/** VO-2 / VO-3 persisted JSON document version constants. */
export const ONBOARDING_SOURCE_SNAPSHOT_VERSION = 1;
export const VEHICLE_IDENTITY_DRAFT_VERSION = 1;
export const VEHICLE_ADMIN_BASELINE_DRAFT_VERSION = 1;
export const VEHICLE_TECHNICAL_BASELINE_DRAFT_VERSION = 1;
export const VEHICLE_VALIDATION_FINDINGS_VERSION = 1;
export const READINESS_SNAPSHOT_VERSION = 1;
export const ACTIVATION_OUTBOX_PAYLOAD_VERSION = 1;
