import type {
  EvaluationsAggregationType,
  EvaluationsComparison,
  EvaluationsDataClassification,
  EvaluationsDimension,
  EvaluationsImplementationStatus,
  EvaluationsMetricCategory,
  EvaluationsMetricDefinition,
  EvaluationsMetricKind,
  EvaluationsMetricUnit,
  EvaluationsValueType,
} from '@synq/evaluations-metrics/evaluations-metric.contract';
import {
  evaluationsMetricDescriptionKey,
  evaluationsMetricLabelKey,
} from '@synq/evaluations-metrics/evaluations-metric.i18n';

type MetricInput = {
  id: string;
  category: EvaluationsMetricCategory;
  unit: EvaluationsMetricUnit;
  valueType: EvaluationsValueType;
  aggregationType: EvaluationsAggregationType;
  calculationVersion: string;
  supportedDimensions: readonly EvaluationsDimension[];
  supportedComparisons: readonly EvaluationsComparison[];
  dataClassification: EvaluationsDataClassification;
  metricKind: EvaluationsMetricKind;
  implementationStatus: EvaluationsImplementationStatus;
  supersededBy?: string;
};

const ORG: readonly EvaluationsDimension[] = ['organizationId'];
const ORG_STATION: readonly EvaluationsDimension[] = ['organizationId', 'stationId'];
const ORG_VEHICLE: readonly EvaluationsDimension[] = ['organizationId', 'vehicleId'];
const ORG_CUSTOMER: readonly EvaluationsDimension[] = ['organizationId', 'customerId'];

function m(input: MetricInput): EvaluationsMetricDefinition {
  return {
    id: input.id,
    category: input.category,
    labelKey: evaluationsMetricLabelKey(input.id),
    descriptionKey: evaluationsMetricDescriptionKey(input.id),
    unit: input.unit,
    valueType: input.valueType,
    aggregationType: input.aggregationType,
    calculationVersion: input.calculationVersion,
    supportedDimensions: input.supportedDimensions,
    supportedComparisons: input.supportedComparisons,
    dataClassification: input.dataClassification,
    metricKind: input.metricKind,
    implementationStatus: input.implementationStatus,
    ...(input.supersededBy ? { supersededBy: input.supersededBy } : {}),
  };
}

/** Canonical metric definitions — aligned with evaluations-kpi-taxonomy.md v1.0.0 */
export const EVALUATIONS_METRIC_DEFINITIONS: readonly EvaluationsMetricDefinition[] = [
  // ─── Revenue ─────────────────────────────────────────────────────────────
  m({
    id: 'fin.mtd_issued_revenue',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.issued_revenue_strict_mtd',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.mtd_paid_revenue',
    category: 'CASHFLOW',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.cash_inflow_mtd',
    category: 'CASHFLOW',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'deprecated',
    supersededBy: 'fin.mtd_paid_revenue',
  }),
  m({
    id: 'fin.reserved_revenue_mtd',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'prepared',
  }),
  m({
    id: 'fin.avg_invoice_value_mtd',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'AVG',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.daily_revenue_mtd',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.top_customers_mtd',
    category: 'CUSTOMERS',
    unit: 'EUR',
    valueType: 'LIST',
    aggregationType: 'LIST_TOP_N',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_CUSTOMER,
    supportedComparisons: ['none'],
    dataClassification: 'PII_AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active_degraded',
  }),
  m({
    id: 'fin.top_vehicles_mtd',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'LIST',
    aggregationType: 'LIST_TOP_N',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.mom_revenue_delta_pct',
    category: 'REVENUE',
    unit: 'PERCENT',
    valueType: 'PERCENT',
    aggregationType: 'RATIO',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.revenue_lost_actual_mtd',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'planned',
  }),

  // ─── Cashflow ────────────────────────────────────────────────────────────
  m({
    id: 'fin.cashflow_net_mtd',
    category: 'CASHFLOW',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'planned',
  }),

  // ─── Receivables ───────────────────────────────────────────────────────
  m({
    id: 'fin.open_receivables',
    category: 'RECEIVABLES',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.overdue_receivables',
    category: 'RECEIVABLES',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.total_outstanding_receivables',
    category: 'RECEIVABLES',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.open_receivables_cockpit',
    category: 'RECEIVABLES',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'deprecated',
    supersededBy: 'fin.open_receivables',
  }),

  // ─── Costs & result ────────────────────────────────────────────────────
  m({
    id: 'fin.mtd_expenses',
    category: 'COSTS',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.daily_expenses_mtd',
    category: 'COSTS',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.mom_expense_delta_pct',
    category: 'COSTS',
    unit: 'PERCENT',
    valueType: 'PERCENT',
    aggregationType: 'RATIO',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.mtd_net_result',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.profit_margin_mtd',
    category: 'REVENUE',
    unit: 'PERCENT',
    valueType: 'PERCENT',
    aggregationType: 'RATIO',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.daily_net_result_mtd',
    category: 'REVENUE',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.contribution_margin_mtd',
    category: 'CONTRIBUTION_MARGIN',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'planned',
  }),

  // ─── Bookings / invoice counts ─────────────────────────────────────────
  m({
    id: 'fin.recent_invoice_activity',
    category: 'BOOKINGS',
    unit: 'COUNT',
    valueType: 'LIST',
    aggregationType: 'LIST_TOP_N',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'PII_ROW',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.mtd_open_invoice_count',
    category: 'BOOKINGS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.mtd_paid_invoice_count',
    category: 'BOOKINGS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.mtd_expense_invoice_count',
    category: 'COSTS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'fin.org_invoice_count',
    category: 'BOOKINGS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),

  // ─── Utilization & downtime ────────────────────────────────────────────
  m({
    id: 'ins.low_utilization',
    category: 'UTILIZATION',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_STATION,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'RULE_BASED_ESTIMATE',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.low_utilization.revenue_potential_eur',
    category: 'UTILIZATION',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'RULE_BASED_ESTIMATE',
    implementationStatus: 'active',
  }),
  m({
    id: 'ops.vehicle_idle_days',
    category: 'DOWNTIME',
    unit: 'DAYS',
    valueType: 'DURATION_DAYS',
    aggregationType: 'LAST',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'RULE_BASED_ESTIMATE',
    implementationStatus: 'active',
  }),
  m({
    id: 'ops.fleet_utilization_pct',
    category: 'UTILIZATION',
    unit: 'PERCENT',
    valueType: 'PERCENT',
    aggregationType: 'RATIO',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_STATION,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'planned',
  }),

  // ─── Fleet availability & stations ───────────────────────────────────────
  m({
    id: 'ins.station_shortage',
    category: 'STATIONS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_STATION,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.station_available_vehicle_count',
    category: 'FLEET_AVAILABILITY',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'MIN',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_STATION,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ops.station_revenue_rank_mtd',
    category: 'STATIONS',
    unit: 'EUR',
    valueType: 'LIST',
    aggregationType: 'LIST_TOP_N',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_STATION,
    supportedComparisons: ['mom'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'planned',
  }),

  // ─── Maintenance & compliance insights ─────────────────────────────────
  m({
    id: 'ins.tight_handover',
    category: 'BOOKINGS',
    unit: 'MINUTES',
    valueType: 'DURATION_MINUTES',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.return_needs_inspection',
    category: 'BOOKINGS',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.service_window',
    category: 'MAINTENANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.service_before_booking',
    category: 'MAINTENANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.service_overdue',
    category: 'COMPLIANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.tuv_overdue',
    category: 'COMPLIANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.bokraft_overdue',
    category: 'COMPLIANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.hm_service_no_tracking',
    category: 'DATA_QUALITY',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),

  // ─── Health-gated & pickup ─────────────────────────────────────────────
  m({
    id: 'ins.battery_critical_gated',
    category: 'MAINTENANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.tire_critical_gated',
    category: 'MAINTENANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.brake_critical_gated',
    category: 'MAINTENANCE',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.health_booking_financial_impact_eur',
    category: 'RISKS',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ['organizationId', 'vehicleId', 'bookingId'],
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'RULE_BASED_ESTIMATE',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.pickup_overdue',
    category: 'BOOKINGS',
    unit: 'MINUTES',
    valueType: 'DURATION_MINUTES',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ['organizationId', 'customerId', 'bookingId'],
    supportedComparisons: ['none'],
    dataClassification: 'PII_ROW',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.driving_assessment_device_quality',
    category: 'DATA_QUALITY',
    unit: 'NONE',
    valueType: 'ENUM',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'OPERATIONAL_SIGNAL',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),

  // ─── Cockpit aggregates ────────────────────────────────────────────────
  m({
    id: 'ins.business_risks_count',
    category: 'RISKS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_STATION,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active_degraded',
  }),
  m({
    id: 'ins.estimated_financial_exposure_eur',
    category: 'RISKS',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'RULE_BASED_ESTIMATE',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.estimated_financial_risk',
    category: 'RISKS',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'RULE_BASED_ESTIMATE',
    implementationStatus: 'deprecated',
    supersededBy: 'ins.estimated_financial_exposure_eur',
  }),
  m({
    id: 'ins.critical_insights_count',
    category: 'RISKS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.critical_bookings_count',
    category: 'RISKS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'deprecated',
    supersededBy: 'ins.critical_insights_count',
  }),
  m({
    id: 'ins.revenue_leakage_count',
    category: 'REVENUE',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.recommendations_visible_count',
    category: 'RECOMMENDATIONS',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.misuse_cases_visible_count',
    category: 'DAMAGE',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'PII_ROW',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.insights_run_stale',
    category: 'OPERATIONAL_QUALITY',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'ins.insights_run_error',
    category: 'OPERATIONAL_QUALITY',
    unit: 'NONE',
    valueType: 'BOOLEAN',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),

  // ─── Data analyse ──────────────────────────────────────────────────────
  m({
    id: 'da.telemetry_last_received',
    category: 'DATA_QUALITY',
    unit: 'DATETIME',
    valueType: 'DATETIME',
    aggregationType: 'LAST',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'da.signals_observed_count',
    category: 'DATA_QUALITY',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'da.hf_availability_status',
    category: 'DATA_QUALITY',
    unit: 'ENUM',
    valueType: 'ENUM',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'DERIVED',
    implementationStatus: 'active_degraded',
  }),
  m({
    id: 'da.avg_signal_interval_ms',
    category: 'DATA_QUALITY',
    unit: 'MILLISECONDS',
    valueType: 'DURATION_MILLISECONDS',
    aggregationType: 'AVG',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'DERIVED',
    implementationStatus: 'active_degraded',
  }),
  m({
    id: 'da.data_freshness_status',
    category: 'DATA_QUALITY',
    unit: 'ENUM',
    valueType: 'ENUM',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'DERIVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'da.signal_quality_score',
    category: 'DATA_QUALITY',
    unit: 'SCORE',
    valueType: 'SCORE',
    aggregationType: 'LAST',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active_degraded',
  }),
  m({
    id: 'da.pipeline_stages',
    category: 'DATA_QUALITY',
    unit: 'ENUM',
    valueType: 'ENUM',
    aggregationType: 'STATUS',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'da.health_trace',
    category: 'DATA_QUALITY',
    unit: 'TEXT',
    valueType: 'TEXT',
    aggregationType: 'LAST',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),
  m({
    id: 'da.clickhouse_diagnostics',
    category: 'DATA_QUALITY',
    unit: 'TEXT',
    valueType: 'TEXT',
    aggregationType: 'LAST',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'DIAGNOSTIC',
    metricKind: 'OBSERVED',
    implementationStatus: 'active',
  }),

  // ─── Forecasts (planned) ─────────────────────────────────────────────────
  m({
    id: 'fc.revenue_forecast_30d',
    category: 'FORECASTS',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'STATISTICAL_FORECAST',
    implementationStatus: 'planned',
  }),
  m({
    id: 'fc.utilization_forecast_30d',
    category: 'FORECASTS',
    unit: 'PERCENT',
    valueType: 'PERCENT',
    aggregationType: 'RATIO',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_STATION,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'STATISTICAL_FORECAST',
    implementationStatus: 'planned',
  }),
  m({
    id: 'fc.receivables_collection_forecast',
    category: 'FORECASTS',
    unit: 'EUR',
    valueType: 'MONEY',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'STATISTICAL_FORECAST',
    implementationStatus: 'planned',
  }),
  m({
    id: 'fc.maintenance_downtime_forecast',
    category: 'FORECASTS',
    unit: 'DAYS',
    valueType: 'DURATION_DAYS',
    aggregationType: 'SUM',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG_VEHICLE,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'STATISTICAL_FORECAST',
    implementationStatus: 'planned',
  }),

  // ─── Operational (planned) ───────────────────────────────────────────────
  m({
    id: 'ops.strengths_count',
    category: 'OPERATIONAL_QUALITY',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'planned',
  }),
  m({
    id: 'ops.weaknesses_count',
    category: 'OPERATIONAL_QUALITY',
    unit: 'COUNT',
    valueType: 'COUNT',
    aggregationType: 'COUNT',
    calculationVersion: '1.0.0',
    supportedDimensions: ORG,
    supportedComparisons: ['none'],
    dataClassification: 'AGGREGATE',
    metricKind: 'DERIVED',
    implementationStatus: 'planned',
  }),
];
