export const M3_3_HV_H4_A3_RETENTION_GATE_REASON = {
  CURRENT_SOURCE_REVISION_NOT_DURABLY_ACKED: 'CURRENT_SOURCE_REVISION_NOT_DURABLY_ACKED',
  HV_CAPACITY_OBSERVATION_REFERENCE: 'HV_CAPACITY_OBSERVATION_REFERENCE',
  RETENTION_CUTOFF_NOT_MET: 'RETENTION_CUTOFF_NOT_MET',
} as const;

export type M3_3HvH4A3RetentionGateBlockKind =
  | 'BLOCKED_CAPACITY_OBSERVATION_REFERENCE'
  | 'BLOCKED_CURRENT_REVISION_MISSING'
  | 'BLOCKED_ACK_MISSING'
  | 'BLOCKED_ACK_IDENTITY_MISMATCH'
  | 'BLOCKED_REVISION_INTEGRITY'
  | 'BLOCKED_CONTRACT_VERSION'
  | 'BLOCKED_RETENTION_CUTOFF';

export type M3_3HvH4A3RetentionGateOutcomeKind =
  | 'DELETED'
  | 'DRY_RUN_ELIGIBLE'
  | 'ALREADY_GONE'
  | 'BLOCKED';

export interface M3_3HvH4A3RetentionGateOutcomeV1 {
  kind: M3_3HvH4A3RetentionGateOutcomeKind;
  blockKind?: M3_3HvH4A3RetentionGateBlockKind;
  reasonCode?: string;
}
