import {
  A3_ATTESTATION_FUTURE_ADMISSION_AUTHORITY_CONTRACT_DEFINED,
  A3_ATTESTATION_INTERNAL_WORKFLOW_ORIGIN_AUTHORIZED,
  A3_ATTESTATION_PRODUCTION_ADMISSION_AUTHORITY_COMPLETE,
  A3_ATTESTATION_REQUESTED_BY_AUTHENTICATED,
  A3_ATTESTATION_REVISION_TENANT_SCOPE_MATCH_VERIFIED_BY_ISSUER,
} from './m3-3-hv-h4-a3.constants';

describe('m3-3-hv-h4-a3-o2-r3-h1 admission authority boundary constants', () => {
  it('distinguishes tenant scope verification from authenticated admission', () => {
    expect(A3_ATTESTATION_REVISION_TENANT_SCOPE_MATCH_VERIFIED_BY_ISSUER).toBe(true);
    expect(A3_ATTESTATION_REQUESTED_BY_AUTHENTICATED).toBe(false);
    expect(A3_ATTESTATION_INTERNAL_WORKFLOW_ORIGIN_AUTHORIZED).toBe(false);
    expect(A3_ATTESTATION_PRODUCTION_ADMISSION_AUTHORITY_COMPLETE).toBe(false);
    expect(A3_ATTESTATION_FUTURE_ADMISSION_AUTHORITY_CONTRACT_DEFINED).toBe(true);
  });
});
