import { M3_3_HV_H4_EXPOSURE_SOURCE_AUTHORITY_V1 } from './m3-3-hv-h4.constants';
import type {
  M3_3HvH4ExposureAxisAuthorityV1,
  M3_3HvH4ExposureSourceAuthorityContractV1,
} from './m3-3-hv-h4.types';

/** Static H4 axis authority — no upgrade beyond A0 audit without new evidence. */
export function buildM3_3HvH4ExposureSourceAuthorityContractV1(): M3_3HvH4ExposureSourceAuthorityContractV1 {
  const axes: M3_3HvH4ExposureAxisAuthorityV1[] = [
    {
      axis: 'CALENDAR_TIME',
      unit: 'ISO-8601 instant',
      semanticAuthority: 'OBSERVATION_CALENDAR_TIME',
      coverageClass: 'BOUNDED_GAP_AWARE',
      sourceAuthorityClass: 'POSTGRES_CANONICAL',
      lifecycleScope: 'PER_HV_LIFECYCLE_SEGMENT',
      retentionContinuity: 'WINDOW_LIMITED',
      replacementSegmentable: true,
      integrationAllowed: true,
      normalizationAllowed: false,
      customerUseAllowed: false,
    },
    {
      axis: 'ODOMETER_KM',
      unit: 'km',
      semanticAuthority: 'VEHICLE_ODOMETER_POINT',
      coverageClass: 'POINT_CONTEXT_ONLY',
      sourceAuthorityClass: 'POSTGRES_POINT_HISTORY',
      lifecycleScope: 'PER_HV_LIFECYCLE_SEGMENT',
      retentionContinuity: 'WINDOW_LIMITED',
      replacementSegmentable: true,
      integrationAllowed: false,
      normalizationAllowed: false,
      customerUseAllowed: false,
    },
    {
      axis: 'CHARGE_THROUGHPUT_KWH',
      unit: 'kWh',
      semanticAuthority: 'PROVIDER_CHARGING_ADDED_ENERGY_SESSION',
      coverageClass: 'BOUNDED_GAP_AWARE',
      sourceAuthorityClass: 'POSTGRES_SESSION_EPISODE',
      lifecycleScope: 'PER_HV_LIFECYCLE_SEGMENT',
      retentionContinuity: 'WINDOW_LIMITED',
      replacementSegmentable: true,
      integrationAllowed: false,
      normalizationAllowed: false,
      customerUseAllowed: false,
    },
    {
      axis: 'FULL_EQUIVALENT_CYCLES',
      unit: null,
      semanticAuthority: 'FEC_UNDEFINED',
      coverageClass: 'UNAVAILABLE',
      sourceAuthorityClass: 'NONE',
      lifecycleScope: 'PER_HV_LIFECYCLE_SEGMENT',
      retentionContinuity: 'UNKNOWN',
      replacementSegmentable: true,
      integrationAllowed: false,
      normalizationAllowed: false,
      customerUseAllowed: false,
    },
    {
      axis: 'TEMPERATURE_EXPOSURE',
      unit: 'celsius-point',
      semanticAuthority: 'BATTERY_TEMPERATURE_POINT',
      coverageClass: 'POINT_CONTEXT_ONLY',
      sourceAuthorityClass: 'POSTGRES_POINT_HISTORY',
      lifecycleScope: 'PER_HV_LIFECYCLE_SEGMENT',
      retentionContinuity: 'WINDOW_LIMITED',
      replacementSegmentable: true,
      integrationAllowed: false,
      normalizationAllowed: false,
      customerUseAllowed: false,
    },
    {
      axis: 'SOC_WINDOW_EXPOSURE',
      unit: 'soc-percent-point',
      semanticAuthority: 'SOC_PERCENT_POINT',
      coverageClass: 'POINT_CONTEXT_ONLY',
      sourceAuthorityClass: 'POSTGRES_POINT_HISTORY',
      lifecycleScope: 'PER_HV_LIFECYCLE_SEGMENT',
      retentionContinuity: 'WINDOW_LIMITED',
      replacementSegmentable: true,
      integrationAllowed: false,
      normalizationAllowed: false,
      customerUseAllowed: false,
    },
    {
      axis: 'FAST_CHARGE_EXPOSURE',
      unit: 'kW-point',
      semanticAuthority: 'CHARGING_POWER_POINT',
      coverageClass: 'POINT_CONTEXT_ONLY',
      sourceAuthorityClass: 'POSTGRES_POINT_HISTORY',
      lifecycleScope: 'PER_HV_LIFECYCLE_SEGMENT',
      retentionContinuity: 'WINDOW_LIMITED',
      replacementSegmentable: true,
      integrationAllowed: false,
      normalizationAllowed: false,
      customerUseAllowed: false,
    },
  ];

  return {
    version: M3_3_HV_H4_EXPOSURE_SOURCE_AUTHORITY_V1,
    axes,
  };
}
