import { InsightType } from '@prisma/client';
import type { TaskAutomationCatalogKey, TaskAutomationRuleDefinition } from './task-automation-rule.types';
import {
  BOOKING_LIFECYCLE_ORG_OVERRIDE_FIELDS,
  DOCUMENT_PACKAGE_ORG_OVERRIDE_FIELDS,
  INSIGHT_HEALTH_ORG_OVERRIDE_FIELDS,
  INVOICE_PAYMENT_ORG_OVERRIDE_FIELDS,
  markOrgOverridableConfigurableFields,
  REPAIR_ORG_OVERRIDE_FIELDS,
  VEHICLE_CLEANING_ORG_OVERRIDE_FIELDS,
} from './task-automation-rule-override.fields';

const PROTECTED_AUTOMATION_FIELDS = [
  'ruleId',
  'version',
  'dedupScope',
  'taskType',
  'sourceType',
  'protectedFields',
] as const;

function materializationRule(
  catalogKey: TaskAutomationCatalogKey,
  rule: Omit<TaskAutomationRuleDefinition, 'catalogKey' | 'materializesTask'>,
): TaskAutomationRuleDefinition {
  return { ...rule, catalogKey, materializesTask: true };
}

function lifecycleRule(
  rule: Omit<TaskAutomationRuleDefinition, 'catalogKey' | 'materializesTask'>,
): TaskAutomationRuleDefinition {
  return { ...rule, materializesTask: false };
}

/** Canonical, code-defined automation rule catalog — single source of truth for rule identity and defaults. */
export const TASK_AUTOMATION_RULE_CATALOG: readonly TaskAutomationRuleDefinition[] = [
  // ─── Booking lifecycle materialization ─────────────────────────────────────
  materializationRule('BOOKING_PREPARATION', {
    ruleId: 'booking.lifecycle.confirmed.prep',
    version: 1,
    nameDe: 'Buchung vorbereiten',
    descriptionDe:
      'Vorbereitung einer bestätigten Buchung vor der Fahrzeugübergabe (Dokumente, Reinigung, Verfügbarkeit).',
    sourceType: 'BOOKING',
    taskType: 'BOOKING_PREPARATION',
    defaultEnabled: true,
    activationStrategy: 'ON_BOOKING_CONFIRMED',
    dueStrategy: 'BOOKING_PREPARATION_TIMING',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'STATION_FROM_BOOKING',
    dedupScope: {
      kind: 'PER_BOOKING',
      keyTemplate: 'booking:prep:{bookingId}',
      legacyKeyTemplates: ['booking:document:{bookingId}'],
    },
    autoResolveCondition: 'HANDOVER_PICKUP_COMPLETED | BOOKING_CANCELLED | BOOKING_NO_SHOW',
    supersedeConditions: ['BOOKING_STATUS_NOT_CONFIRMED', 'BOOKING_LIFECYCLE_SUPERSEDE'],
    checklistTemplateId: 'BOOKING_PREPARATION',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  materializationRule('BOOKING_PICKUP', {
    ruleId: 'booking.lifecycle.confirmed.pickup',
    version: 1,
    nameDe: 'Fahrzeugübergabe (Pickup)',
    descriptionDe: 'Operative Übergabeaufgabe für eine bestätigte Buchung zum Pickup-Zeitpunkt.',
    sourceType: 'BOOKING',
    taskType: 'BOOKING_PICKUP',
    defaultEnabled: true,
    activationStrategy: 'ON_BOOKING_CONFIRMED',
    dueStrategy: 'BOOKING_PICKUP_MILESTONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'STATION_FROM_BOOKING',
    dedupScope: {
      kind: 'PER_BOOKING',
      keyTemplate: 'booking:pickup:{bookingId}',
    },
    autoResolveCondition: 'HANDOVER_PICKUP_COMPLETED | BOOKING_CANCELLED | BOOKING_NO_SHOW',
    supersedeConditions: ['BOOKING_STATUS_NOT_CONFIRMED', 'BOOKING_LIFECYCLE_SUPERSEDE'],
    checklistTemplateId: 'BOOKING_PICKUP',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  materializationRule('BOOKING_RETURN', {
    ruleId: 'booking.lifecycle.active.return',
    version: 1,
    nameDe: 'Fahrzeugrücknahme (Return)',
    descriptionDe: 'Operative Rücknahmeaufgabe für eine aktive Buchung zum Return-Zeitpunkt.',
    sourceType: 'BOOKING',
    taskType: 'BOOKING_RETURN',
    defaultEnabled: true,
    activationStrategy: 'ON_BOOKING_ACTIVE',
    dueStrategy: 'BOOKING_RETURN_MILESTONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'STATION_FROM_BOOKING',
    dedupScope: {
      kind: 'PER_BOOKING',
      keyTemplate: 'booking:return:{bookingId}',
    },
    autoResolveCondition: 'HANDOVER_RETURN_COMPLETED | BOOKING_CANCELLED',
    supersedeConditions: ['BOOKING_STATUS_NOT_ACTIVE', 'BOOKING_LIFECYCLE_SUPERSEDE'],
    checklistTemplateId: 'BOOKING_RETURN',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  // ─── Document package ──────────────────────────────────────────────────────
  materializationRule('DOCUMENT_PACKAGE_INCOMPLETE', {
    ruleId: 'booking.document.package.review',
    version: 1,
    nameDe: 'Dokumentenpaket unvollständig',
    descriptionDe:
      'Fehlende Pflichtdokumente im Buchungspaket prüfen oder erzeugen (ein Task pro Phase).',
    sourceType: 'DOCUMENT',
    taskType: 'DOCUMENT_REVIEW',
    defaultEnabled: true,
    activationStrategy: 'ON_DOCUMENT_PACKAGE_GAP',
    dueStrategy: 'IMMEDIATE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'INHERIT_FROM_CONTEXT',
    dedupScope: {
      kind: 'PER_BOOKING_PHASE',
      keyTemplate: 'document:package:{phase}:{bookingId}',
      legacyKeyTemplates: ['document:{documentType}:{bookingId}'],
    },
    autoResolveCondition: 'DOCUMENT_PACKAGE_COMPLETE',
    supersedeConditions: ['DOCUMENT_PHASE_CHANGED', 'BOOKING_LIFECYCLE_SUPERSEDE'],
    checklistTemplateId: 'DOCUMENT_REVIEW',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'DOCUMENT',
    category: 'Documents',
  }),

  // ─── Invoice payment ───────────────────────────────────────────────────────
  materializationRule('INVOICE_PAYMENT_CHECK', {
    ruleId: 'invoice.payment.check',
    version: 1,
    nameDe: 'Zahlungseingang prüfen',
    descriptionDe: 'Offene Ausgangs- oder Eingangsrechnung — Zahlungseingang prüfen oder verbuchen.',
    sourceType: 'SYSTEM',
    taskType: 'INVOICE_REQUIRED',
    defaultEnabled: true,
    activationStrategy: 'ON_INVOICE_PAYMENT_OPEN',
    dueStrategy: 'INVOICE_DUE_DATE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: {
      kind: 'PER_INVOICE',
      keyTemplate: 'invoice:payment-check:{invoiceId}',
      legacyKeyTemplates: ['invoice:unpaid:{invoiceId}'],
    },
    autoResolveCondition: 'PAYMENT_RECEIVED',
    supersedeConditions: ['INVOICE_CANCELLED', 'INVOICE_VOIDED', 'INVOICE_CREDITED'],
    checklistTemplateId: 'INVOICE_REQUIRED',
    configurableFields: markOrgOverridableConfigurableFields([
      {
        field: 'defaultDueDays',
        type: 'number',
        defaultValue: 14,
        descriptionDe: 'Standard-Fälligkeit ohne explizites Rechnungsdatum',
      },
      {
        field: 'criticalOverdueAfterDays',
        type: 'number',
        defaultValue: 7,
        descriptionDe: 'Eskalation auf CRITICAL nach Überfälligkeit (Kalendertage)',
      },
      {
        field: 'overduePriority',
        type: 'string',
        defaultValue: 'HIGH',
        descriptionDe: 'Priorität nach erstem Überfälligkeitstag',
      },
    ]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INVOICE',
    category: 'invoice',
  }),

  // ─── Vehicle cleaning ──────────────────────────────────────────────────────
  materializationRule('VEHICLE_CLEANING_REQUIRED', {
    ruleId: 'vehicle.cleaning.required',
    version: 1,
    nameDe: 'Fahrzeugreinigung erforderlich',
    descriptionDe:
      'Fahrzeug muss vor der nächsten Übergabe oder eigenständig gereinigt werden (ein Task pro Vorbereitungsfenster).',
    sourceType: 'SYSTEM',
    taskType: 'VEHICLE_CLEANING',
    defaultEnabled: true,
    activationStrategy: 'ON_VEHICLE_NEEDS_CLEANING',
    dueStrategy: 'IMMEDIATE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'STATION_FROM_BOOKING',
    dedupScope: {
      kind: 'PER_VEHICLE_CLEANING_WINDOW',
      keyTemplate: 'vehicle:cleaning:{vehicleId}:{purposeSuffix}',
      legacyKeyTemplates: [
        'booking:clean:{bookingId}',
        'vehicle:cleaning:{vehicleId}',
      ],
    },
    autoResolveCondition: 'VEHICLE_CLEANED | BOOKING_CANCELLED | BOOKING_VEHICLE_CHANGED',
    supersedeConditions: ['CLEANING_TASK_SUPERSEDED', 'BOOKING_LIFECYCLE_SUPERSEDE'],
    checklistTemplateId: 'VEHICLE_CLEANING',
    configurableFields: markOrgOverridableConfigurableFields([
      {
        field: 'urgentBeforePickupHours',
        type: 'number',
        defaultValue: 24,
        descriptionDe: 'Eskalation auf HIGH wenn Pickup innerhalb dieser Stunden',
      },
    ]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'VEHICLE_CLEANING',
    category: 'Cleaning',
  }),

  // ─── Insight / health materialization ──────────────────────────────────────
  materializationRule('VEHICLE_SERVICE_OVERDUE', {
    ruleId: 'insight.service_overdue',
    version: 1,
    nameDe: 'Service überfällig',
    descriptionDe:
      'Hersteller-Serviceintervall überschritten oder kritisch — Servicehistorie prüfen und terminieren.',
    sourceType: 'ALERT',
    taskType: 'VEHICLE_SERVICE',
    defaultEnabled: true,
    activationStrategy: 'ON_INSIGHT_MATERIALIZE',
    dueStrategy: 'INSIGHT_TIME_CONTEXT',
    defaultPriority: 'HIGH',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: {
      kind: 'PER_VEHICLE',
      keyTemplate: 'service_overdue:{vehicleId}',
    },
    autoResolveCondition:
      'SERVICE_SCHEDULED | SERVICE_ALREADY_COMPLETED | SERVICE_DUE_DATE_CORRECTED | FALSE_POSITIVE | SERVICE_CASE_COMPLETED',
    supersedeConditions: ['INSIGHT_STALE', 'SERVICE_INTERVAL_OK'],
    checklistTemplateId: 'VEHICLE_SERVICE',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INSIGHT_SERVICE',
    category: 'Maintenance',
    insightType: InsightType.SERVICE_OVERDUE,
  }),

  materializationRule('VEHICLE_INSPECTION_TUV_DUE', {
    ruleId: 'insight.compliance.tuv_overdue',
    version: 1,
    nameDe: 'TÜV/HU fällig',
    descriptionDe: 'TÜV- oder Hauptuntersuchung überfällig oder kritisch — Termin vorbereiten.',
    sourceType: 'ALERT',
    taskType: 'VEHICLE_INSPECTION',
    defaultEnabled: true,
    activationStrategy: 'ON_INSIGHT_MATERIALIZE',
    dueStrategy: 'INSIGHT_TIME_CONTEXT',
    defaultPriority: 'HIGH',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: {
      kind: 'PER_VEHICLE',
      keyTemplate: 'tuv_overdue:{vehicleId}',
    },
    autoResolveCondition: 'TUV_PASSED | TUV_SCHEDULED | FALSE_POSITIVE',
    supersedeConditions: ['INSIGHT_STALE', 'COMPLIANCE_OK'],
    checklistTemplateId: 'VEHICLE_INSPECTION',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INSIGHT_COMPLIANCE',
    category: 'TÜV',
    insightType: InsightType.TUV_OVERDUE,
  }),

  materializationRule('VEHICLE_INSPECTION_BOKRAFT_DUE', {
    ruleId: 'insight.compliance.bokraft_overdue',
    version: 1,
    nameDe: 'BOKraft fällig',
    descriptionDe: 'BOKraft-Prüfung überfällig oder kritisch — Termin vorbereiten.',
    sourceType: 'ALERT',
    taskType: 'VEHICLE_INSPECTION',
    defaultEnabled: true,
    activationStrategy: 'ON_INSIGHT_MATERIALIZE',
    dueStrategy: 'INSIGHT_TIME_CONTEXT',
    defaultPriority: 'HIGH',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: {
      kind: 'PER_VEHICLE',
      keyTemplate: 'bokraft_overdue:{vehicleId}',
    },
    autoResolveCondition: 'BOKRAFT_PASSED | BOKRAFT_SCHEDULED | FALSE_POSITIVE',
    supersedeConditions: ['INSIGHT_STALE', 'COMPLIANCE_OK'],
    checklistTemplateId: 'VEHICLE_INSPECTION',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INSIGHT_COMPLIANCE',
    category: 'BOKraft',
    insightType: InsightType.BOKRAFT_OVERDUE,
  }),

  materializationRule('TIRE_CRITICAL_HEALTH', {
    ruleId: 'insight.health.tire_critical',
    version: 1,
    nameDe: 'Reifen kritisch',
    descriptionDe: 'Kritischer Reifenzustand — Profiltiefe und Beschädigungen prüfen.',
    sourceType: 'ALERT',
    taskType: 'TIRE_CHECK',
    defaultEnabled: true,
    activationStrategy: 'ON_INSIGHT_MATERIALIZE',
    dueStrategy: 'IMMEDIATE',
    defaultPriority: 'HIGH',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: {
      kind: 'PER_VEHICLE',
      keyTemplate: 'tire_critical:{vehicleId}',
    },
    autoResolveCondition: 'TIRE_MEASURED_OK | TIRE_REPLACED | TIRE_ROTATED | FALSE_POSITIVE',
    supersedeConditions: ['INSIGHT_STALE'],
    checklistTemplateId: 'TIRE_CHECK',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INSIGHT_HEALTH',
    category: 'Tire Change',
    insightType: InsightType.TIRE_CRITICAL,
  }),

  materializationRule('BRAKE_CRITICAL_HEALTH', {
    ruleId: 'insight.health.brake_critical',
    version: 1,
    nameDe: 'Bremsen kritisch',
    descriptionDe: 'Kritischer Bremszustand — Sichtprüfung und Messwerte erfassen.',
    sourceType: 'ALERT',
    taskType: 'BRAKE_CHECK',
    defaultEnabled: true,
    activationStrategy: 'ON_INSIGHT_MATERIALIZE',
    dueStrategy: 'IMMEDIATE',
    defaultPriority: 'HIGH',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: {
      kind: 'PER_VEHICLE',
      keyTemplate: 'brake_critical:{vehicleId}',
    },
    autoResolveCondition: 'BRAKE_MEASURED_OK | BRAKE_PARTS_REPLACED | FALSE_POSITIVE',
    supersedeConditions: ['INSIGHT_STALE'],
    checklistTemplateId: 'BRAKE_CHECK',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INSIGHT_HEALTH',
    category: 'Repair',
    insightType: InsightType.BRAKE_CRITICAL,
  }),

  materializationRule('BATTERY_CRITICAL_HEALTH', {
    ruleId: 'insight.health.battery_critical',
    version: 1,
    nameDe: 'Batterie — operative Aufgaben',
    descriptionDe:
      'Handlungsfähige Battery-Alerts und bestätigte Evidenz erzeugen semantische Tasks (12V-Prüfung, Warnleuchte, BMS-Bericht, Referenzkapazität). Kein Task aus Shadow oder experimentellen Messungen.',
    sourceType: 'ALERT',
    taskType: 'BATTERY_CHECK',
    defaultEnabled: true,
    activationStrategy: 'ON_INSIGHT_MATERIALIZE',
    dueStrategy: 'IMMEDIATE',
    defaultPriority: 'HIGH',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: {
      kind: 'PER_VEHICLE',
      keyTemplate: 'battery_task:{vehicleId}:{taskIntent}',
      legacyKeyTemplates: ['battery_critical:{vehicleId}'],
    },
    autoResolveCondition:
      'BATTERY_MEASURED_OK | BATTERY_REPLACED | REFERENCE_CAPACITY_VERIFIED | WARNING_LIGHT_CLEARED | WORKSHOP_RESOLVED | FALSE_POSITIVE',
    supersedeConditions: ['INSIGHT_STALE'],
    checklistTemplateId: 'BATTERY_CHECK',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INSIGHT_HEALTH',
    category: 'Maintenance',
    insightType: InsightType.BATTERY_CRITICAL,
  }),

  // ─── Vendor repair ─────────────────────────────────────────────────────────
  materializationRule('REPAIR_REQUIRED', {
    ruleId: 'vendor.repair.ensure',
    version: 1,
    nameDe: 'Reparatur erforderlich',
    descriptionDe: 'Werkstatt- oder Schadensreparatur am Fahrzeug beauftragen oder durchführen.',
    sourceType: 'VENDOR',
    taskType: 'REPAIR',
    defaultEnabled: true,
    activationStrategy: 'ON_VENDOR_REPAIR_REQUEST',
    dueStrategy: 'IMMEDIATE',
    defaultPriority: 'HIGH',
    assignmentStrategy: 'INHERIT_FROM_CONTEXT',
    dedupScope: {
      kind: 'PER_VEHICLE_VENDOR_REASON',
      keyTemplate: 'vendor:repair:{vehicleId}:{vendorId|none}:{reason}',
    },
    autoResolveCondition: 'REPAIR_COMPLETED | PARTS_REPLACED',
    supersedeConditions: ['REPAIR_SUPERSEDED'],
    checklistTemplateId: 'REPAIR',
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'VENDOR',
    category: 'Repair',
  }),

  // ─── Lifecycle / orchestration helpers (no materialization) ────────────────
  lifecycleRule({
    ruleId: 'booking.lifecycle.cancelled',
    version: 1,
    nameDe: 'Buchung storniert',
    descriptionDe: 'Schließt aktive Buchungs-Tasks bei Stornierung.',
    sourceType: 'BOOKING',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: 'BOOKING_CANCELLED',
    supersedeConditions: [],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  lifecycleRule({
    ruleId: 'booking.lifecycle.cancelled.noshow',
    version: 1,
    nameDe: 'Buchung No-Show',
    descriptionDe: 'Schließt aktive Buchungs-Tasks bei No-Show.',
    sourceType: 'BOOKING',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: 'BOOKING_NO_SHOW',
    supersedeConditions: [],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  lifecycleRule({
    ruleId: 'booking.handover.pickup.completed',
    version: 1,
    nameDe: 'Pickup abgeschlossen',
    descriptionDe: 'Schließt Vorbereitungs- und Pickup-Tasks nach abgeschlossener Übergabe.',
    sourceType: 'BOOKING',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: 'HANDOVER_PICKUP_COMPLETED',
    supersedeConditions: [],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  lifecycleRule({
    ruleId: 'booking.handover.return.completed',
    version: 1,
    nameDe: 'Return abgeschlossen',
    descriptionDe: 'Schließt Return-Tasks nach abgeschlossener Rücknahme.',
    sourceType: 'BOOKING',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: 'HANDOVER_RETURN_COMPLETED',
    supersedeConditions: [],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  lifecycleRule({
    ruleId: 'booking.lifecycle.ensure',
    version: 1,
    nameDe: 'Buchungs-Lifecycle synchronisieren',
    descriptionDe: 'Orchestriert die Materialisierung aller Buchungs-Lifecycle-Tasks.',
    sourceType: 'BOOKING',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: '',
    supersedeConditions: [],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'BOOKING',
    category: 'Booking',
  }),

  lifecycleRule({
    ruleId: 'booking.document.package.supersede',
    version: 1,
    nameDe: 'Dokumentenpaket Phase gewechselt',
    descriptionDe: 'Superseded veraltete Dokumentenpaket-Tasks bei Phasenwechsel.',
    sourceType: 'DOCUMENT',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: '',
    supersedeConditions: ['DOCUMENT_PHASE_CHANGED'],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'DOCUMENT',
    category: 'Documents',
  }),

  lifecycleRule({
    ruleId: 'booking.document.package.close_stale',
    version: 1,
    nameDe: 'Veraltete Dokumentenpaket-Tasks schließen',
    descriptionDe: 'Schließt nicht mehr aktive Dokumentenpaket-Tasks.',
    sourceType: 'DOCUMENT',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: '',
    supersedeConditions: ['DOCUMENT_PHASE_CHANGED'],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'DOCUMENT',
    category: 'Documents',
  }),

  lifecycleRule({
    ruleId: 'invoice.payment.received',
    version: 1,
    nameDe: 'Zahlung eingegangen',
    descriptionDe: 'Auto-resolve offener Zahlungsprüf-Tasks bei Zahlungseingang.',
    sourceType: 'SYSTEM',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: 'PAYMENT_RECEIVED',
    supersedeConditions: [],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INVOICE',
    category: 'invoice',
  }),

  lifecycleRule({
    ruleId: 'invoice.payment.terminal',
    version: 1,
    nameDe: 'Rechnung terminal',
    descriptionDe: 'Schließt Zahlungsprüf-Tasks bei stornierten/ungültigen Rechnungen.',
    sourceType: 'SYSTEM',
    taskType: null,
    defaultEnabled: true,
    activationStrategy: 'ON_LIFECYCLE_EVENT',
    dueStrategy: 'NONE',
    defaultPriority: 'NORMAL',
    assignmentStrategy: 'UNASSIGNED',
    dedupScope: { kind: 'NONE', keyTemplate: '' },
    autoResolveCondition: 'INVOICE_CANCELLED | INVOICE_VOIDED | INVOICE_CREDITED',
    supersedeConditions: [],
    checklistTemplateId: null,
    configurableFields: markOrgOverridableConfigurableFields([]),
    protectedFields: [...PROTECTED_AUTOMATION_FIELDS],
    source: 'INVOICE',
    category: 'invoice',
  }),
] as const;

export const MATERIALIZATION_AUTOMATION_RULES = TASK_AUTOMATION_RULE_CATALOG.filter(
  (rule) => rule.materializesTask,
);

export const TASK_AUTOMATION_CATALOG_KEYS: readonly TaskAutomationCatalogKey[] =
  MATERIALIZATION_AUTOMATION_RULES.map(
    (rule) => rule.catalogKey!,
  ) as TaskAutomationCatalogKey[];

/** Which standard org override columns apply per materialization catalog key. */
export const CATALOG_ORG_OVERRIDE_FIELDS: Partial<
  Record<TaskAutomationCatalogKey, readonly import('./task-automation-rule.types').TaskAutomationOrgOverrideFieldKey[]>
> = {
  BOOKING_PREPARATION: BOOKING_LIFECYCLE_ORG_OVERRIDE_FIELDS,
  BOOKING_PICKUP: BOOKING_LIFECYCLE_ORG_OVERRIDE_FIELDS,
  BOOKING_RETURN: BOOKING_LIFECYCLE_ORG_OVERRIDE_FIELDS,
  DOCUMENT_PACKAGE_INCOMPLETE: DOCUMENT_PACKAGE_ORG_OVERRIDE_FIELDS,
  INVOICE_PAYMENT_CHECK: INVOICE_PAYMENT_ORG_OVERRIDE_FIELDS,
  VEHICLE_CLEANING_REQUIRED: VEHICLE_CLEANING_ORG_OVERRIDE_FIELDS,
  VEHICLE_SERVICE_OVERDUE: INSIGHT_HEALTH_ORG_OVERRIDE_FIELDS,
  VEHICLE_INSPECTION_TUV_DUE: INSIGHT_HEALTH_ORG_OVERRIDE_FIELDS,
  VEHICLE_INSPECTION_BOKRAFT_DUE: INSIGHT_HEALTH_ORG_OVERRIDE_FIELDS,
  TIRE_CRITICAL_HEALTH: INSIGHT_HEALTH_ORG_OVERRIDE_FIELDS,
  BRAKE_CRITICAL_HEALTH: INSIGHT_HEALTH_ORG_OVERRIDE_FIELDS,
  BATTERY_CRITICAL_HEALTH: INSIGHT_HEALTH_ORG_OVERRIDE_FIELDS,
  REPAIR_REQUIRED: REPAIR_ORG_OVERRIDE_FIELDS,
};
