import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createReadStream } from 'fs';
import { mkdir, readFile, unlink, writeFile } from 'fs/promises';
import { resolve, sep, dirname, extname, basename } from 'path';
import { randomUUID } from 'crypto';
import { Readable } from 'stream';
import {
  DocumentStoragePort,
  PutDocumentInput,
  PutDocumentResult,
} from './document-storage.interface';

const STORAGE_PROVIDER = 'local';

/**
 * Local-disk implementation of {@link DocumentStoragePort}.
 *
 * Files are written under `documents.localStorageDir` (default
 * `./storage/documents`), which is NOT registered as a static asset directory —
 * generated PDFs and legal documents are never publicly reachable.
 *
 * Object keys are fully generated by this service:
 *   booking-scoped: organizations/{orgId}/bookings/{bookingId}/{documentType}/{yyyy}/{mm}/{uuid}-{safeName}
 *   org-scoped:     organizations/{orgId}/legal/{documentType}/{yyyy}/{mm}/{uuid}-{safeName}
 * The untrusted original filename is sanitised and only contributes a suffix; it
 * is never used for directory construction. Every key passed back in for read /
 * delete is validated to stay inside the base directory (path-traversal guard).
 *
 * --- Future S3-compatible provider (TODO) ---
 * Implement a sibling `S3DocumentStorageService implements DocumentStoragePort`
 * that PUTs/GETs by the same object key, returns `storageProvider: 's3'`, and
 * returns `null` from getInternalPath. Then bind the DOCUMENTS_STORAGE token by
 * `documents.storageProvider`.
 */
@Injectable()
export class LocalDocumentStorageService implements DocumentStoragePort {
  private readonly logger = new Logger(LocalDocumentStorageService.name);
  private readonly baseDir: string;

  constructor(private readonly config: ConfigService) {
    const configured = this.config.get<string>(
      'documents.localStorageDir',
      './storage/documents',
    );
    this.baseDir = resolve(process.cwd(), configured);
  }

  async putObject(input: PutDocumentInput): Promise<PutDocumentResult> {
    const orgSeg = this.safeSegment(input.organizationId);
    const typeSeg = this.safeSegment(input.documentType) || 'document';
    if (!orgSeg) {
      throw new BadRequestException('organizationId is required for storage');
    }

    const now = new Date();
    const yyyy = String(now.getUTCFullYear());
    const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
    const safeName = this.sanitizeFileName(input.originalName);

    const bookingSeg = input.bookingId ? this.safeSegment(input.bookingId) : '';
    const scope = bookingSeg
      ? ['bookings', bookingSeg, typeSeg]
      : ['legal', typeSeg];

    const objectKey = [
      'organizations',
      orgSeg,
      ...scope,
      yyyy,
      mm,
      `${randomUUID()}-${safeName}`,
    ].join('/');

    const absPath = this.resolveKey(objectKey);
    await mkdir(dirname(absPath), { recursive: true });
    await writeFile(absPath, input.buffer);

    return {
      objectKey,
      storageProvider: STORAGE_PROVIDER,
      sizeBytes: input.buffer.length,
      mimeType: input.mimeType,
    };
  }

  async getObject(objectKey: string): Promise<Buffer> {
    const absPath = this.resolveKey(objectKey);
    return readFile(absPath);
  }

  async getObjectStream(objectKey: string): Promise<Readable> {
    const absPath = this.resolveKey(objectKey);
    return createReadStream(absPath);
  }

  async deleteObject(objectKey: string): Promise<void> {
    try {
      const absPath = this.resolveKey(objectKey);
      await unlink(absPath).catch(() => undefined);
    } catch (err) {
      this.logger.debug(`deleteObject(${objectKey}) skipped: ${(err as Error).message}`);
    }
  }

  getInternalPath(objectKey: string): string | null {
    return this.resolveKey(objectKey);
  }

  // ── internals ──────────────────────────────────────────────────────────

  /**
   * Resolves an object key to an absolute path and asserts it stays inside the
   * base directory. Rejects absolute keys, `..` traversal, and NUL bytes.
   */
  private resolveKey(objectKey: string): string {
    if (typeof objectKey !== 'string' || objectKey.length === 0) {
      throw new BadRequestException('Invalid object key');
    }
    if (objectKey.includes('\0') || objectKey.includes('..')) {
      throw new BadRequestException('Invalid object key');
    }
    const normalized = objectKey.replace(/\\/g, '/').replace(/^\/+/, '');
    if (/^[a-zA-Z]:/.test(normalized)) {
      throw new BadRequestException('Invalid object key');
    }
    const abs = resolve(this.baseDir, normalized);
    const baseWithSep = this.baseDir.endsWith(sep) ? this.baseDir : this.baseDir + sep;
    if (abs !== this.baseDir && !abs.startsWith(baseWithSep)) {
      throw new BadRequestException('Invalid object key (path traversal)');
    }
    return abs;
  }

  /** A single path segment derived from a trusted id / known constant. */
  private safeSegment(value: string): string {
    if (!value) return '';
    return basename(String(value)).replace(/[^a-zA-Z0-9_-]/g, '');
  }

  /**
   * Sanitises an untrusted original filename into a safe suffix. Keeps a known
   * extension, strips directories, and collapses unsafe characters.
   */
  private sanitizeFileName(originalName: string): string {
    const base = basename(String(originalName || 'document'));
    const ext = extname(base).toLowerCase().replace(/[^a-z0-9.]/g, '');
    const stem =
      base
        .slice(0, base.length - extname(base).length)
        .replace(/[^a-zA-Z0-9_-]/g, '_')
        .replace(/_+/g, '_')
        .slice(0, 60) || 'document';
    const safeExt = ext && ext.length <= 6 ? ext : '';
    return `${stem}${safeExt}`;
  }
}
