export const BOOKING_ELIGIBILITY_DECISION_RECHECK_WINDOW_MS = 24 * 60 * 60 * 1000;

export const BOOKING_ELIGIBILITY_DECISION_ERROR_CODE = {
  BOOKING_REQUIRED: 'BOOKING_ELIGIBILITY_DECISION_BOOKING_REQUIRED',
  NOT_FOUND: 'BOOKING_ELIGIBILITY_DECISION_NOT_FOUND',
} as const;
