/** Standardized, machine-readable skip reasons for dry-run explainability. */
export const WORKFLOW_MATCHER_SKIP_REASONS = [
  'WRONG_ORGANIZATION',
  'DEFINITION_ARCHIVED',
  'DEFINITION_REMEDIATION_REQUIRED',
  'VERSION_NOT_ACTIVE',
  'VERSION_NOT_PUBLISHED',
  'NOT_ACTIVE_VERSION_POINTER',
  'VERSION_DISABLED',
  'UNSUPPORTED_EVENT_VERSION',
  'ENTITY_TYPE_MISMATCH',
  'SCOPE_NOT_CONFIGURED',
  'SCOPE_EMPTY_BINDINGS',
  'SCOPE_STATION_MISMATCH',
  'SCOPE_VEHICLE_MISMATCH',
  'SCOPE_BOOKING_MISMATCH',
  'SCOPE_CUSTOMER_MISMATCH',
  'VALIDITY_NOT_YET_ACTIVE',
  'VALIDITY_EXPIRED',
  'FEATURE_FLAG_DISABLED',
  'ROLLOUT_SCOPE_MISMATCH',
  'ROLLOUT_PERCENTAGE_EXCLUDED',
  'CAPABILITY_UNAVAILABLE',
  'POLICY_REQUIREMENT_FAILED',
  'EVALUATION_ERROR',
] as const;

export type WorkflowMatcherSkipReason = (typeof WORKFLOW_MATCHER_SKIP_REASONS)[number];

export function isWorkflowMatcherSkipReason(
  value: string,
): value is WorkflowMatcherSkipReason {
  return (WORKFLOW_MATCHER_SKIP_REASONS as readonly string[]).includes(value);
}
