export const BUSINESS_AUDIT_OUTBOX = {
  payloadVersion: 1,
  pollBatchSize: 25,
  maxAttempts: 5,
  backoffMs: 2_000,
  staleProcessingMs: 5 * 60_000,
} as const;

export const BUSINESS_AUDIT_SENSITIVE_KEYS = [
  'password',
  'passwordhash',
  'token',
  'secret',
  'apikey',
  'privatekey',
  'document',
  'extractedjson',
  'factualvalue',
  'dateofbirth',
  'licenseissuedat',
  'licenseexpiry',
  'idfronturl',
  'idbackurl',
  'signaturedataurl',
  'image',
  'payload',
] as const;

export const BusinessAuditAction = {
  RENTAL_RULE_DRAFT_CREATED: 'RENTAL_RULE_DRAFT_CREATED',
  RENTAL_RULE_DRAFT_CHANGED: 'RENTAL_RULE_DRAFT_CHANGED',
  RENTAL_RULE_PUBLISHED: 'RENTAL_RULE_PUBLISHED',
  RENTAL_RULE_DEACTIVATED: 'RENTAL_RULE_DEACTIVATED',
  RENTAL_CATEGORY_ARCHIVED: 'RENTAL_CATEGORY_ARCHIVED',
  RENTAL_CATEGORY_VEHICLES_ASSIGNED: 'RENTAL_CATEGORY_VEHICLES_ASSIGNED',
  RENTAL_VEHICLE_OVERRIDE_CREATED: 'RENTAL_VEHICLE_OVERRIDE_CREATED',
  RENTAL_VEHICLE_OVERRIDE_DELETED: 'RENTAL_VEHICLE_OVERRIDE_DELETED',
  ELIGIBILITY_CHECKED: 'ELIGIBILITY_CHECKED',
  MANUAL_APPROVAL_REQUESTED: 'MANUAL_APPROVAL_REQUESTED',
  MANUAL_APPROVAL_APPROVED: 'MANUAL_APPROVAL_APPROVED',
  MANUAL_APPROVAL_REJECTED: 'MANUAL_APPROVAL_REJECTED',
  MANUAL_APPROVAL_REVOKED: 'MANUAL_APPROVAL_REVOKED',
  MANUAL_APPROVAL_EXPIRED: 'MANUAL_APPROVAL_EXPIRED',
  EVALUATIONS_SENSITIVE_DETAIL_ACCESSED: 'EVALUATIONS_SENSITIVE_DETAIL_ACCESSED',
  EVALUATIONS_FINANCE_EXPORT: 'EVALUATIONS_FINANCE_EXPORT',
  EVALUATIONS_PII_DATA_ACCESSED: 'EVALUATIONS_PII_DATA_ACCESSED',
  EVALUATIONS_RECOMMENDATION_CHANGED: 'EVALUATIONS_RECOMMENDATION_CHANGED',
  EVALUATIONS_ASSIGNEE_CHANGED: 'EVALUATIONS_ASSIGNEE_CHANGED',
  EVALUATIONS_STATUS_CHANGED: 'EVALUATIONS_STATUS_CHANGED',
  EVALUATIONS_KPI_DEFINITION_CHANGED: 'EVALUATIONS_KPI_DEFINITION_CHANGED',
  EVALUATIONS_FORECAST_MODEL_CHANGED: 'EVALUATIONS_FORECAST_MODEL_CHANGED',
  EVALUATIONS_THRESHOLD_CHANGED: 'EVALUATIONS_THRESHOLD_CHANGED',
  EVALUATIONS_MANUAL_RECALCULATION: 'EVALUATIONS_MANUAL_RECALCULATION',
  EVALUATIONS_MODEL_ACTIVATED: 'EVALUATIONS_MODEL_ACTIVATED',
  EVALUATIONS_MODEL_DEACTIVATED: 'EVALUATIONS_MODEL_DEACTIVATED',
  EVALUATIONS_DATA_QUALITY_ACTION: 'EVALUATIONS_DATA_QUALITY_ACTION',
  EVALUATIONS_ACCESS_DENIED: 'EVALUATIONS_ACCESS_DENIED',
} as const;

export type BusinessAuditActionCode =
  (typeof BusinessAuditAction)[keyof typeof BusinessAuditAction];

export const BUSINESS_AUDIT_ENTITY_TYPE = {
  RENTAL_RULE_REVISION: 'RENTAL_RULE_REVISION',
  RENTAL_CATEGORY: 'RENTAL_CATEGORY',
  VEHICLE: 'VEHICLE',
  BOOKING: 'BOOKING',
  BOOKING_ELIGIBILITY_APPROVAL: 'BOOKING_ELIGIBILITY_APPROVAL',
  EVALUATIONS_EXPORT: 'EVALUATIONS_EXPORT',
  EVALUATIONS_MISUSE_CASE: 'EVALUATIONS_MISUSE_CASE',
  EVALUATIONS_INSIGHT_POLICY: 'EVALUATIONS_INSIGHT_POLICY',
  EVALUATIONS_MODEL_REGISTRY: 'EVALUATIONS_MODEL_REGISTRY',
  EVALUATIONS_FORECAST_RUN: 'EVALUATIONS_FORECAST_RUN',
  EVALUATIONS_CUSTOMER_LABELS: 'EVALUATIONS_CUSTOMER_LABELS',
  EVALUATIONS_ADMIN_DIAGNOSTICS: 'EVALUATIONS_ADMIN_DIAGNOSTICS',
} as const;

export type BusinessAuditEntityType =
  (typeof BUSINESS_AUDIT_ENTITY_TYPE)[keyof typeof BUSINESS_AUDIT_ENTITY_TYPE];
