export const BUSINESS_AUDIT_OUTBOX = {
  payloadVersion: 1,
  pollBatchSize: 25,
  maxAttempts: 5,
  backoffMs: 2_000,
  staleProcessingMs: 5 * 60_000,
} as const;

export const BUSINESS_AUDIT_SENSITIVE_KEYS = [
  'password',
  'passwordhash',
  'token',
  'secret',
  'apikey',
  'privatekey',
  'document',
  'extractedjson',
  'factualvalue',
  'dateofbirth',
  'licenseissuedat',
  'licenseexpiry',
  'idfronturl',
  'idbackurl',
  'signaturedataurl',
  'imagedata',
  'image',
  'payload',
] as const;

export const BusinessAuditAction = {
  RENTAL_RULE_DRAFT_CREATED: 'RENTAL_RULE_DRAFT_CREATED',
  RENTAL_RULE_DRAFT_CHANGED: 'RENTAL_RULE_DRAFT_CHANGED',
  RENTAL_RULE_PUBLISHED: 'RENTAL_RULE_PUBLISHED',
  RENTAL_RULE_DEACTIVATED: 'RENTAL_RULE_DEACTIVATED',
  RENTAL_CATEGORY_ARCHIVED: 'RENTAL_CATEGORY_ARCHIVED',
  RENTAL_CATEGORY_VEHICLES_ASSIGNED: 'RENTAL_CATEGORY_VEHICLES_ASSIGNED',
  RENTAL_VEHICLE_OVERRIDE_CREATED: 'RENTAL_VEHICLE_OVERRIDE_CREATED',
  RENTAL_VEHICLE_OVERRIDE_DELETED: 'RENTAL_VEHICLE_OVERRIDE_DELETED',
  ELIGIBILITY_CHECKED: 'ELIGIBILITY_CHECKED',
  MANUAL_APPROVAL_REQUESTED: 'MANUAL_APPROVAL_REQUESTED',
  MANUAL_APPROVAL_APPROVED: 'MANUAL_APPROVAL_APPROVED',
  MANUAL_APPROVAL_REJECTED: 'MANUAL_APPROVAL_REJECTED',
  MANUAL_APPROVAL_REVOKED: 'MANUAL_APPROVAL_REVOKED',
  MANUAL_APPROVAL_EXPIRED: 'MANUAL_APPROVAL_EXPIRED',
  // Operator App — sensitive field actions (Prompt 35)
  OPERATOR_CUSTOMER_SENSITIVE_VIEW: 'OPERATOR_CUSTOMER_SENSITIVE_VIEW',
  OPERATOR_DOCUMENT_FULL_VIEW: 'OPERATOR_DOCUMENT_FULL_VIEW',
  OPERATOR_DOCUMENT_VERIFICATION: 'OPERATOR_DOCUMENT_VERIFICATION',
  OPERATOR_HANDOVER_STARTED: 'OPERATOR_HANDOVER_STARTED',
  OPERATOR_HANDOVER_DRAFT_RESUMED: 'OPERATOR_HANDOVER_DRAFT_RESUMED',
  OPERATOR_HANDOVER_PICKUP_COMPLETED: 'OPERATOR_HANDOVER_PICKUP_COMPLETED',
  OPERATOR_HANDOVER_RETURN_COMPLETED: 'OPERATOR_HANDOVER_RETURN_COMPLETED',
  OPERATOR_HANDOVER_OVERRIDE: 'OPERATOR_HANDOVER_OVERRIDE',
  OPERATOR_HANDOVER_PROTOCOL_CORRECTED: 'OPERATOR_HANDOVER_PROTOCOL_CORRECTED',
  OPERATOR_SIGNATURE_CAPTURED: 'OPERATOR_SIGNATURE_CAPTURED',
  OPERATOR_DAMAGE_CREATED: 'OPERATOR_DAMAGE_CREATED',
  OPERATOR_DAMAGE_UPDATED: 'OPERATOR_DAMAGE_UPDATED',
  OPERATOR_DAMAGE_VERIFIED: 'OPERATOR_DAMAGE_VERIFIED',
  OPERATOR_TECHNICAL_OBSERVATION_CREATED: 'OPERATOR_TECHNICAL_OBSERVATION_CREATED',
  OPERATOR_TIRE_MEASUREMENT_RECORDED: 'OPERATOR_TIRE_MEASUREMENT_RECORDED',
  OPERATOR_TASK_COMPLETED: 'OPERATOR_TASK_COMPLETED',
  OPERATOR_TASK_COMPLETION_OVERRIDE: 'OPERATOR_TASK_COMPLETION_OVERRIDE',
  OPERATOR_BOOKING_CREATED: 'OPERATOR_BOOKING_CREATED',
  OPERATOR_BOOKING_UPDATED: 'OPERATOR_BOOKING_UPDATED',
  OPERATOR_BOOKING_CANCELLED: 'OPERATOR_BOOKING_CANCELLED',
  OPERATOR_UPLOAD_DELETED: 'OPERATOR_UPLOAD_DELETED',
  OPERATOR_PERMISSION_DENIED: 'OPERATOR_PERMISSION_DENIED',
} as const;

export type BusinessAuditActionCode =
  (typeof BusinessAuditAction)[keyof typeof BusinessAuditAction];

export const BUSINESS_AUDIT_ENTITY_TYPE = {
  RENTAL_RULE_REVISION: 'RENTAL_RULE_REVISION',
  RENTAL_CATEGORY: 'RENTAL_CATEGORY',
  VEHICLE: 'VEHICLE',
  BOOKING: 'BOOKING',
  BOOKING_ELIGIBILITY_APPROVAL: 'BOOKING_ELIGIBILITY_APPROVAL',
  HANDOVER_PROTOCOL: 'HANDOVER_PROTOCOL',
  DAMAGE: 'DAMAGE',
  DOCUMENT_EXTRACTION: 'DOCUMENT_EXTRACTION',
  TECHNICAL_OBSERVATION: 'TECHNICAL_OBSERVATION',
  TIRE_MEASUREMENT: 'TIRE_MEASUREMENT',
  TASK: 'TASK',
  CUSTOMER: 'CUSTOMER',
  ORGANIZATION: 'ORGANIZATION',
} as const;

export type BusinessAuditEntityType =
  (typeof BUSINESS_AUDIT_ENTITY_TYPE)[keyof typeof BUSINESS_AUDIT_ENTITY_TYPE];
