/**
 * Canonical legal-document notification event types (Prompt 29/32).
 * Producers must derive signals only from resolver, bundle, integrity, and workflow states.
 */

export const LEGAL_NOTIFICATION_EVENT = {
  // User-facing
  REQUIRED_DOCUMENT_MISSING: 'LEGAL_REQUIRED_DOCUMENT_MISSING',
  REQUIRED_LANGUAGE_MISSING: 'LEGAL_REQUIRED_LANGUAGE_MISSING',
  REQUIRED_JURISDICTION_MISSING: 'LEGAL_REQUIRED_JURISDICTION_MISSING',
  APPROVAL_PENDING: 'LEGAL_APPROVAL_PENDING',
  ACTIVATION_SCHEDULED: 'LEGAL_ACTIVATION_SCHEDULED',
  DOCUMENT_EXPIRING_SOON: 'LEGAL_DOCUMENT_EXPIRING_SOON',
  BUNDLE_INCOMPLETE: 'LEGAL_BUNDLE_INCOMPLETE',
  DOCUMENT_DELIVERY_FAILED: 'LEGAL_DOCUMENT_DELIVERY_FAILED',
  SCAN_FAILED: 'LEGAL_SCAN_FAILED',
  INTEGRITY_CHECK_FAILED: 'LEGAL_INTEGRITY_CHECK_FAILED',
  PICKUP_BLOCKED_MISSING_PROOF: 'LEGAL_PICKUP_BLOCKED_MISSING_PROOF',
  // Technical (admin / internal surfaces)
  TECH_MULTIPLE_ACTIVE_VERSIONS: 'LEGAL_TECH_MULTIPLE_ACTIVE_VERSIONS',
  TECH_STORAGE_OBJECT_MISSING: 'LEGAL_TECH_STORAGE_OBJECT_MISSING',
  TECH_HASH_MISMATCH: 'LEGAL_TECH_HASH_MISMATCH',
  TECH_QUEUE_JOB_DEAD: 'LEGAL_TECH_QUEUE_JOB_DEAD',
  TECH_MALWARE_SCANNER_UNAVAILABLE: 'LEGAL_TECH_MALWARE_SCANNER_UNAVAILABLE',
  TECH_OBJECT_STORAGE_UNAVAILABLE: 'LEGAL_TECH_OBJECT_STORAGE_UNAVAILABLE',
  TECH_RECONCILIATION_FAILED: 'LEGAL_TECH_RECONCILIATION_FAILED',
  TECH_UNMAPPED_DOCUMENT_TYPE: 'LEGAL_TECH_UNMAPPED_DOCUMENT_TYPE',
  TECH_RESOLVER_CONFLICT_UNRESOLVABLE: 'LEGAL_TECH_RESOLVER_CONFLICT_UNRESOLVABLE',
} as const;

export type LegalNotificationEventType =
  (typeof LEGAL_NOTIFICATION_EVENT)[keyof typeof LEGAL_NOTIFICATION_EVENT];

/** @deprecated Use LEGAL_NOTIFICATION_EVENT.REQUIRED_DOCUMENT_MISSING — kept for migration alias. */
export const LEGACY_REQUIRED_DOCUMENT_MISSING = 'REQUIRED_DOCUMENT_MISSING';

export const LEGAL_NOTIFICATION_EXPECTED_LANGUAGE = 'de';
export const LEGAL_NOTIFICATION_EXPECTED_JURISDICTION = 'DE';
export const LEGAL_NOTIFICATION_EXPIRY_WARNING_DAYS = 30;

export const LEGAL_SCAN_BLOCKING_STATUSES = new Set(['FAILED', 'INFECTED', 'REJECTED']);
export const LEGAL_INTEGRITY_BLOCKING_STATUSES = new Set([
  'CHECKSUM_MISMATCH',
  'MISSING_OBJECT',
  'STORAGE_ERROR',
  'INTEGRITY_FAILED',
]);

/** Org-level category keys aligned with admin UI grouping. */
export const LEGAL_DOCUMENT_CATEGORY_KEYS = [
  'TERMS_AND_CONDITIONS',
  'CONSUMER_INFORMATION',
  'PRIVACY_POLICY',
] as const;

export type LegalDocumentCategoryKey = (typeof LEGAL_DOCUMENT_CATEGORY_KEYS)[number];

export const LEGAL_NOTIFICATION_SCOPE = {
  ORG_READINESS: 'org-readiness',
  BOOKING_BUNDLE: 'booking-bundle',
  BOOKING_PICKUP: 'booking-pickup',
  DOCUMENT_INTEGRITY: 'document-integrity',
  ORG_TECHNICAL: 'org-technical',
} as const;

export type LegalNotificationScope =
  (typeof LEGAL_NOTIFICATION_SCOPE)[keyof typeof LEGAL_NOTIFICATION_SCOPE];
