export const WORKFLOW_RUNTIME_STATUS_ERROR_CODES = {
  NOT_FOUND: 'WORKFLOW_RUN_NOT_FOUND',
  ACTION_RUN_NOT_FOUND: 'WORKFLOW_ACTION_RUN_NOT_FOUND',
  FOREIGN_TENANT: 'WORKFLOW_RUNTIME_FOREIGN_TENANT',
  INVALID_TRANSITION: 'WORKFLOW_RUNTIME_INVALID_STATUS_TRANSITION',
  NOOP_TRANSITION: 'WORKFLOW_RUNTIME_NOOP_STATUS_TRANSITION',
  TERMINAL_IMMUTABLE: 'WORKFLOW_RUNTIME_TERMINAL_STATUS_IMMUTABLE',
  LOCK_CONFLICT: 'WORKFLOW_RUNTIME_LOCK_CONFLICT',
  FIELD_RULE_VIOLATION: 'WORKFLOW_RUNTIME_STATUS_FIELD_RULE_VIOLATION',
  DERIVATION_CONFLICT: 'WORKFLOW_RUNTIME_RUN_STATUS_DERIVATION_CONFLICT',
  TENANT_VIOLATION: 'WORKFLOW_RUNTIME_TENANT_VIOLATION',
  MAX_RUN_DURATION_EXCEEDED: 'WORKFLOW_RUNTIME_MAX_RUN_DURATION_EXCEEDED',
  CLAIM_CONFLICT: 'WORKFLOW_RUNTIME_CLAIM_CONFLICT',
  RUN_CANCELLED: 'WORKFLOW_RUN_CANCELLED',
} as const;

export type WorkflowRuntimeStatusErrorCode =
  (typeof WORKFLOW_RUNTIME_STATUS_ERROR_CODES)[keyof typeof WORKFLOW_RUNTIME_STATUS_ERROR_CODES];
