export type VehicleOnboardingErrorCode =
  | 'CASE_NOT_FOUND'
  | 'ORGANIZATION_MISMATCH'
  | 'INVALID_CASE_TRANSITION'
  | 'READINESS_NOT_SEALED'
  | 'READINESS_SEAL_STALE'
  | 'PRODUCT_ENTITLEMENT_NOT_ACTIVE'
  | 'READINESS_PROFILE_UNSUPPORTED'
  | 'ACTIVATION_PRECONDITION_FAILED'
  | 'SCHEMA_REQUIRED_FIELDS_MISSING'
  | 'UNSUPPORTED_CONTRACT_VERSION'
  | 'UNSUPPORTED_FUEL_TYPE'
  | 'VIN_CONFLICT_REQUIRES_IDENTITY_REVIEW'
  | 'IDENTITY_REVIEW_REQUIRED'
  | 'SOURCE_REF_CONFLICT'
  | 'SOURCE_NOT_AVAILABLE'
  | 'TERMINAL_CASE_IDEMPOTENCY'
  | 'COMPOSITE_IDENTITY_CONFLICT'
  | 'PROVIDER_LINK_CONFLICT'
  | 'HM_ALREADY_REGISTERED'
  | 'SOURCE_SET_REQUIRES_REVIEW'
  | 'PRIMARY_SOURCE_CONFLICT'
  | 'IDEMPOTENCY_KEY_REUSED_FOR_DIFFERENT_REQUEST'
  | 'OUTBOX_IDEMPOTENCY_CONFLICT'
  | 'TECHNICAL_BASELINE_MATERIALIZATION_FAILED'
  | 'TECHNICAL_BASELINE_EVIDENCE_SCOPE_MISMATCH'
  | 'ONBOARDING_CONCURRENCY_CONFLICT'
  | 'INVALID_CAPTURE_PAYLOAD'
  | 'STATION_SCOPE_MISMATCH'
  | 'SOURCE_ALREADY_CLAIMED'
  | 'SOURCE_ALREADY_REGISTERED'
  | 'SOURCE_CLAIM_INTEGRITY_CONFLICT';

export class VehicleOnboardingError extends Error {
  constructor(
    readonly code: VehicleOnboardingErrorCode,
    message: string,
    readonly details?: Record<string, unknown>,
  ) {
    super(message);
    this.name = 'VehicleOnboardingError';
  }
}
