/**
 * Central bundle completeness status model (Prompt 16/32).
 * Replaces scattered PENDING/PARTIAL/COMPLETE derivations for booking document packages.
 */
export const BUNDLE_COMPLETENESS_STATUS = {
  COMPLETE: 'COMPLETE',
  INCOMPLETE: 'INCOMPLETE',
  BLOCKED: 'BLOCKED',
  GENERATING: 'GENERATING',
  DELIVERY_PENDING: 'DELIVERY_PENDING',
  ACKNOWLEDGMENT_PENDING: 'ACKNOWLEDGMENT_PENDING',
  INTEGRITY_FAILED: 'INTEGRITY_FAILED',
} as const;

export type BundleCompletenessStatus =
  (typeof BUNDLE_COMPLETENESS_STATUS)[keyof typeof BUNDLE_COMPLETENESS_STATUS];

export const BUNDLE_COMPLETENESS_REASON_CODE = {
  DOCUMENT_MISSING: 'DOCUMENT_MISSING',
  GENERATION_FAILED: 'GENERATION_FAILED',
  GENERATION_IN_PROGRESS: 'GENERATION_IN_PROGRESS',
  ORG_CONFIGURATION_GAP: 'ORG_CONFIGURATION_GAP',
  RESOLVER_CONFLICT: 'RESOLVER_CONFLICT',
  INTEGRITY_UNAVAILABLE: 'INTEGRITY_UNAVAILABLE',
  INTEGRITY_CHECKSUM_MISMATCH: 'INTEGRITY_CHECKSUM_MISMATCH',
  INTEGRITY_MISSING_OBJECT: 'INTEGRITY_MISSING_OBJECT',
  INTEGRITY_STORAGE_ERROR: 'INTEGRITY_STORAGE_ERROR',
  SCAN_NOT_PASSED: 'SCAN_NOT_PASSED',
  DELIVERY_PROOF_MISSING: 'DELIVERY_PROOF_MISSING',
  ACKNOWLEDGMENT_MISSING: 'ACKNOWLEDGMENT_MISSING',
  SCOPE_NOT_APPLICABLE: 'SCOPE_NOT_APPLICABLE',
} as const;

export type BundleCompletenessReasonCode =
  (typeof BUNDLE_COMPLETENESS_REASON_CODE)[keyof typeof BUNDLE_COMPLETENESS_REASON_CODE];

/** Document types that require email delivery proof once generated (CONFIRMED+). */
export const DELIVERY_PROOF_DOCUMENT_TYPES = ['BOOKING_INVOICE'] as const;

/** Status priority — higher index wins when multiple conditions apply. */
export const BUNDLE_COMPLETENESS_STATUS_PRIORITY: readonly BundleCompletenessStatus[] = [
  BUNDLE_COMPLETENESS_STATUS.COMPLETE,
  BUNDLE_COMPLETENESS_STATUS.INCOMPLETE,
  BUNDLE_COMPLETENESS_STATUS.DELIVERY_PENDING,
  BUNDLE_COMPLETENESS_STATUS.ACKNOWLEDGMENT_PENDING,
  BUNDLE_COMPLETENESS_STATUS.GENERATING,
  BUNDLE_COMPLETENESS_STATUS.BLOCKED,
  BUNDLE_COMPLETENESS_STATUS.INTEGRITY_FAILED,
] as const;

export function pickHigherPriorityCompletenessStatus(
  current: BundleCompletenessStatus,
  candidate: BundleCompletenessStatus,
): BundleCompletenessStatus {
  const currentIdx = BUNDLE_COMPLETENESS_STATUS_PRIORITY.indexOf(current);
  const candidateIdx = BUNDLE_COMPLETENESS_STATUS_PRIORITY.indexOf(candidate);
  return candidateIdx > currentIdx ? candidate : current;
}
