export const LEGAL_DOCUMENT_ERROR_CODES = {
  ACTIVE_CONFLICT: 'LEGAL_DOCUMENT_ACTIVE_CONFLICT',
  NOT_ACTIVATABLE: 'LEGAL_DOCUMENT_NOT_ACTIVATABLE',
  INVALID_STATUS_TRANSITION: 'LEGAL_DOCUMENT_INVALID_STATUS_TRANSITION',
  SCOPE_CONFLICT: 'LEGAL_DOCUMENT_SCOPE_CONFLICT',
  VALIDATION_FAILED: 'LEGAL_DOCUMENT_VALIDATION_FAILED',
  NOT_FOUND: 'LEGAL_DOCUMENT_NOT_FOUND',
  SCOPE_LOCKED: 'LEGAL_DOCUMENT_SCOPE_LOCKED',
  MISSING_REQUIRED_FIELD: 'LEGAL_DOCUMENT_MISSING_REQUIRED_FIELD',
  INVALID_DOCUMENT_TYPE: 'LEGAL_DOCUMENT_INVALID_DOCUMENT_TYPE',
  INVALID_FILE_TYPE: 'LEGAL_DOCUMENT_INVALID_FILE_TYPE',
} as const;

export type LegalDocumentErrorCode =
  (typeof LEGAL_DOCUMENT_ERROR_CODES)[keyof typeof LEGAL_DOCUMENT_ERROR_CODES];

export interface LegalDocumentConflictBody {
  message: string;
  code: typeof LEGAL_DOCUMENT_ERROR_CODES.ACTIVE_CONFLICT;
  organizationId: string;
  documentType: string;
  language: string;
}

export const LEGAL_DOCUMENT_SINGLE_ACTIVE_INDEX = 'organization_legal_documents_single_active_key';
