import {
  BadRequestException,
  ConflictException,
  Inject,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { createHash } from 'crypto';
import { OrganizationLegalDocument, Prisma } from '@prisma/client';
import { PrismaService } from '@shared/database/prisma.service';
import {
  DOCUMENTS_STORAGE,
  DocumentStoragePort,
} from './storage/document-storage.interface';
import {
  DOCUMENT_TITLE_DE,
  LEGAL_DOCUMENT_TYPES,
  LEGAL_STATUS,
  isLegalDocumentType,
  type LegalStatus,
} from './documents.constants';
import { DocumentDownload } from './generated-documents.service';
import { isLegalPdfUpload, normalizeLegalPdfMimeType } from './legal-documents.util';
import {
  LEGAL_DOCUMENT_ERROR_CODES,
  type LegalDocumentConflictBody,
} from './legal-documents.errors';
import { isLegalDocumentSingleActiveViolation } from './legal-documents-prisma.util';
import {
  LEGAL_ACTIVATABLE_STATUSES,
  assertLegalStatusTransition,
  isLegalStatusTransitionAllowed,
} from './legal-document-lifecycle.transitions';

export interface UploadLegalDocumentInput {
  organizationId: string;
  documentType: string;
  versionLabel: string;
  title?: string | null;
  language?: string | null;
  fileName: string;
  buffer: Buffer;
  mimeType: string;
  uploadedByUserId?: string | null;
  legalOwnerName?: string | null;
  changeSummary?: string | null;
}

export interface LegalDocumentStatusChangeInput {
  userId?: string | null;
  statusReason?: string | null;
  changeSummary?: string | null;
}

export interface ScheduleLegalDocumentInput extends LegalDocumentStatusChangeInput {
  validFrom: Date;
}

export interface LegalDocumentDto {
  id: string;
  documentType: string;
  title: string;
  versionLabel: string;
  language: string;
  status: string;
  fileName: string;
  sizeBytes: number | null;
  /** @deprecated Use activatedAt — kept for API backward compatibility. */
  activeFrom: string | null;
  activatedAt: string | null;
  validFrom: string | null;
  validUntil: string | null;
  legalOwnerName: string | null;
  changeSummary: string | null;
  statusReason: string | null;
  createdAt: string;
  updatedAt: string;
}

type Tx = Prisma.TransactionClient;

/**
 * AGB + Widerrufsbelehrung are NOT generated by SynqDrive — the rental company
 * uploads and versions them here. Exactly one ACTIVE document is allowed per
 * (organization, documentType, language); activating a new version supersedes the
 * previously active one. The active versions are snapshotted onto the booking
 * bundle when documents are generated.
 */
@Injectable()
export class LegalDocumentsService {
  private readonly logger = new Logger(LegalDocumentsService.name);

  constructor(
    private readonly prisma: PrismaService,
    @Inject(DOCUMENTS_STORAGE) private readonly storage: DocumentStoragePort,
  ) {}

  async upload(input: UploadLegalDocumentInput): Promise<OrganizationLegalDocument> {
    if (!isLegalDocumentType(input.documentType)) {
      throw new BadRequestException(
        `documentType must be one of: ${LEGAL_DOCUMENT_TYPES.join(', ')}`,
      );
    }
    if (!isLegalPdfUpload({ mimetype: input.mimeType, originalname: input.fileName })) {
      throw new BadRequestException('Legal documents must be PDF files');
    }
    const versionLabel = (input.versionLabel || '').trim();
    if (!versionLabel) {
      throw new BadRequestException('versionLabel is required');
    }

    const language = (input.language || 'de').toLowerCase();
    const mimeType = normalizeLegalPdfMimeType(input.mimeType, input.fileName);
    const stored = await this.storage.putObject({
      organizationId: input.organizationId,
      bookingId: null,
      documentType: input.documentType,
      originalName: input.fileName,
      buffer: input.buffer,
      mimeType,
    });
    const checksum = createHash('sha256').update(input.buffer).digest('hex');

    return this.prisma.organizationLegalDocument.create({
      data: {
        organizationId: input.organizationId,
        documentType: input.documentType,
        title: input.title?.trim() || DOCUMENT_TITLE_DE[input.documentType] || input.documentType,
        versionLabel,
        language,
        status: LEGAL_STATUS.DRAFT,
        fileName: input.fileName,
        mimeType,
        storageProvider: stored.storageProvider,
        objectKey: stored.objectKey,
        checksum,
        sizeBytes: stored.sizeBytes,
        uploadedByUserId: input.uploadedByUserId ?? null,
        legalOwnerName: input.legalOwnerName?.trim() || null,
        changeSummary: input.changeSummary?.trim() || null,
      },
    });
  }

  async list(orgId: string): Promise<OrganizationLegalDocument[]> {
    return this.prisma.organizationLegalDocument.findMany({
      where: { organizationId: orgId },
      orderBy: [{ documentType: 'asc' }, { createdAt: 'desc' }],
    });
  }

  async getById(orgId: string, id: string): Promise<OrganizationLegalDocument> {
    const doc = await this.prisma.organizationLegalDocument.findFirst({
      where: { id, organizationId: orgId },
    });
    if (!doc) throw new NotFoundException('Legal document not found');
    return doc;
  }

  async submitForReview(
    orgId: string,
    id: string,
    input: LegalDocumentStatusChangeInput = {},
  ): Promise<OrganizationLegalDocument> {
    return this.transitionStatus(orgId, id, LEGAL_STATUS.IN_REVIEW, (now) => ({
      submittedForReviewAt: now,
      submittedForReviewByUserId: input.userId ?? null,
      changeSummary: input.changeSummary?.trim() ?? undefined,
    }));
  }

  async approve(
    orgId: string,
    id: string,
    input: LegalDocumentStatusChangeInput = {},
  ): Promise<OrganizationLegalDocument> {
    return this.transitionStatus(orgId, id, LEGAL_STATUS.APPROVED, (now) => ({
      approvedAt: now,
      approvedByUserId: input.userId ?? null,
      changeSummary: input.changeSummary?.trim() ?? undefined,
    }));
  }

  async schedule(
    orgId: string,
    id: string,
    input: ScheduleLegalDocumentInput,
  ): Promise<OrganizationLegalDocument> {
    if (!(input.validFrom instanceof Date) || Number.isNaN(input.validFrom.getTime())) {
      throw new BadRequestException('validFrom must be a valid date');
    }
    return this.transitionStatus(orgId, id, LEGAL_STATUS.SCHEDULED, () => ({
      validFrom: input.validFrom,
      changeSummary: input.changeSummary?.trim() ?? undefined,
    }));
  }

  /** Activates an approved or scheduled version and supersedes any other ACTIVE version. */
  async activate(
    orgId: string,
    id: string,
    input: LegalDocumentStatusChangeInput = {},
  ): Promise<OrganizationLegalDocument> {
    const doc = await this.getById(orgId, id);

    if (
      doc.status !== LEGAL_STATUS.ACTIVE &&
      !LEGAL_ACTIVATABLE_STATUSES.has(doc.status as LegalStatus)
    ) {
      throw new BadRequestException({
        message: `Legal document must be APPROVED or SCHEDULED before activation (current: ${doc.status})`,
        code: LEGAL_DOCUMENT_ERROR_CODES.NOT_ACTIVATABLE,
      });
    }

    try {
      return await this.prisma.$transaction(async (tx) => {
        const current = await tx.organizationLegalDocument.findFirst({
          where: { id: doc.id, organizationId: orgId },
        });
        if (!current) throw new NotFoundException('Legal document not found');

        const otherActiveCount = await tx.organizationLegalDocument.count({
          where: {
            organizationId: orgId,
            documentType: current.documentType,
            language: current.language,
            status: LEGAL_STATUS.ACTIVE,
            id: { not: current.id },
          },
        });

        if (current.status === LEGAL_STATUS.ACTIVE && otherActiveCount === 0) {
          return current;
        }

        if (
          current.status !== LEGAL_STATUS.ACTIVE &&
          !LEGAL_ACTIVATABLE_STATUSES.has(current.status as LegalStatus)
        ) {
          throw new BadRequestException({
            message: `Legal document must be APPROVED or SCHEDULED before activation (current: ${current.status})`,
            code: LEGAL_DOCUMENT_ERROR_CODES.NOT_ACTIVATABLE,
          });
        }

        if (otherActiveCount > 0) {
          await this.supersedeActivePeers(tx, orgId, current);
        }

        if (current.status === LEGAL_STATUS.ACTIVE) {
          return current;
        }

        const now = new Date();
        const activationTime =
          current.status === LEGAL_STATUS.SCHEDULED && current.validFrom && current.validFrom > now
            ? current.validFrom
            : now;

        return this.applyStatusTransition(tx, current, LEGAL_STATUS.ACTIVE, {
          activatedAt: activationTime,
          activatedByUserId: input.userId ?? null,
          validFrom: current.validFrom ?? activationTime,
        });
      });
    } catch (err) {
      throw this.rethrowActivationError(err, orgId, doc);
    }
  }

  async revoke(
    orgId: string,
    id: string,
    input: LegalDocumentStatusChangeInput = {},
  ): Promise<OrganizationLegalDocument> {
    const reason = input.statusReason?.trim();
    if (!reason) {
      throw new BadRequestException('statusReason is required when revoking a legal document');
    }
    return this.transitionStatus(orgId, id, LEGAL_STATUS.REVOKED, (now) => ({
      revokedAt: now,
      revokedByUserId: input.userId ?? null,
      statusReason: reason,
    }));
  }

  async archive(
    orgId: string,
    id: string,
    input: LegalDocumentStatusChangeInput = {},
  ): Promise<OrganizationLegalDocument> {
    return this.transitionStatus(orgId, id, LEGAL_STATUS.ARCHIVED, () => ({
      statusReason: input.statusReason?.trim() ?? undefined,
    }));
  }

  /** Returns resolvable active legal documents per type (excludes expired / not-yet-valid). */
  async getActiveByType(
    orgId: string,
    language = 'de',
  ): Promise<Record<string, OrganizationLegalDocument | undefined>> {
    const now = new Date();
    const active = await this.prisma.organizationLegalDocument.findMany({
      where: {
        organizationId: orgId,
        language,
        status: LEGAL_STATUS.ACTIVE,
        AND: [
          { OR: [{ validFrom: null }, { validFrom: { lte: now } }] },
          { OR: [{ validUntil: null }, { validUntil: { gt: now } }] },
        ],
      },
      orderBy: { activatedAt: 'desc' },
    });
    const map: Record<string, OrganizationLegalDocument | undefined> = {};
    for (const doc of active) {
      if (!map[doc.documentType]) map[doc.documentType] = doc;
    }
    return map;
  }

  async getDownload(orgId: string, id: string): Promise<DocumentDownload> {
    const doc = await this.getById(orgId, id);
    const stream = await this.storage.getObjectStream(doc.objectKey);
    return { stream, fileName: doc.fileName, mimeType: doc.mimeType, sizeBytes: doc.sizeBytes };
  }

  toDto(doc: OrganizationLegalDocument): LegalDocumentDto {
    const activatedAt = doc.activatedAt ? doc.activatedAt.toISOString() : null;
    return {
      id: doc.id,
      documentType: doc.documentType,
      title: doc.title,
      versionLabel: doc.versionLabel,
      language: doc.language,
      status: doc.status,
      fileName: doc.fileName,
      sizeBytes: doc.sizeBytes,
      activeFrom: activatedAt,
      activatedAt,
      validFrom: doc.validFrom ? doc.validFrom.toISOString() : null,
      validUntil: doc.validUntil ? doc.validUntil.toISOString() : null,
      legalOwnerName: doc.legalOwnerName,
      changeSummary: doc.changeSummary,
      statusReason: doc.statusReason,
      createdAt: doc.createdAt.toISOString(),
      updatedAt: doc.updatedAt.toISOString(),
    };
  }

  private async transitionStatus(
    orgId: string,
    id: string,
    toStatus: string,
    patch: (now: Date) => Prisma.OrganizationLegalDocumentUpdateInput,
  ): Promise<OrganizationLegalDocument> {
    const doc = await this.getById(orgId, id);
    if (!isLegalStatusTransitionAllowed(doc.status, toStatus)) {
      throw new BadRequestException({
        message: `Illegal legal document status transition: ${doc.status} → ${toStatus}`,
        code: LEGAL_DOCUMENT_ERROR_CODES.INVALID_STATUS_TRANSITION,
        fromStatus: doc.status,
        toStatus,
      });
    }

    return this.prisma.$transaction(async (tx) => {
      const current = await tx.organizationLegalDocument.findFirst({
        where: { id: doc.id, organizationId: orgId },
      });
      if (!current) throw new NotFoundException('Legal document not found');
      return this.applyStatusTransition(tx, current, toStatus, patch(new Date()));
    });
  }

  private async applyStatusTransition(
    tx: Tx,
    current: OrganizationLegalDocument,
    toStatus: string,
    data: Prisma.OrganizationLegalDocumentUpdateInput,
  ): Promise<OrganizationLegalDocument> {
    assertLegalStatusTransition(current.status, toStatus);
    return tx.organizationLegalDocument.update({
      where: { id: current.id },
      data: { status: toStatus, ...data },
    });
  }

  private async supersedeActivePeers(
    tx: Tx,
    orgId: string,
    current: OrganizationLegalDocument,
  ): Promise<void> {
    const peers = await tx.organizationLegalDocument.findMany({
      where: {
        organizationId: orgId,
        documentType: current.documentType,
        language: current.language,
        status: LEGAL_STATUS.ACTIVE,
        id: { not: current.id },
      },
    });
    const now = new Date();
    for (const peer of peers) {
      await this.applyStatusTransition(tx, peer, LEGAL_STATUS.SUPERSEDED, {
        validUntil: peer.validUntil ?? now,
        statusReason: peer.statusReason ?? 'Superseded by a newer active legal document version',
      });
    }
  }

  private rethrowActivationError(
    err: unknown,
    orgId: string,
    doc: OrganizationLegalDocument,
  ): never {
    if (
      err instanceof NotFoundException ||
      err instanceof BadRequestException ||
      err instanceof ConflictException
    ) {
      throw err;
    }
    if (isLegalDocumentSingleActiveViolation(err)) {
      const body: LegalDocumentConflictBody = {
        message:
          'Another legal document version is already active for this organization, document type, and language',
        code: LEGAL_DOCUMENT_ERROR_CODES.ACTIVE_CONFLICT,
        organizationId: orgId,
        documentType: doc.documentType,
        language: doc.language,
      };
      throw new ConflictException(body);
    }
    throw err;
  }
}
