import {
  BadRequestException,
  Inject,
  Injectable,
  Logger,
  NotFoundException,
} from '@nestjs/common';
import { createHash } from 'crypto';
import { OrganizationLegalDocument } from '@prisma/client';
import { PrismaService } from '@shared/database/prisma.service';
import {
  DOCUMENTS_STORAGE,
  DocumentStoragePort,
} from './storage/document-storage.interface';
import {
  DOCUMENT_TITLE_DE,
  LEGAL_DOCUMENT_TYPES,
  LEGAL_STATUS,
  isLegalDocumentType,
} from './documents.constants';
import { DocumentDownload } from './generated-documents.service';
import { isLegalPdfUpload, normalizeLegalPdfMimeType } from './legal-documents.util';

export interface UploadLegalDocumentInput {
  organizationId: string;
  documentType: string;
  versionLabel: string;
  title?: string | null;
  language?: string | null;
  fileName: string;
  buffer: Buffer;
  mimeType: string;
  uploadedByUserId?: string | null;
}

export interface LegalDocumentDto {
  id: string;
  documentType: string;
  title: string;
  versionLabel: string;
  language: string;
  status: string;
  fileName: string;
  sizeBytes: number | null;
  activeFrom: string | null;
  createdAt: string;
}

/**
 * AGB + Widerrufsbelehrung are NOT generated by SynqDrive — the rental company
 * uploads and versions them here. Exactly one ACTIVE document is allowed per
 * (organization, documentType, language); activating a new version archives the
 * previously active one. The active versions are snapshotted onto the booking
 * bundle when documents are generated.
 */
@Injectable()
export class LegalDocumentsService {
  private readonly logger = new Logger(LegalDocumentsService.name);

  constructor(
    private readonly prisma: PrismaService,
    @Inject(DOCUMENTS_STORAGE) private readonly storage: DocumentStoragePort,
  ) {}

  async upload(input: UploadLegalDocumentInput): Promise<OrganizationLegalDocument> {
    if (!isLegalDocumentType(input.documentType)) {
      throw new BadRequestException(
        `documentType must be one of: ${LEGAL_DOCUMENT_TYPES.join(', ')}`,
      );
    }
    if (!isLegalPdfUpload({ mimetype: input.mimeType, originalname: input.fileName })) {
      throw new BadRequestException('Legal documents must be PDF files');
    }
    const versionLabel = (input.versionLabel || '').trim();
    if (!versionLabel) {
      throw new BadRequestException('versionLabel is required');
    }

    const language = (input.language || 'de').toLowerCase();
    const mimeType = normalizeLegalPdfMimeType(input.mimeType, input.fileName);
    const stored = await this.storage.putObject({
      organizationId: input.organizationId,
      bookingId: null,
      documentType: input.documentType,
      originalName: input.fileName,
      buffer: input.buffer,
      mimeType,
    });
    const checksum = createHash('sha256').update(input.buffer).digest('hex');

    return this.prisma.organizationLegalDocument.create({
      data: {
        organizationId: input.organizationId,
        documentType: input.documentType,
        title: input.title?.trim() || DOCUMENT_TITLE_DE[input.documentType] || input.documentType,
        versionLabel,
        language,
        status: LEGAL_STATUS.DRAFT,
        fileName: input.fileName,
        mimeType,
        storageProvider: stored.storageProvider,
        objectKey: stored.objectKey,
        checksum,
        sizeBytes: stored.sizeBytes,
        uploadedByUserId: input.uploadedByUserId ?? null,
      },
    });
  }

  async list(orgId: string): Promise<OrganizationLegalDocument[]> {
    return this.prisma.organizationLegalDocument.findMany({
      where: { organizationId: orgId },
      orderBy: [{ documentType: 'asc' }, { createdAt: 'desc' }],
    });
  }

  async getById(orgId: string, id: string): Promise<OrganizationLegalDocument> {
    const doc = await this.prisma.organizationLegalDocument.findFirst({
      where: { id, organizationId: orgId },
    });
    if (!doc) throw new NotFoundException('Legal document not found');
    return doc;
  }

  /** Activates a version and archives any other ACTIVE version of the same type+language. */
  async activate(orgId: string, id: string): Promise<OrganizationLegalDocument> {
    const doc = await this.getById(orgId, id);
    return this.prisma.$transaction(async (tx) => {
      await tx.organizationLegalDocument.updateMany({
        where: {
          organizationId: orgId,
          documentType: doc.documentType,
          language: doc.language,
          status: LEGAL_STATUS.ACTIVE,
          id: { not: doc.id },
        },
        data: { status: LEGAL_STATUS.ARCHIVED },
      });
      return tx.organizationLegalDocument.update({
        where: { id: doc.id },
        data: { status: LEGAL_STATUS.ACTIVE, activeFrom: new Date() },
      });
    });
  }

  async archive(orgId: string, id: string): Promise<OrganizationLegalDocument> {
    await this.getById(orgId, id);
    return this.prisma.organizationLegalDocument.update({
      where: { id },
      data: { status: LEGAL_STATUS.ARCHIVED },
    });
  }

  /** Returns the active legal document per type for an org+language (default de). */
  async getActiveByType(
    orgId: string,
    language = 'de',
  ): Promise<Record<string, OrganizationLegalDocument | undefined>> {
    const active = await this.prisma.organizationLegalDocument.findMany({
      where: { organizationId: orgId, language, status: LEGAL_STATUS.ACTIVE },
      orderBy: { activeFrom: 'desc' },
    });
    const map: Record<string, OrganizationLegalDocument | undefined> = {};
    for (const doc of active) {
      if (!map[doc.documentType]) map[doc.documentType] = doc;
    }
    return map;
  }

  async getDownload(orgId: string, id: string): Promise<DocumentDownload> {
    const doc = await this.getById(orgId, id);
    const stream = await this.storage.getObjectStream(doc.objectKey);
    return { stream, fileName: doc.fileName, mimeType: doc.mimeType, sizeBytes: doc.sizeBytes };
  }

  toDto(doc: OrganizationLegalDocument): LegalDocumentDto {
    return {
      id: doc.id,
      documentType: doc.documentType,
      title: doc.title,
      versionLabel: doc.versionLabel,
      language: doc.language,
      status: doc.status,
      fileName: doc.fileName,
      sizeBytes: doc.sizeBytes,
      activeFrom: doc.activeFrom ? doc.activeFrom.toISOString() : null,
      createdAt: doc.createdAt.toISOString(),
    };
  }
}
