/**
 * Quarantine / malware-scan pipeline statuses for legal document uploads.
 * Documents must reach SCAN_PASSED before review or activation.
 */
export const LEGAL_DOCUMENT_SCAN_STATUSES = {
  UPLOADED: 'UPLOADED',
  VALIDATING: 'VALIDATING',
  VALIDATION_FAILED: 'VALIDATION_FAILED',
  MALWARE_SCAN_PENDING: 'MALWARE_SCAN_PENDING',
  SCAN_PASSED: 'SCAN_PASSED',
  SCAN_FAILED: 'SCAN_FAILED',
} as const;

export type LegalDocumentScanStatus =
  (typeof LEGAL_DOCUMENT_SCAN_STATUSES)[keyof typeof LEGAL_DOCUMENT_SCAN_STATUSES];

export const LEGAL_DOCUMENT_SCAN_PASSED_STATUSES = new Set<LegalDocumentScanStatus>([
  LEGAL_DOCUMENT_SCAN_STATUSES.SCAN_PASSED,
]);

export const LEGAL_DOCUMENT_VALIDATION_ERROR_CODES = {
  FILE_EMPTY: 'LEGAL_PDF_FILE_EMPTY',
  FILE_TOO_LARGE: 'LEGAL_PDF_FILE_TOO_LARGE',
  MIME_UNSUPPORTED: 'LEGAL_PDF_MIME_UNSUPPORTED',
  MIME_MISMATCH: 'LEGAL_PDF_MIME_MISMATCH',
  NOT_PDF: 'LEGAL_PDF_NOT_PDF',
  CORRUPT: 'LEGAL_PDF_CORRUPT',
  PASSWORD_PROTECTED: 'LEGAL_PDF_PASSWORD_PROTECTED',
  TOO_MANY_PAGES: 'LEGAL_PDF_TOO_MANY_PAGES',
  TOO_COMPLEX: 'LEGAL_PDF_TOO_COMPLEX',
  EMBEDDED_FILES: 'LEGAL_PDF_EMBEDDED_FILES',
  ACTIVE_JAVASCRIPT: 'LEGAL_PDF_ACTIVE_JAVASCRIPT',
  ACTIVE_LAUNCH_ACTION: 'LEGAL_PDF_ACTIVE_LAUNCH_ACTION',
  PARSE_FAILED: 'LEGAL_PDF_PARSE_FAILED',
  VALIDATION_TIMEOUT: 'LEGAL_PDF_VALIDATION_TIMEOUT',
  MALWARE_DETECTED: 'LEGAL_PDF_MALWARE_DETECTED',
  MALWARE_SCAN_FAILED: 'LEGAL_PDF_MALWARE_SCAN_FAILED',
  LEGACY_REVALIDATION_REQUIRED: 'LEGAL_PDF_LEGACY_REVALIDATION_REQUIRED',
} as const;

export type LegalDocumentValidationErrorCode =
  (typeof LEGAL_DOCUMENT_VALIDATION_ERROR_CODES)[keyof typeof LEGAL_DOCUMENT_VALIDATION_ERROR_CODES];

export function isLegalDocumentScanPassed(status: string | null | undefined): boolean {
  return status === LEGAL_DOCUMENT_SCAN_STATUSES.SCAN_PASSED;
}

export function isLegalDocumentUnknownScanStatus(status: string | null | undefined): boolean {
  if (!status) return true;
  return !Object.values(LEGAL_DOCUMENT_SCAN_STATUSES).includes(status as LegalDocumentScanStatus);
}
