/** Resolver contract version — bump on breaking output changes. */
export const POLICY_RESOLVER_VERSION = '1.0.0';

/** Explicit source systems — no empty-string wildcards. */
export const POLICY_RESOLVER_SOURCE_SYSTEM = {
  DIMO: 'DIMO',
  SYNQDRIVE_SYSTEM: 'SYNQDRIVE_SYSTEM',
  CUSTOMER_CONSENT: 'CUSTOMER_CONSENT',
  PARTNER_ACCESS: 'PARTNER_ACCESS',
  MANUAL_UPLOAD: 'MANUAL_UPLOAD',
  API_INTEGRATION: 'API_INTEGRATION',
} as const;

export type PolicyResolverSourceSystem =
  (typeof POLICY_RESOLVER_SOURCE_SYSTEM)[keyof typeof POLICY_RESOLVER_SOURCE_SYSTEM];

/** Explicit actions — empty action is invalid input, not ANY. */
export const POLICY_RESOLVER_ACTION = {
  READ: 'READ',
  WRITE: 'WRITE',
  INGEST: 'INGEST',
  SHARE: 'SHARE',
  PROCESS: 'PROCESS',
} as const;

export type PolicyResolverAction =
  (typeof POLICY_RESOLVER_ACTION)[keyof typeof POLICY_RESOLVER_ACTION];

/** Explicit processor types — required on every request. */
export const POLICY_RESOLVER_PROCESSOR_TYPE = {
  SYNQDRIVE: 'SYNQDRIVE',
  EXTERNAL_PARTNER: 'EXTERNAL_PARTNER',
  INTERNAL_SYSTEM: 'INTERNAL_SYSTEM',
  PROVIDER_PLATFORM: 'PROVIDER_PLATFORM',
} as const;

export type PolicyResolverProcessorType =
  (typeof POLICY_RESOLVER_PROCESSOR_TYPE)[keyof typeof POLICY_RESOLVER_PROCESSOR_TYPE];

/** Explicit resource binding — NONE means no resource anchor (org-wide only). */
export const POLICY_RESOLVER_RESOURCE_TYPE = {
  ORGANIZATION: 'ORGANIZATION',
  VEHICLE: 'VEHICLE',
  CUSTOMER: 'CUSTOMER',
  BOOKING: 'BOOKING',
  STATION: 'STATION',
  CONNECTED_VEHICLES: 'CONNECTED_VEHICLES',
  NONE: 'NONE',
} as const;

export type PolicyResolverResourceType =
  (typeof POLICY_RESOLVER_RESOURCE_TYPE)[keyof typeof POLICY_RESOLVER_RESOURCE_TYPE];

export const POLICY_RESOLVER_DECISION = {
  ALLOW: 'ALLOW',
  DENY: 'DENY',
  SHADOW_WOULD_DENY: 'SHADOW_WOULD_DENY',
  INCOMPLETE: 'INCOMPLETE',
  CONFLICT: 'CONFLICT',
} as const;

export type PolicyResolverDecision =
  (typeof POLICY_RESOLVER_DECISION)[keyof typeof POLICY_RESOLVER_DECISION];

export const POLICY_RESOLVER_REASON = {
  NO_MATCHING_POLICY: 'NO_MATCHING_POLICY',
  POLICY_CONFLICT: 'POLICY_CONFLICT',
  POLICY_SUSPENDED: 'POLICY_SUSPENDED',
  POLICY_REVOKED: 'POLICY_REVOKED',
  POLICY_EXPIRED: 'POLICY_EXPIRED',
  POLICY_NOT_YET_VALID: 'POLICY_NOT_YET_VALID',
  POLICY_SUPERSEDED: 'POLICY_SUPERSEDED',
  PROCESSING_ACTIVITY_INACTIVE: 'PROCESSING_ACTIVITY_INACTIVE',
  PROCESSING_ACTIVITY_MISSING: 'PROCESSING_ACTIVITY_MISSING',
  LEGAL_BASIS_MISSING: 'LEGAL_BASIS_MISSING',
  LEGAL_BASIS_INVALID: 'LEGAL_BASIS_INVALID',
  LEGAL_BASIS_EXPIRED: 'LEGAL_BASIS_EXPIRED',
  LEGAL_BASIS_NOT_ACTIVE: 'LEGAL_BASIS_NOT_ACTIVE',
  CONSENT_REQUIRED: 'CONSENT_REQUIRED',
  CONSENT_MISSING: 'CONSENT_MISSING',
  CONSENT_WITHDRAWN: 'CONSENT_WITHDRAWN',
  CONSENT_EXPIRED: 'CONSENT_EXPIRED',
  CONSENT_PENDING: 'CONSENT_PENDING',
  PROVIDER_GRANT_MISSING: 'PROVIDER_GRANT_MISSING',
  PROVIDER_GRANT_EXPIRED: 'PROVIDER_GRANT_EXPIRED',
  PROVIDER_GRANT_REVOKED: 'PROVIDER_GRANT_REVOKED',
  PROVIDER_GRANT_PENDING: 'PROVIDER_GRANT_PENDING',
  DATA_SHARING_MISSING: 'DATA_SHARING_MISSING',
  DATA_SHARING_UNAUTHORIZED: 'DATA_SHARING_UNAUTHORIZED',
  DATA_SHARING_EXPIRED: 'DATA_SHARING_EXPIRED',
  DATA_SHARING_PENDING: 'DATA_SHARING_PENDING',
  SCOPE_MISMATCH: 'SCOPE_MISMATCH',
  TENANT_MISMATCH: 'TENANT_MISMATCH',
  CATEGORY_MISMATCH: 'CATEGORY_MISMATCH',
  PURPOSE_MISMATCH: 'PURPOSE_MISMATCH',
  PROCESSOR_MISMATCH: 'PROCESSOR_MISMATCH',
  DPIA_REQUIRED: 'DPIA_REQUIRED',
  DPIA_MISSING: 'DPIA_MISSING',
  DPA_REQUIRED: 'DPA_REQUIRED',
  DPA_MISSING: 'DPA_MISSING',
  DPA_NOT_ACTIVE: 'DPA_NOT_ACTIVE',
  TRANSFER_MECHANISM_REQUIRED: 'TRANSFER_MECHANISM_REQUIRED',
  INCOMPLETE_POLICY_DATASET: 'INCOMPLETE_POLICY_DATASET',
  INPUT_INVALID: 'INPUT_INVALID',
  ENFORCEMENT_MODE_OFF: 'ENFORCEMENT_MODE_OFF',
} as const;

export type PolicyResolverReasonCode =
  (typeof POLICY_RESOLVER_REASON)[keyof typeof POLICY_RESOLVER_REASON];

/** EEA country codes for transfer gate (non-exhaustive core set + DE as default). */
export const POLICY_RESOLVER_EEA_COUNTRIES = new Set([
  'AT', 'BE', 'BG', 'HR', 'CY', 'CZ', 'DK', 'EE', 'FI', 'FR', 'DE', 'GR', 'HU', 'IS', 'IE',
  'IT', 'LI', 'LV', 'LT', 'LU', 'MT', 'NL', 'NO', 'PL', 'PT', 'RO', 'SK', 'SI', 'ES', 'SE',
]);

/** Category+purpose combinations requiring DPIA evidence on legal basis. */
export const POLICY_RESOLVER_DPIA_REQUIRED_COMBINATIONS: ReadonlyArray<{
  dataCategory: string;
  purpose: string;
}> = [
  { dataCategory: 'GPS_LOCATION', purpose: 'FLEET_ANALYTICS' },
  { dataCategory: 'DRIVING_BEHAVIOR', purpose: 'ABUSE_MISUSE_DETECTION' },
  { dataCategory: 'HEALTH_SIGNALS', purpose: 'VEHICLE_HEALTH' },
  { dataCategory: 'CUSTOMER_DATA', purpose: 'PARTNER_SERVICE' },
];

/** Scope specificity for deterministic priority (higher = more specific). */
export const POLICY_RESOLVER_SCOPE_PRIORITY: Record<string, number> = {
  VEHICLE: 500,
  BOOKING: 400,
  CUSTOMER: 300,
  STATION: 250,
  CONNECTED_VEHICLES: 200,
  ORGANIZATION: 100,
};

export const POLICY_RESOLVER_SOURCE_VALUES = Object.values(POLICY_RESOLVER_SOURCE_SYSTEM);
export const POLICY_RESOLVER_ACTION_VALUES = Object.values(POLICY_RESOLVER_ACTION);
export const POLICY_RESOLVER_PROCESSOR_TYPE_VALUES = Object.values(POLICY_RESOLVER_PROCESSOR_TYPE);
export const POLICY_RESOLVER_RESOURCE_TYPE_VALUES = Object.values(POLICY_RESOLVER_RESOURCE_TYPE);
