import type {
  WorkflowDomainEventDefinition,
  WorkflowEventPayloadSchema,
} from './workflow-domain-event-registry.types';

const FORBIDDEN_PII = [
  'email',
  'phone',
  'phoneNumber',
  'firstName',
  'lastName',
  'fullName',
  'name',
  'address',
  'street',
  'postalCode',
  'dateOfBirth',
  'licenseNumber',
  'iban',
  'password',
  'token',
  'apiKey',
  'secret',
] as const;

const V1 = '1.0.0';

function schema(
  required: readonly string[],
  optional: readonly string[] = [],
  fields: WorkflowEventPayloadSchema['fields'] = {},
): WorkflowEventPayloadSchema {
  return {
    required,
    optional,
    fields,
    forbidden: FORBIDDEN_PII,
  };
}

function def(
  eventType: string,
  domain: WorkflowDomainEventDefinition['domain'],
  kind: WorkflowDomainEventDefinition['kind'],
  description: string,
  producerModule: string,
  primaryEntityType: string,
  payloadSchema: WorkflowEventPayloadSchema,
  relatedEntityFields?: readonly string[],
): WorkflowDomainEventDefinition {
  return {
    eventType,
    domain,
    kind,
    description,
    defaultVersion: V1,
    primaryEntityType,
    relatedEntityFields,
    producerModule,
    versions: {
      [V1]: {
        eventVersion: V1,
        introducedAt: '2026-07-25',
        payloadSchema,
      },
    },
  };
}

const bookingId = { bookingId: { type: 'string' as const, description: 'Booking UUID' } };
const vehicleId = { vehicleId: { type: 'string' as const, description: 'Vehicle UUID' } };
const stationId = { stationId: { type: 'string' as const, description: 'Station UUID' } };
const customerId = { customerId: { type: 'string' as const, description: 'Customer UUID' } };
const invoiceId = { invoiceId: { type: 'string' as const, description: 'Invoice UUID' } };

/** Canonical workflow domain event catalogue — single source of truth. */
export const WORKFLOW_DOMAIN_EVENT_DEFINITIONS: readonly WorkflowDomainEventDefinition[] = [
  def(
    'booking.created',
    'booking',
    'occurred',
    'A rental booking record was created (draft or pending confirmation).',
    'bookings',
    'booking',
    schema(['bookingId'], ['vehicleId', 'stationId', 'customerId'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      ...customerId,
      status: { type: 'string', description: 'Booking status code at creation' },
    }),
    ['vehicleId', 'customerId', 'stationId'],
  ),
  def(
    'booking.confirmed',
    'booking',
    'occurred',
    'A booking was confirmed and is awaiting pickup.',
    'bookings',
    'booking',
    schema(['bookingId'], ['vehicleId', 'stationId', 'customerId'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      ...customerId,
    }),
    ['vehicleId', 'customerId'],
  ),
  def(
    'booking.pickup_due',
    'booking',
    'state',
    'Scheduled pickup window is approaching (reminder threshold reached).',
    'bookings',
    'booking',
    schema(['bookingId', 'dueAt'], ['vehicleId', 'stationId'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      dueAt: { type: 'iso-date', description: 'Scheduled pickup instant' },
    }),
    ['vehicleId', 'stationId'],
  ),
  def(
    'booking.pickup_overdue',
    'booking',
    'state',
    'Scheduled pickup time has passed without handover completion.',
    'bookings',
    'booking',
    schema(['bookingId', 'dueAt'], ['vehicleId', 'stationId', 'minutesOverdue'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      dueAt: { type: 'iso-date' },
      minutesOverdue: { type: 'number' },
    }),
    ['vehicleId', 'stationId'],
  ),
  def(
    'booking.picked_up',
    'booking',
    'occurred',
    'Vehicle handover at pickup was completed.',
    'bookings',
    'booking',
    schema(['bookingId'], ['vehicleId', 'stationId', 'handoverProtocolId'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      handoverProtocolId: { type: 'string' },
    }),
    ['vehicleId', 'stationId'],
  ),
  def(
    'booking.return_due',
    'booking',
    'state',
    'Scheduled return window is approaching.',
    'bookings',
    'booking',
    schema(['bookingId', 'dueAt'], ['vehicleId', 'stationId'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      dueAt: { type: 'iso-date' },
    }),
    ['vehicleId', 'stationId'],
  ),
  def(
    'booking.return_overdue',
    'booking',
    'state',
    'Scheduled return time has passed without return handover.',
    'bookings',
    'booking',
    schema(['bookingId', 'dueAt'], ['vehicleId', 'stationId', 'minutesOverdue'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      dueAt: { type: 'iso-date' },
      minutesOverdue: { type: 'number' },
    }),
    ['vehicleId', 'stationId'],
  ),
  def(
    'booking.returned',
    'booking',
    'occurred',
    'Vehicle was returned and return handover completed.',
    'bookings',
    'booking',
    schema(['bookingId'], ['vehicleId', 'stationId', 'handoverProtocolId'], {
      ...bookingId,
      ...vehicleId,
      ...stationId,
      handoverProtocolId: { type: 'string' },
    }),
    ['vehicleId', 'stationId'],
  ),
  def(
    'booking.cancelled',
    'booking',
    'occurred',
    'Booking was cancelled before or during rental.',
    'bookings',
    'booking',
    schema(['bookingId'], ['vehicleId', 'reasonCode', 'cancelledBy'], {
      ...bookingId,
      ...vehicleId,
      reasonCode: { type: 'string' },
      cancelledBy: { type: 'string', enum: ['customer', 'operator', 'system'] },
    }),
    ['vehicleId'],
  ),
  def(
    'booking.completed',
    'booking',
    'occurred',
    'Legacy alias: rental lifecycle fully closed (prefer booking.returned for handover).',
    'bookings',
    'booking',
    schema(['bookingId'], ['vehicleId'], { ...bookingId, ...vehicleId }),
    ['vehicleId'],
  ),
  def(
    'vehicle.health.warning',
    'vehicle',
    'state',
    'Vehicle health score or subsystem entered warning band.',
    'vehicle-health',
    'vehicle',
    schema(['vehicleId', 'healthModule'], ['severityCode', 'metricCode'], {
      ...vehicleId,
      healthModule: {
        type: 'string',
        enum: ['brakes', 'tires', 'battery', 'oil', 'service', 'error_codes', 'aggregate'],
      },
      severityCode: { type: 'string' },
      metricCode: { type: 'string' },
    }),
  ),
  def(
    'vehicle.health.critical',
    'vehicle',
    'state',
    'Vehicle health entered critical band requiring immediate attention.',
    'vehicle-health',
    'vehicle',
    schema(['vehicleId', 'healthModule'], ['severityCode', 'metricCode'], {
      ...vehicleId,
      healthModule: { type: 'string' },
      severityCode: { type: 'string' },
      metricCode: { type: 'string' },
    }),
  ),
  def(
    'vehicle.dtc.detected',
    'vehicle',
    'occurred',
    'Diagnostic trouble code detected on vehicle.',
    'vehicle-health',
    'vehicle',
    schema(['vehicleId', 'dtcCode'], ['ecuModule', 'severity'], {
      ...vehicleId,
      dtcCode: { type: 'string' },
      ecuModule: { type: 'string' },
      severity: { type: 'string', enum: ['warning', 'critical'] },
    }),
  ),
  def(
    'vehicle.telemetry.soft_offline',
    'vehicle',
    'state',
    'Telemetry freshness degraded — last signal older than soft threshold.',
    'telemetry',
    'vehicle',
    schema(['vehicleId', 'lastSignalAt'], ['minutesSinceSignal', 'source'], {
      ...vehicleId,
      lastSignalAt: { type: 'iso-date' },
      minutesSinceSignal: { type: 'number' },
      source: { type: 'string', enum: ['dimo', 'hm', 'aggregated'] },
    }),
  ),
  def(
    'vehicle.telemetry.offline',
    'vehicle',
    'state',
    'Telemetry considered offline — last signal older than hard threshold.',
    'telemetry',
    'vehicle',
    schema(['vehicleId', 'lastSignalAt'], ['minutesSinceSignal', 'source'], {
      ...vehicleId,
      lastSignalAt: { type: 'iso-date' },
      minutesSinceSignal: { type: 'number' },
      source: { type: 'string' },
    }),
  ),
  def(
    'vehicle.geofence.entered',
    'vehicle',
    'occurred',
    'Vehicle entered a configured geofence zone.',
    'stations',
    'vehicle',
    schema(['vehicleId', 'geofenceId'], ['stationId', 'zoneName'], {
      ...vehicleId,
      geofenceId: { type: 'string' },
      ...stationId,
      zoneName: { type: 'string' },
    }),
    ['stationId'],
  ),
  def(
    'vehicle.geofence.exited',
    'vehicle',
    'occurred',
    'Vehicle exited a configured geofence zone.',
    'stations',
    'vehicle',
    schema(['vehicleId', 'geofenceId'], ['stationId'], {
      ...vehicleId,
      geofenceId: { type: 'string' },
      ...stationId,
    }),
    ['stationId'],
  ),
  def(
    'vehicle.connectivity.lost',
    'connectivity',
    'state',
    'Vehicle device or modem connectivity lost.',
    'vehicles',
    'vehicle',
    schema(['vehicleId'], ['deviceId', 'lastConnectedAt'], {
      ...vehicleId,
      deviceId: { type: 'string' },
      lastConnectedAt: { type: 'iso-date' },
    }),
  ),
  def(
    'vehicle.connectivity.restored',
    'connectivity',
    'occurred',
    'Vehicle device connectivity restored.',
    'vehicles',
    'vehicle',
    schema(['vehicleId'], ['deviceId', 'restoredAt'], {
      ...vehicleId,
      deviceId: { type: 'string' },
      restoredAt: { type: 'iso-date' },
    }),
  ),
  def(
    'invoice.created',
    'invoice',
    'occurred',
    'Invoice document was created.',
    'billing',
    'invoice',
    schema(['invoiceId'], ['bookingId', 'customerId', 'invoiceKind', 'amountCents'], {
      ...invoiceId,
      ...bookingId,
      ...customerId,
      invoiceKind: { type: 'string', enum: ['rental', 'fine', 'damage', 'extra', 'deposit'] },
      amountCents: { type: 'number' },
    }),
    ['bookingId', 'customerId'],
  ),
  def(
    'invoice.due',
    'invoice',
    'state',
    'Invoice payment due date reached.',
    'billing',
    'invoice',
    schema(['invoiceId', 'dueAt'], ['bookingId', 'customerId', 'amountCents'], {
      ...invoiceId,
      dueAt: { type: 'iso-date' },
      ...bookingId,
      ...customerId,
      amountCents: { type: 'number' },
    }),
    ['bookingId', 'customerId'],
  ),
  def(
    'invoice.overdue',
    'invoice',
    'state',
    'Invoice payment is overdue.',
    'billing',
    'invoice',
    schema(['invoiceId', 'dueAt'], ['bookingId', 'customerId', 'daysOverdue', 'amountCents'], {
      ...invoiceId,
      dueAt: { type: 'iso-date' },
      ...bookingId,
      ...customerId,
      daysOverdue: { type: 'number' },
      amountCents: { type: 'number' },
    }),
    ['bookingId', 'customerId'],
  ),
  def(
    'payment.failed',
    'payment',
    'occurred',
    'Payment attempt failed for invoice or booking charge.',
    'billing',
    'payment',
    schema(['paymentId'], ['invoiceId', 'bookingId', 'failureCode', 'provider'], {
      paymentId: { type: 'string' },
      ...invoiceId,
      ...bookingId,
      failureCode: { type: 'string' },
      provider: { type: 'string', enum: ['stripe', 'manual', 'sepa'] },
    }),
    ['invoiceId', 'bookingId'],
  ),
  def(
    'customer.document.expiring',
    'customer',
    'state',
    'Customer document (license, ID, contract) approaching expiry.',
    'customers',
    'customer',
    schema(['customerId', 'documentId', 'documentType', 'expiresAt'], ['bookingId'], {
      ...customerId,
      documentId: { type: 'string' },
      documentType: { type: 'string', enum: ['license', 'id_card', 'passport', 'contract', 'other'] },
      expiresAt: { type: 'iso-date' },
      ...bookingId,
    }),
    ['bookingId'],
  ),
  def(
    'customer.verification.failed',
    'customer',
    'occurred',
    'Identity or license verification failed or was rejected.',
    'customers',
    'customer',
    schema(['customerId', 'verificationType', 'reasonCode'], ['bookingId', 'providerRef'], {
      ...customerId,
      verificationType: { type: 'string', enum: ['identity', 'license', 'address'] },
      reasonCode: { type: 'string' },
      ...bookingId,
      providerRef: { type: 'string' },
    }),
    ['bookingId'],
  ),
  def(
    'customer.complaint.created',
    'customer',
    'occurred',
    'Customer submitted a support complaint (not traffic fines or invoices).',
    'support',
    'customer',
    schema(['customerId', 'complaintId'], ['bookingId', 'categoryCode'], {
      ...customerId,
      complaintId: { type: 'string' },
      ...bookingId,
      categoryCode: { type: 'string' },
    }),
    ['bookingId'],
  ),
  def(
    'damage.reported',
    'damage',
    'occurred',
    'New vehicle damage record was reported.',
    'damages',
    'damage',
    schema(['damageId', 'vehicleId'], ['bookingId', 'severity', 'reportedBy'], {
      damageId: { type: 'string' },
      ...vehicleId,
      ...bookingId,
      severity: { type: 'string', enum: ['minor', 'moderate', 'severe'] },
      reportedBy: { type: 'string', enum: ['operator', 'customer', 'inspection', 'system'] },
    }),
    ['vehicleId', 'bookingId'],
  ),
  def(
    'service.due',
    'service',
    'state',
    'Scheduled maintenance or service interval is due.',
    'vehicle-health',
    'vehicle',
    schema(['vehicleId', 'serviceType'], ['dueAt', 'odometerKm', 'bookingId'], {
      ...vehicleId,
      serviceType: { type: 'string' },
      dueAt: { type: 'iso-date' },
      odometerKm: { type: 'number' },
      ...bookingId,
    }),
    ['bookingId'],
  ),
  def(
    'task.overdue',
    'task',
    'state',
    'Operational task passed its due date without completion.',
    'tasks',
    'task',
    schema(['taskId'], ['vehicleId', 'bookingId', 'dueAt', 'assigneeId'], {
      taskId: { type: 'string' },
      ...vehicleId,
      ...bookingId,
      dueAt: { type: 'iso-date' },
      assigneeId: { type: 'string' },
    }),
    ['vehicleId', 'bookingId'],
  ),
  def(
    'task.created',
    'task',
    'occurred',
    'Operational task was created (may be workflow action side-effect).',
    'tasks',
    'task',
    schema(['taskId'], ['vehicleId', 'bookingId', 'taskType'], {
      taskId: { type: 'string' },
      ...vehicleId,
      ...bookingId,
      taskType: { type: 'string' },
    }),
    ['vehicleId', 'bookingId'],
  ),
  def(
    'support.ticket.created',
    'support',
    'occurred',
    'Support ticket opened for operator follow-up.',
    'support',
    'support_ticket',
    schema(['ticketId'], ['customerId', 'bookingId', 'vehicleId', 'priority'], {
      ticketId: { type: 'string' },
      ...customerId,
      ...bookingId,
      ...vehicleId,
      priority: { type: 'string', enum: ['low', 'normal', 'high', 'urgent'] },
    }),
    ['customerId', 'bookingId', 'vehicleId'],
  ),
  def(
    'support.ticket.escalated',
    'support',
    'occurred',
    'Support ticket escalated to higher tier.',
    'support',
    'support_ticket',
    schema(['ticketId', 'escalationLevel'], ['customerId', 'bookingId'], {
      ticketId: { type: 'string' },
      escalationLevel: { type: 'string' },
      ...customerId,
      ...bookingId,
    }),
    ['customerId', 'bookingId'],
  ),
  def(
    'notification.dispatch.failed',
    'notification',
    'occurred',
    'Outbound notification could not be delivered.',
    'notifications',
    'notification',
    schema(['notificationId', 'channel'], ['recipientRef', 'failureCode'], {
      notificationId: { type: 'string' },
      channel: { type: 'string', enum: ['email', 'sms', 'push', 'whatsapp', 'in_app'] },
      recipientRef: { type: 'string', description: 'Opaque recipient reference — not email/phone' },
      failureCode: { type: 'string' },
    }),
  ),
  def(
    'notification.delivered',
    'notification',
    'occurred',
    'Outbound notification was successfully delivered.',
    'notifications',
    'notification',
    schema(['notificationId', 'channel'], ['recipientRef'], {
      notificationId: { type: 'string' },
      channel: { type: 'string' },
      recipientRef: { type: 'string' },
    }),
  ),
  def(
    'manual.test',
    'manual',
    'occurred',
    'Operator-initiated test event for workflow validation.',
    'workflows',
    'organization',
    schema([], ['note'], { note: { type: 'string' } }),
  ),
];

export const WORKFLOW_DOMAIN_EVENT_TYPES = WORKFLOW_DOMAIN_EVENT_DEFINITIONS.map(
  (d) => d.eventType,
) as readonly string[];
