/** Default TTL for pending/approved eligibility override requests (7 days). */
export const BOOKING_ELIGIBILITY_APPROVAL_TTL_MS = 7 * 24 * 60 * 60 * 1000;

export const BOOKING_ELIGIBILITY_APPROVAL_ERROR_CODE = {
  NOT_FOUND: 'BOOKING_ELIGIBILITY_APPROVAL_NOT_FOUND',
  INVALID_STATUS: 'BOOKING_ELIGIBILITY_APPROVAL_INVALID_STATUS',
  EXPIRED: 'BOOKING_ELIGIBILITY_APPROVAL_EXPIRED',
  STALE: 'BOOKING_ELIGIBILITY_APPROVAL_STALE',
  SELF_DECISION_DENIED: 'BOOKING_ELIGIBILITY_APPROVAL_SELF_DECISION_DENIED',
  GATE_NOT_MANUAL: 'BOOKING_ELIGIBILITY_APPROVAL_GATE_NOT_MANUAL',
  DECISION_REASON_REQUIRED: 'BOOKING_ELIGIBILITY_APPROVAL_DECISION_REASON_REQUIRED',
} as const;
