import {
  WORKFLOW_AI_MODEL_ID,
  WORKFLOW_AI_PROMPT_VERSION,
} from './workflow-audit.constants';

export interface WorkflowAiTransparency {
  generatedByAi: boolean;
  aiDisclosure: string;
  responsibleOrganization: string;
  modelId: string;
  promptVersion: string;
  humanAgentClaim: false;
  channel?: 'message' | 'voice' | 'suggestion';
}

export function buildAiMessageTransparency(
  organizationName: string,
  channel: 'message' | 'voice' | 'suggestion' = 'message',
): WorkflowAiTransparency {
  return {
    generatedByAi: true,
    aiDisclosure:
      `This ${channel === 'voice' ? 'call' : 'message'} was generated by a digital assistant on behalf of ${organizationName}.`,
    responsibleOrganization: organizationName,
    modelId: WORKFLOW_AI_MODEL_ID,
    promptVersion: WORKFLOW_AI_PROMPT_VERSION,
    humanAgentClaim: false,
    channel,
  };
}

export function buildAiCallOpeningScript(organizationName: string): string {
  return (
    `Hello, you are speaking with the digital assistant of ${organizationName}. ` +
    'This call is assisted by AI and is not a human operator.'
  );
}

export function isWorkflowAiAction(actionType: string): boolean {
  const normalized = actionType.toLowerCase();
  return (
    normalized.startsWith('ai.')
    || normalized.startsWith('ai_')
    || normalized.includes('voice.call')
    || normalized.includes('whatsapp.ai')
  );
}
