export const DI_V0_S4B_CONTROL_PLANE_CONFIG = Symbol('DI_V0_S4B_CONTROL_PLANE_CONFIG');
export const DI_V0_S4B_RUNTIME_PIPELINE = Symbol('DI_V0_S4B_RUNTIME_PIPELINE');
export const DI_V0_S4B_WORK_ITEM_REPOSITORY = Symbol('DI_V0_S4B_WORK_ITEM_REPOSITORY');
export const DI_V0_S4B_EXECUTOR_REGISTRY = Symbol('DI_V0_S4B_EXECUTOR_REGISTRY');
export const DI_V0_S4B_DISCOVERY_SERVICE = Symbol('DI_V0_S4B_DISCOVERY_SERVICE');
export const DI_V0_S4B_CLAIM_LOOP = Symbol('DI_V0_S4B_CLAIM_LOOP');
export const DI_V0_S4B_DISCOVERY_CONTAINMENT = Symbol('DI_V0_S4B_DISCOVERY_CONTAINMENT');
