/** Canonical station domain audit actions stored in ActivityLog.metaJson.auditAction */
export const StationDomainAuditAction = {
  STATION_CREATED: 'STATION_CREATED',
  MASTER_DATA_UPDATED: 'MASTER_DATA_UPDATED',
  OPERATIONS_UPDATED: 'OPERATIONS_UPDATED',
  ACTIVATED: 'ACTIVATED',
  DEACTIVATED: 'DEACTIVATED',
  ARCHIVED: 'ARCHIVED',
  RESTORED: 'RESTORED',
  PRIMARY_CHANGED: 'PRIMARY_CHANGED',
  HOME_STATION_CHANGED: 'HOME_STATION_CHANGED',
  CURRENT_STATION_CORRECTED: 'CURRENT_STATION_CORRECTED',
  EXPECTED_STATION_CHANGED: 'EXPECTED_STATION_CHANGED',
  TRANSFER_PLANNED: 'TRANSFER_PLANNED',
  TRANSFER_STARTED: 'TRANSFER_STARTED',
  TRANSFER_COMPLETED: 'TRANSFER_COMPLETED',
  TRANSFER_CANCELLED: 'TRANSFER_CANCELLED',
  BOOKING_RULE_OVERRIDDEN: 'BOOKING_RULE_OVERRIDDEN',
} as const;

export type StationDomainAuditActionCode =
  (typeof StationDomainAuditAction)[keyof typeof StationDomainAuditAction];
