export const STATION_SCOPE_MODE = {
  ALL_STATIONS: 'ALL_STATIONS',
  ASSIGNED_STATIONS: 'ASSIGNED_STATIONS',
  NO_STATIONS: 'NO_STATIONS',
} as const;

export type StationScopeMode = (typeof STATION_SCOPE_MODE)[keyof typeof STATION_SCOPE_MODE];

export const StationScopeErrorCode = {
  AUTHENTICATION_REQUIRED: 'STATION_SCOPE_AUTHENTICATION_REQUIRED',
  ORGANIZATION_CONTEXT_REQUIRED: 'STATION_SCOPE_ORGANIZATION_CONTEXT_REQUIRED',
  MEMBERSHIP_REQUIRED: 'STATION_SCOPE_MEMBERSHIP_REQUIRED',
  CROSS_ORGANIZATION: 'STATION_SCOPE_CROSS_ORGANIZATION',
  NO_STATIONS: 'STATION_SCOPE_NO_STATIONS',
  STATION_NOT_IN_SCOPE: 'STATION_SCOPE_STATION_NOT_IN_SCOPE',
  STATION_NOT_FOUND: 'STATION_SCOPE_STATION_NOT_FOUND',
  ARCHIVED_WRITE_FORBIDDEN: 'STATION_SCOPE_ARCHIVED_WRITE_FORBIDDEN',
  ARCHIVED_READ_PERMISSION_REQUIRED: 'STATION_SCOPE_ARCHIVED_READ_PERMISSION_REQUIRED',
  ARCHIVED_RESTORE_PERMISSION_REQUIRED: 'STATION_SCOPE_ARCHIVED_RESTORE_PERMISSION_REQUIRED',
  NESTED_RESOURCE_NOT_FOUND: 'STATION_SCOPE_NESTED_RESOURCE_NOT_FOUND',
  NESTED_RESOURCE_OUT_OF_SCOPE: 'STATION_SCOPE_NESTED_RESOURCE_OUT_OF_SCOPE',
  INVALID_STATION_ID: 'STATION_SCOPE_INVALID_STATION_ID',
} as const;

export type StationScopeErrorCodeValue =
  (typeof StationScopeErrorCode)[keyof typeof StationScopeErrorCode];

export const STATION_SCOPE_CONTEXT_KEY = 'stationScopeContext';
