import type { SignalModuleUsage } from './data-analyse.types';
import { DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS } from './data-analyse.constants';

export interface SignalCatalogEntry {
  field: string;
  signalName: string;
  signalGroup: string;
  unit: string | null;
  expectedIntervalMs: number | null;
  highFrequencyCandidate: boolean;
  usedByModules: SignalModuleUsage[];
  storageLocation: string;
}

export const VEHICLE_LATEST_STATE_CATALOG: SignalCatalogEntry[] = [
  {
    field: 'latitude',
    signalName: 'latitude',
    signalGroup: 'location_gps',
    unit: 'deg',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Trips', 'Live Map', 'Driving Analysis'],
    storageLocation: 'vehicle_latest_states.latitude',
  },
  {
    field: 'longitude',
    signalName: 'longitude',
    signalGroup: 'location_gps',
    unit: 'deg',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Trips', 'Live Map', 'Driving Analysis'],
    storageLocation: 'vehicle_latest_states.longitude',
  },
  {
    field: 'speedKmh',
    signalName: 'speed',
    signalGroup: 'location_gps',
    unit: 'km/h',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: true,
    usedByModules: ['Trips', 'Driving Analysis', 'Live Map', 'Brake Health', 'Tire Health'],
    storageLocation: 'vehicle_latest_states.speed_kmh',
  },
  {
    field: 'odometerKm',
    signalName: 'odometer',
    signalGroup: 'odometer_mileage',
    unit: 'km',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Trips', 'Brake Health', 'Tire Health'],
    storageLocation: 'vehicle_latest_states.odometer_km',
  },
  {
    field: 'isIgnitionOn',
    signalName: 'ignition',
    signalGroup: 'trip_movement',
    unit: null,
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Trips', 'Driving Analysis'],
    storageLocation: 'vehicle_latest_states.is_ignition_on',
  },
  {
    field: 'engineLoad',
    signalName: 'engine_load',
    signalGroup: 'high_frequency_driving',
    unit: '%',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: true,
    usedByModules: ['Driving Analysis'],
    storageLocation: 'vehicle_latest_states.engine_load',
  },
  {
    field: 'lvBatteryVoltage',
    signalName: 'lv_battery_voltage',
    signalGroup: 'battery_energy',
    unit: 'V',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Battery Health', 'Alerts'],
    storageLocation: 'vehicle_latest_states.lv_battery_voltage',
  },
  {
    field: 'evSoc',
    signalName: 'ev_soc',
    signalGroup: 'battery_energy',
    unit: '%',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Battery Health', 'Live Map', 'Alerts'],
    storageLocation: 'vehicle_latest_states.ev_soc',
  },
  {
    field: 'tractionBatteryPowerKw',
    signalName: 'traction_battery_power',
    signalGroup: 'battery_energy',
    unit: 'kW',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: true,
    usedByModules: ['Battery Health', 'Driving Analysis'],
    storageLocation: 'vehicle_latest_states.traction_battery_power_kw',
  },
  {
    field: 'tractionBatterySohPercent',
    signalName: 'traction_battery_soh',
    signalGroup: 'battery_energy',
    unit: '%',
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Battery Health'],
    storageLocation: 'vehicle_latest_states.traction_battery_soh_percent',
  },
  {
    field: 'tractionBatteryCurrentVoltage',
    signalName: 'traction_battery_voltage',
    signalGroup: 'battery_energy',
    unit: 'V',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Battery Health'],
    storageLocation: 'vehicle_latest_states.traction_battery_current_voltage',
  },
  {
    field: 'fuelLevelRelative',
    signalName: 'fuel_level_relative',
    signalGroup: 'battery_energy',
    unit: '%',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Alerts', 'Live Map'],
    storageLocation: 'vehicle_latest_states.fuel_level_relative',
  },
  {
    field: 'fuelLevelAbsolute',
    signalName: 'fuel_level_absolute',
    signalGroup: 'battery_energy',
    unit: 'L',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Alerts'],
    storageLocation: 'vehicle_latest_states.fuel_level_absolute',
  },
  {
    field: 'rangeKm',
    signalName: 'range',
    signalGroup: 'battery_energy',
    unit: 'km',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Live Map', 'Alerts'],
    storageLocation: 'vehicle_latest_states.range_km',
  },
  {
    field: 'tirePressureFl',
    signalName: 'tire_pressure_fl',
    signalGroup: 'tire_relevant',
    unit: 'bar',
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Tire Health', 'Alerts'],
    storageLocation: 'vehicle_latest_states.tire_pressure_fl',
  },
  {
    field: 'tirePressureFr',
    signalName: 'tire_pressure_fr',
    signalGroup: 'tire_relevant',
    unit: 'bar',
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Tire Health', 'Alerts'],
    storageLocation: 'vehicle_latest_states.tire_pressure_fr',
  },
  {
    field: 'tirePressureRl',
    signalName: 'tire_pressure_rl',
    signalGroup: 'tire_relevant',
    unit: 'bar',
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Tire Health', 'Alerts'],
    storageLocation: 'vehicle_latest_states.tire_pressure_rl',
  },
  {
    field: 'tirePressureRr',
    signalName: 'tire_pressure_rr',
    signalGroup: 'tire_relevant',
    unit: 'bar',
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Tire Health', 'Alerts'],
    storageLocation: 'vehicle_latest_states.tire_pressure_rr',
  },
  {
    field: 'tireHealthPercent',
    signalName: 'tire_health_percent',
    signalGroup: 'tire_relevant',
    unit: '%',
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Tire Health'],
    storageLocation: 'vehicle_latest_states.tire_health_percent',
  },
  {
    field: 'brakePadPercent',
    signalName: 'brake_pad_percent',
    signalGroup: 'brake_relevant',
    unit: '%',
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Brake Health'],
    storageLocation: 'vehicle_latest_states.brake_pad_percent',
  },
  {
    field: 'coolantTempC',
    signalName: 'coolant_temp',
    signalGroup: 'high_frequency_driving',
    unit: '°C',
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: true,
    usedByModules: ['Driving Analysis', 'Alerts'],
    storageLocation: 'vehicle_latest_states.coolant_temp_c',
  },
  {
    field: 'obdDtcList',
    signalName: 'obd_dtc_list',
    signalGroup: 'dtc_diagnostic',
    unit: null,
    expectedIntervalMs: null,
    highFrequencyCandidate: false,
    usedByModules: ['Alerts'],
    storageLocation: 'vehicle_latest_states.obd_dtc_list',
  },
  {
    field: 'online',
    signalName: 'connectivity_online',
    signalGroup: 'connectivity_device',
    unit: null,
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Live Map', 'Alerts'],
    storageLocation: 'vehicle_latest_states.online',
  },
  {
    field: 'lastSeenAt',
    signalName: 'last_seen',
    signalGroup: 'connectivity_device',
    unit: null,
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    highFrequencyCandidate: false,
    usedByModules: ['Live Map', 'Alerts'],
    storageLocation: 'vehicle_latest_states.last_seen_at',
  },
];

export const LAUNCH_REQUIRED_SIGNALS = [
  'speed',
  'longitudinal_acceleration',
  'throttle_position',
  'engine_rpm',
  'torque',
  'pedal_position',
  'wheel_speed',
  'traction_stability_event',
  'movement_start',
  'trip_start_context',
] as const;

export const SIGNAL_GROUP_DEFINITIONS = [
  {
    id: 'vehicle_identity',
    groupName: 'Vehicle Identity / Metadata',
    description:
      'Fahrzeugidentität, VIN, Marke, Modell, Baujahr, Provider-Zuordnung.',
    typicalSignals: ['vin', 'make', 'model', 'year', 'provider_binding'],
    expectedIntervalMs: null,
    practicalUse: 'Master Data, Vehicle Matching, Fleet Overview.',
    usedByModules: ['Fleet', 'Bookings'],
    detectionRelevance: 'Low — contextual only',
    catalogGroups: [] as string[],
  },
  {
    id: 'location_gps',
    groupName: 'Location / GPS',
    description: 'Positionsdaten, Koordinaten, Richtung, Geschwindigkeit, Bewegung.',
    typicalSignals: ['latitude', 'longitude', 'speed', 'heading'],
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    practicalUse: 'Live Map, Trips, Pickup/Return, Geofencing, Movement Detection.',
    usedByModules: ['Trips', 'Live Map', 'Driving Analysis'],
    detectionRelevance: 'High for movement and speed-based events',
    catalogGroups: ['location_gps'],
  },
  {
    id: 'odometer_mileage',
    groupName: 'Odometer / Mileage',
    description: 'Kilometerstand und Laufleistung.',
    typicalSignals: ['odometer'],
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    practicalUse: 'Bookings, Return Checks, Maintenance, Service, Tire/Brake Wear.',
    usedByModules: ['Trips', 'Brake Health', 'Tire Health'],
    detectionRelevance: 'Medium — wear modeling input',
    catalogGroups: ['odometer_mileage'],
  },
  {
    id: 'trip_movement',
    groupName: 'Trip / Movement',
    description: 'Fahrtbeginn, Fahrtende, Bewegungsstatus, Trip-Zuordnung.',
    typicalSignals: ['ignition', 'motion', 'trip_boundaries'],
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    practicalUse: 'Trip History, Driving Analysis, Abuse/Misuse, Rental Context.',
    usedByModules: ['Trips', 'Driving Analysis'],
    detectionRelevance: 'High for trip context',
    catalogGroups: ['trip_movement'],
  },
  {
    id: 'high_frequency_driving',
    groupName: 'High Frequency Driving Signals',
    description: 'Schnell getaktete Fahrdynamiksignale.',
    typicalSignals: [
      'speed',
      'acceleration',
      'rpm',
      'throttle',
      'torque',
      'brake_input',
      'wheel_speed',
    ],
    expectedIntervalMs: 500,
    practicalUse: 'Harsh acceleration, harsh braking, launch-like start, driving impact.',
    usedByModules: ['Driving Analysis', 'Brake Health', 'Tire Health'],
    detectionRelevance: 'Critical for event detection',
    catalogGroups: ['high_frequency_driving'],
  },
  {
    id: 'brake_relevant',
    groupName: 'Brake-Relevant Signals',
    description: 'Signale für Bremsverschleiß und Bremsbelastung.',
    typicalSignals: [
      'harsh_braking',
      'deceleration',
      'speed_delta',
      'trip_distance',
      'driving_style_impact',
    ],
    expectedIntervalMs: null,
    practicalUse: 'Brake Health, estimated remaining km, risk indicators.',
    usedByModules: ['Brake Health', 'Driving Analysis'],
    detectionRelevance: 'High for brake wear modeling',
    catalogGroups: ['brake_relevant'],
  },
  {
    id: 'tire_relevant',
    groupName: 'Tire-Relevant Signals',
    description: 'Reifenverschleiß und Reifenzustand.',
    typicalSignals: [
      'distance',
      'speed',
      'harsh_acceleration',
      'harsh_braking',
      'cornering',
      'pressure',
    ],
    expectedIntervalMs: null,
    practicalUse: 'Tire Health, tread estimation, wear acceleration.',
    usedByModules: ['Tire Health', 'Driving Analysis'],
    detectionRelevance: 'Medium–High',
    catalogGroups: ['tire_relevant'],
  },
  {
    id: 'battery_energy',
    groupName: 'Battery / Energy Signals',
    description: 'LV/12V und HV/EV-Batterie sowie Energie-/Fuel-Daten.',
    typicalSignals: [
      'state_of_charge',
      'state_of_health',
      'voltage',
      'resting_voltage',
      'fuel_level',
      'ev_range',
    ],
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    practicalUse: 'Battery Health, Range, Alerts, Fleet Readiness.',
    usedByModules: ['Battery Health', 'Alerts', 'Live Map'],
    detectionRelevance: 'Low for driving events, high for health',
    catalogGroups: ['battery_energy'],
  },
  {
    id: 'dtc_diagnostic',
    groupName: 'DTC / Diagnostic Trouble Codes',
    description: 'Fehlercodes und Diagnosedaten.',
    typicalSignals: ['obd_dtc_list', 'dtc_events'],
    expectedIntervalMs: null,
    practicalUse: 'Vehicle Health, Alerts, Maintenance, AI DTC Knowledge.',
    usedByModules: ['Alerts'],
    detectionRelevance: 'Diagnostic, not driving dynamics',
    catalogGroups: ['dtc_diagnostic'],
  },
  {
    id: 'connectivity_device',
    groupName: 'Connectivity / Device Status',
    description: 'Provider-/Hardware-Verbindungsstatus, last seen, data freshness.',
    typicalSignals: ['online', 'last_seen', 'provider_fetched_at'],
    expectedIntervalMs: DEFAULT_SNAPSHOT_EXPECTED_INTERVAL_MS,
    practicalUse: 'Fleet Connectivity, Data Reliability, Debugging.',
    usedByModules: ['Live Map', 'Alerts'],
    detectionRelevance: 'Meta — data quality gate',
    catalogGroups: ['connectivity_device'],
  },
] as const;
