export const PRICING_ENGINE_VERSION = 'pricing-engine-v1' as const;

export const PRICING_QUOTE_ATOMIC_ERROR_CODES = {
  QUOTE_TAMPERED: 'PRICING_QUOTE_TAMPERED',
  SNAPSHOT_FAILED: 'BOOKING_PRICE_SNAPSHOT_FAILED',
} as const;
