export const minimalOperationalDetailFixture = {
  vehicleId: 'veh-1',
  organizationId: 'org-1',
  registryLifecycle: 'ACTIVE' as const,
  registrationState: 'registered' as const,
  displayTitle: 'Vehicle 1',
  displaySubtitle: 'sub',
  organizationName: 'Org',
  authorization: { state: 'connected' as const, platformDimoDegraded: false, note: null },
  mapping: {
    dimoVehicleId: null,
    dimoExternalId: null,
    tokenIdMasked: null,
    connectionStatus: null,
    syncedAt: null,
    deviceType: null,
  },
  activeIssues: [],
  integrity: 'ok' as const,
  integrationConnectivity: 'connected' as const,
  integrationConnectivityLabel: 'Connected',
  telemetryFreshness: 'live' as const,
  telemetryLabel: 'Live',
  attention: { severity: 'none' as const, reasons: [] },
  telemetryObservedAtIso: null,
  lastSignalRelative: null,
  pipeline: {
    lastProcessingAt: null,
    lastSuccessfulIngestAt: null,
    stale: false,
    lastPollStatus: null,
    lastPollAt: null,
  },
  auditEvents: [],
};
