export const COMMUNICATION_HEALTH_STATE = {
  HEALTHY: 'HEALTHY',
  DEGRADED: 'DEGRADED',
  UNHEALTHY: 'UNHEALTHY',
  UNKNOWN: 'UNKNOWN',
  DISABLED: 'DISABLED',
  NOT_CONFIGURED: 'NOT_CONFIGURED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
} as const;

export type CommunicationHealthState =
  (typeof COMMUNICATION_HEALTH_STATE)[keyof typeof COMMUNICATION_HEALTH_STATE];

export const COMMUNICATION_HEALTH_COMPONENT = {
  PROJECTION: 'projection',
  OUTBOUND: 'outbound',
  RECONCILIATION: 'reconciliation',
  HANDOFF: 'handoff',
  MEDIA: 'media',
  AI: 'ai',
  RETENTION: 'retention',
  CHANNEL_READINESS: 'channelReadiness',
} as const;

export type CommunicationHealthComponent =
  (typeof COMMUNICATION_HEALTH_COMPONENT)[keyof typeof COMMUNICATION_HEALTH_COMPONENT];

export const COMMUNICATION_HEALTH_DIAGNOSTIC = {
  PROJECTION_BACKLOG: 'PROJECTION_BACKLOG',
  SEND_UNKNOWN_BACKLOG: 'SEND_UNKNOWN_BACKLOG',
  RECONCILIATION_STALE: 'RECONCILIATION_STALE',
  HANDOFF_BACKLOG: 'HANDOFF_BACKLOG',
  HANDOFF_NOTIFICATION_FAILURE: 'HANDOFF_NOTIFICATION_FAILURE',
  AI_OPERATION_FAILURE: 'AI_OPERATION_FAILURE',
  RETENTION_STALE: 'RETENTION_STALE',
  RETENTION_LOCK_LOST: 'RETENTION_LOCK_LOST',
  RETENTION_RUN_FAILED: 'RETENTION_RUN_FAILED',
  VOICE_WEBHOOK_BACKLOG: 'VOICE_WEBHOOK_BACKLOG',
  WHATSAPP_WEBHOOK_BACKLOG: 'WHATSAPP_WEBHOOK_BACKLOG',
  INSUFFICIENT_EVIDENCE: 'INSUFFICIENT_EVIDENCE',
  NOT_MEASURABLE: 'NOT_MEASURABLE',
  NOT_MEASURABLE_FOR_TENANT: 'NOT_MEASURABLE_FOR_TENANT',
  CANONICAL_PROJECTION_LAG_NOT_MEASURABLE: 'CANONICAL_PROJECTION_LAG_NOT_MEASURABLE',
  RETENTION_TENANT_EVIDENCE_GLOBAL_ONLY: 'RETENTION_TENANT_EVIDENCE_GLOBAL_ONLY',
  DEFERRED_TO_EXISTING_C10_AUTHORITY: 'DEFERRED_TO_EXISTING_C10_AUTHORITY',
  QUERY_UNAVAILABLE: 'QUERY_UNAVAILABLE',
} as const;

export type CommunicationHealthDiagnostic =
  (typeof COMMUNICATION_HEALTH_DIAGNOSTIC)[keyof typeof COMMUNICATION_HEALTH_DIAGNOSTIC];

export const COMMUNICATION_HEALTH_THRESHOLD_AUTHORITY = {
  EXISTING_THRESHOLD: 'EXISTING_THRESHOLD',
  DERIVED_SAFE_DEFAULT: 'DERIVED_SAFE_DEFAULT',
  POLICY_REQUIRED: 'POLICY_REQUIRED',
} as const;

export const COMMUNICATION_HEALTH_CHANNEL = {
  WHATSAPP: 'WHATSAPP',
  VOICE: 'VOICE',
  SMS: 'SMS',
  EMAIL: 'EMAIL',
} as const;

export type CommunicationHealthChannel =
  (typeof COMMUNICATION_HEALTH_CHANNEL)[keyof typeof COMMUNICATION_HEALTH_CHANNEL];

/** ReplyCommand-supported channels for UNKNOWN send attribution. */
export const COMMUNICATION_UNKNOWN_SEND_CHANNELS = [
  COMMUNICATION_HEALTH_CHANNEL.WHATSAPP,
  COMMUNICATION_HEALTH_CHANNEL.VOICE,
  COMMUNICATION_HEALTH_CHANNEL.SMS,
  COMMUNICATION_HEALTH_CHANNEL.EMAIL,
] as const satisfies readonly CommunicationHealthChannel[];

/** Optional components whose UNKNOWN state does not block overall platform health. */
export const COMMUNICATION_HEALTH_OPTIONAL_UNMEASURED_COMPONENTS = [
  COMMUNICATION_HEALTH_COMPONENT.MEDIA,
  COMMUNICATION_HEALTH_COMPONENT.AI,
] as const;
