export const OPERATOR_UPLOAD_ERROR = {
  NOT_FOUND: 'OPERATOR_UPLOAD_NOT_FOUND',
  SESSION_DENIED: 'OPERATOR_UPLOAD_SESSION_DENIED',
  SESSION_CANCELLED: 'OPERATOR_UPLOAD_SESSION_CANCELLED',
  SESSION_NOT_EDITABLE: 'OPERATOR_UPLOAD_SESSION_NOT_EDITABLE',
  VALIDATION: 'OPERATOR_UPLOAD_VALIDATION',
  NOT_RETRYABLE: 'OPERATOR_UPLOAD_NOT_RETRYABLE',
  MAX_ATTEMPTS: 'OPERATOR_UPLOAD_MAX_ATTEMPTS',
  INCOMPLETE: 'OPERATOR_UPLOAD_INCOMPLETE',
  CANCELLED: 'OPERATOR_UPLOAD_CANCELLED',
  BOOKING_MISMATCH: 'OPERATOR_UPLOAD_BOOKING_MISMATCH',
} as const;

export const OPERATOR_UPLOAD_RETENTION_MS = 7 * 24 * 60 * 60 * 1000;
export const OPERATOR_UPLOAD_MAX_BYTES = 8 * 1024 * 1024;
export const OPERATOR_UPLOAD_MAX_ATTEMPTS = 5;

export const OPERATOR_UPLOAD_ALLOWED_MIME = new Set([
  'image/jpeg',
  'image/jpg',
  'image/png',
  'image/webp',
  'image/gif',
  'application/pdf',
]);
