export const WORKFLOW_LIFECYCLE_ERROR_CODES = {
  NOT_FOUND: 'WORKFLOW_DEFINITION_NOT_FOUND',
  VERSION_NOT_FOUND: 'WORKFLOW_VERSION_NOT_FOUND',
  FOREIGN_TENANT: 'WORKFLOW_DEFINITION_FOREIGN_TENANT',
  ARCHIVED: 'WORKFLOW_DEFINITION_ARCHIVED',
  VERSION_IMMUTABLE: 'WORKFLOW_VERSION_IMMUTABLE',
  NOT_DRAFT: 'WORKFLOW_VERSION_NOT_DRAFT',
  NOT_PUBLISHED: 'WORKFLOW_VERSION_NOT_PUBLISHED',
  NOT_ACTIVE: 'WORKFLOW_VERSION_NOT_ACTIVE',
  LOCK_CONFLICT: 'WORKFLOW_DEFINITION_LOCK_CONFLICT',
  PUBLISH_VALIDATION_FAILED: 'WORKFLOW_PUBLISH_VALIDATION_FAILED',
  ACTIVATION_VALIDATION_FAILED: 'WORKFLOW_ACTIVATION_VALIDATION_FAILED',
  DRAFT_EXISTS: 'WORKFLOW_DRAFT_ALREADY_EXISTS',
  NO_DRAFT: 'WORKFLOW_NO_DRAFT_VERSION',
  ALREADY_PUBLISHED: 'WORKFLOW_VERSION_ALREADY_PUBLISHED',
  ALREADY_ACTIVE: 'WORKFLOW_VERSION_ALREADY_ACTIVE',
  CONCURRENT_LIFECYCLE: 'WORKFLOW_CONCURRENT_LIFECYCLE_CONFLICT',
} as const;

export type WorkflowLifecycleErrorCode =
  (typeof WORKFLOW_LIFECYCLE_ERROR_CODES)[keyof typeof WORKFLOW_LIFECYCLE_ERROR_CODES];
