export const LEGAL_DOCUMENT_HASH_ALGORITHM = 'sha256' as const;

export const BOOKING_LEGAL_DOCUMENT_SNAPSHOT_EVENT_TYPE = {
  CREATED: 'SNAPSHOT_CREATED',
  INTEGRITY_VERIFIED: 'SNAPSHOT_INTEGRITY_VERIFIED',
  INTEGRITY_FAILED: 'SNAPSHOT_INTEGRITY_FAILED',
  RETRIEVAL_BLOCKED: 'SNAPSHOT_RETRIEVAL_BLOCKED',
  SILENT_REGENERATION_BLOCKED: 'SNAPSHOT_SILENT_REGENERATION_BLOCKED',
} as const;

export const BOOKING_LEGAL_DOCUMENT_SNAPSHOT_ERROR_CODE = {
  NOT_FOUND: 'BOOKING_LEGAL_DOCUMENT_SNAPSHOT_NOT_FOUND',
  BOOKING_SCOPE: 'BOOKING_LEGAL_DOCUMENT_SNAPSHOT_BOOKING_SCOPE',
  MISSING_CHECKSUM: 'BOOKING_LEGAL_DOCUMENT_SNAPSHOT_MISSING_CHECKSUM',
  INTEGRITY_FAILED: 'BOOKING_LEGAL_DOCUMENT_SNAPSHOT_INTEGRITY_FAILED',
  CROSS_TENANT: 'BOOKING_LEGAL_DOCUMENT_SNAPSHOT_CROSS_TENANT',
  SILENT_REGENERATION: 'BOOKING_LEGAL_DOCUMENT_SNAPSHOT_SILENT_REGENERATION',
} as const;

export const CHECKOUT_LEGAL_DOCUMENT_TYPES = [
  'TERMS_AND_CONDITIONS',
  'CONSUMER_INFORMATION',
  'PRIVACY_POLICY',
] as const;
