export { AiModule } from './ai.module';
export { LlmGatewayService } from './llm/llm-gateway.service';
export { LLM_PROVIDER } from './llm/llm-provider.token';
export type {
  LlmCompleteInput,
  LlmCompleteResult,
  LlmJsonInput,
  LlmJsonResult,
  LlmMessage,
  LlmMessageRole,
  LlmModelPurpose,
  LlmProvider,
  LlmStreamEvent,
  LlmStreamEventType,
  LlmStreamInput,
  LlmUsage,
} from './llm/llm.types';
export { MistralLlmService } from './providers/mistral/mistral-llm.service';
export { MistralOcrService } from './providers/mistral/mistral-ocr.service';
export { MistralSdkClientProvider } from './providers/mistral/mistral-sdk-client.provider';
export type {
  MistralOcrInput,
  MistralOcrOutput,
  MistralOcrPage,
} from './providers/mistral/mistral-ocr.types';
export {
  MISTRAL_OCR_ERROR_CODES,
  MistralOcrError,
} from './providers/mistral/mistral-ocr.errors';
export { DocumentAiExtractionService } from './documents/document-ai-extraction.service';
export { VehicleSpecAiService } from './vehicle-specs/vehicle-spec-ai.service';
export { TireSpecAiService } from './vehicle-specs/tire-spec-ai.service';
export { AiTireSpecJobService } from './vehicle-specs/ai-tire-spec-job.service';
export { ChatService } from './chat/chat.service';
export { AiHealthController } from './ai-health.controller';
export {
  AI_EVIDENCE_AVAILABILITY,
  AI_EVIDENCE_CONFIDENCE,
  AI_EVIDENCE_FACT_KINDS,
  AI_EVIDENCE_FRESHNESS,
  AI_EVIDENCE_REASON_CODES,
  AI_EVIDENCE_SENSITIVITY,
  AI_EVIDENCE_SOURCES,
  AI_EVIDENCE_SOURCE_ENTITY_KINDS,
  AiEvidenceBatchDto,
  AiEvidenceDto,
  AiEvidenceSourceEntityDto,
  assertValidAiEvidence,
  containsLikelyRawPii,
  createCalculatedAiEvidence,
  createObservedAiEvidence,
  createPermissionDeniedAiEvidence,
  createStaleObservedAiEvidence,
  createStaticAiEvidence,
  createUnavailableAiEvidence,
  isAiEvidenceEnumValue,
  isRedactedAiEvidenceValue,
  parseAiEvidenceIsoTimestampMs,
  parseAiEvidenceJson,
  serializeAiEvidenceForLlm,
  toAiEvidenceJson,
  validateAiEvidence,
  validateAiEvidenceDto,
} from './evidence';
export type {
  AiEvidence,
  AiEvidenceAvailability,
  AiEvidenceConfidence,
  AiEvidenceDtoValue,
  AiEvidenceFactKind,
  AiEvidenceFreshness,
  AiEvidencePrimitive,
  AiEvidenceReasonCode,
  AiEvidenceSensitivity,
  AiEvidenceSource,
  AiEvidenceSourceEntity,
  AiEvidenceSourceEntityKind,
  AiEvidenceTelemetrySemantics,
  AiEvidenceValidationIssue,
  AiEvidenceValidationOptions,
  AiEvidenceValidationResult,
  AiEvidenceValue,
  AiTelemetryLiveHints,
  AiTelemetrySemanticsMappingRow,
  CreateAiEvidenceBaseInput,
  MapTelemetryToAiEvidenceInput,
  MappedTelemetryAiSemantics,
  TelemetryFreshness,
} from './evidence';
export {
  AI_DOMAIN_AUDIT_EVENTS,
  AI_DOMAIN_ERROR_CATALOG,
  AI_DOMAIN_ERROR_CODES,
  AI_DOMAIN_ERROR_FACTORIES,
  AI_DOMAIN_ERROR_RETRY_POLICY,
  AI_DOMAIN_ERROR_SEVERITY,
  AI_DOMAIN_HTTP_STATUS,
  AI_EVIDENCE_TELEMETRY_SEMANTICS,
  AI_TELEMETRY_SEMANTICS_MAPPING_TABLE,
  assertNoDiagnosticsInPublicView,
  buildAiDomainQueryOutcome,
  buildPartialAiDomainQueryOutcome,
  createAiDomainError,
  createDataNotAvailableError,
  createDataTooOldError,
  createDomainStatusInconsistentError,
  createIntegrationNotConnectedError,
  createIntegrationTemporarilyUnavailableError,
  createInternalProcessingFailedError,
  createInvalidInputError,
  createPermissionDeniedError,
  createRoleRestrictedError,
  createSignalNotSupportedError,
  createTimeoutError,
  createVehicleAmbiguousError,
  createVehicleNotFoundError,
  describeAiDomainErrorCode,
  getAiDomainErrorCatalogEntry,
  hasAiTelemetryFreshLiveHint,
  isAiDomainErrorCode,
  mapCanonicalTelemetryFreshnessToSemantics,
  mapDashboardTelemetryStateToSemantics,
  mapEvidenceReasonCodeToDomainErrorCode,
  mapTelemetryToAiEvidenceSemantics,
  resolveSecureVehicleAccessError,
  sanitizeAiDomainDiagnosticText,
  serializeAiDomainErrorForLlm,
  toAiDomainErrorApiView,
  toAiDomainErrorAuditPayload,
  toAiDomainQueryOutcomeForLlm,
  TELEMETRY_FRESH_THRESHOLD_MS,
  TELEMETRY_SIGNAL_DELAYED_THRESHOLD_MS,
  TELEMETRY_STANDBY_THRESHOLD_MS,
} from './evidence';
export type {
  AiDomainAuditEvent,
  AiDomainError,
  AiDomainErrorApiView,
  AiDomainErrorCatalogEntry,
  AiDomainErrorCode,
  AiDomainErrorDiagnostics,
  AiDomainErrorPublicView,
  AiDomainErrorRetryPolicy,
  AiDomainErrorSeverity,
  AiDomainHttpStatus,
  AiDomainQueryOutcome,
  CreateAiDomainErrorInput,
} from './evidence';
export {
  AI_DATA_ACCESS_PURPOSES,
  AI_EXECUTION_ACCESS_KINDS,
  AI_EXECUTION_CHANNELS,
  AI_VEHICLE_SCOPE_MODES,
  aiExecutionContextLogFields,
  assertAiBookingAccess,
  assertAiCustomerDataAccess,
  assertAiExecutionContextPresent,
  assertAiFleetSummaryAccess,
  assertAiHealthAccess,
  assertAiLocationAccess,
  assertAiToolExecutionAllowed,
  assertValidAiExecutionContext,
  buildAiExecutionContext,
  generateAiCorrelationId,
  isValidAiExecutionUuid,
  membershipPermissionsForContext,
  resolveAiExecutionContextError,
  resolveAiRequestId,
  resolveAiVehicleAccess,
  validateAiExecutionContext,
} from './execution';
export type {
  AiAllowedVehicleScope,
  AiDataAccessPurpose,
  AiDataAuthorizationProbe,
  AiExecutionAccessAuditPayload,
  AiExecutionAccessKind,
  AiExecutionChannel,
  AiExecutionContext,
  AiExecutionContextValidationIssue,
  AiExecutionContextValidationResult,
  AiVehicleAccessInput,
  AiVehicleAccessResult,
  AiVehicleOrgBinding,
  AiVehicleScopeMode,
  AiVehicleScopeResolver,
  VerifiedAiExecutionContextInput,
} from './execution';
export type {
  DocumentAiExtractInput,
  DocumentAiExtractResult,
  DocumentAiField,
  DocumentAiVehicleContext,
} from './documents/document-ai-extraction.types';
export {
  AI_VEHICLE_AMBIGUITY_DELTA,
  AI_VEHICLE_MATCH_BASE_SCORE,
  AI_VEHICLE_MATCH_TYPES,
  AI_VEHICLE_MIN_CONFIDENCE,
  AiVehicleResolutionService,
  buildEnrichedChatMessage,
  buildAiVehicleDisplayName,
  extractAiVehicleResolutionHints,
  FLEET_CHAT_SYSTEM_PROMPT,
  formatChatScopeLog,
  normalizePlate,
  resolveAiVehicleFromMessage,
  resolveChatVehicleTokenIds,
  sanitizeAiVehicleLlmField,
  sanitizeAiVehicleUserText,
  toLlmSafeVehicleCandidate,
} from './vehicle-resolution';
export type {
  AiVehicleAllowedDataScope,
  AiVehicleMatchType,
  AiVehicleResolutionAmbiguity,
  AiVehicleResolutionCandidate,
  AiVehicleResolutionHints,
  AiVehicleResolutionRecord,
  AiVehicleResolutionResult,
  ResolveAiVehicleFromMessageInput,
} from './vehicle-resolution';
export {
  AI_GET_VEHICLE_LOCATION_TOOL,
  AI_GET_VEHICLE_TELEMETRY_STATUS_TOOL,
  AI_GET_VEHICLE_HEALTH_SUMMARY_TOOL,
  AI_EXPLAIN_OVERDUE_RETURN_TOOL,
  AI_GET_VEHICLE_BOOKING_CONTEXT_TOOL,
  AiDataAuthorizationProbeAdapter,
  AiGetVehicleLocationTool,
  AiGetVehicleTelemetryStatusTool,
  AiGetVehicleHealthSummaryTool,
  AiExplainOverdueReturnTool,
  AiGetVehicleBookingContextTool,
  AiPrismaVehicleScopeResolver,
} from './tools';
export type {
  AiGetVehicleLocationData,
  AiGetVehicleLocationInput,
  AiGetVehicleLocationSource,
  AiGetVehicleTelemetryStatusData,
  AiGetVehicleTelemetryStatusInput,
  AiTelemetryStatusExplanation,
  AiGetVehicleHealthSummaryData,
  AiGetVehicleHealthSummaryDomains,
  AiHealthDomainSlice,
  AiGetVehicleHealthSummaryInput,
  AiExplainOverdueReturnData,
  AiExplainOverdueReturnInput,
  AiGetVehicleBookingContextData,
  AiGetVehicleBookingContextInput,
} from './tools';
export {
  AI_DOMAIN_TOOL_CACHE_POLICIES,
  AI_DOMAIN_TOOL_AUDIT_LEVELS,
  AI_DOMAIN_TOOL_PERSONAL_DATA,
  AI_DOMAIN_TOOL_REGISTRY_AUDIT_EVENTS,
  AI_DOMAIN_TOOL_DEFINITIONS,
  AI_DOMAIN_TOOL_DEFINITION_BY_NAME,
  isAiDomainToolName,
  validateAiDomainToolInput,
  buildAiDomainToolRegistryAuditPayload,
  assertNoProviderDetailsInOutcome,
  AiDomainToolRegistry,
  createAiDomainToolInvocationTracker,
} from './registry';
export {
  routeFleetChatMessage,
  validateFleetChatLlmClassification,
  FleetChatIntentRouterService,
  FLEET_CHAT_INTENTS,
} from './routing';
export { FleetChatOrchestratorService } from './chat/fleet-chat-orchestrator.service';
export type {
  FleetChatOrchestrateResult,
  FleetChatOrchestratorAudit,
  FleetChatOrchestratorPerformance,
} from './chat/fleet-chat-orchestrator.types';
export type {
  FleetChatIntent,
  FleetChatRouteResult,
  FleetChatClarification,
  FleetChatVehicleReference,
  FleetChatBookingReference,
  FleetChatSecurityFlag,
} from './routing';
export type {
  AiDomainToolCachePolicy,
  AiDomainToolAuditLevel,
  AiDomainToolPersonalData,
  AiDomainToolRegistryAuditEvent,
  AiDomainToolName,
  AiDomainToolSchemaField,
  AiDomainToolInputSchema,
  AiDomainToolOutputSchema,
  AiDomainToolPermissionRequirement,
  AiDomainToolCacheRule,
  AiDomainToolDefinition,
  AiDomainToolInvocationTracker,
  AiDomainToolExecuteOptions,
  AiDomainToolRegistryAuditPayload,
  AiDomainToolRegistryPreflightResult,
  AiDomainToolRegistryExecutor,
  AiDomainToolInputValidationIssue,
  AiDomainToolInputValidationResult,
} from './registry';
export type {
  StartAiTireSpecJobInput,
  AiTireSpecJobStatus,
  AiTireSpecApplyResult,
} from './vehicle-specs/ai-tire-spec-job.service';
