import { WORKFLOW_EVENT_TYPES } from '../workflow.constants';
import type { WorkflowActionTechnicalPolicy } from './workflow-action-policy.types';

const ALL_TRIGGERS = [...WORKFLOW_EVENT_TYPES] as const;

const VEHICLE_HEALTH_CRITICAL_TRIGGERS = [
  'vehicle.health.critical',
  'vehicle.dtc.critical',
] as const;

const BASE_TIMEOUT = { defaultMs: 120_000, maxMs: 600_000 };
const BASE_RETRY = { maxAttempts: 3, initialBackoffMs: 30_000, maxBackoffMs: 900_000 };

function policy(partial: WorkflowActionTechnicalPolicy): WorkflowActionTechnicalPolicy {
  return partial;
}

/**
 * Canonical server-side technical policy matrix.
 * Client/workflow definitions cannot downgrade these bindings.
 */
export const WORKFLOW_ACTION_POLICY_MATRIX: Record<string, WorkflowActionTechnicalPolicy> = {
  'task.create': policy({
    actionType: 'task.create',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_EXECUTE',
    approvalRule: 'NONE',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['booking', 'vehicle', 'customer', 'organization', '*'],
    allowedScopes: ['organization', 'vehicle', 'station'],
    timeout: BASE_TIMEOUT,
    retry: BASE_RETRY,
    maxAttempts: 3,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL'],
    auditLevel: 'STANDARD',
    retentionClass: 'STANDARD',
    dryRunAvailable: true,
    compensationPossible: false,
  }),

  'notification.in_app.send': policy({
    actionType: 'notification.in_app.send',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_EXECUTE',
    approvalRule: 'NONE',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['booking', 'vehicle', 'customer', 'organization', '*'],
    allowedScopes: ['organization', 'vehicle', 'station'],
    timeout: { defaultMs: 60_000, maxMs: 120_000 },
    retry: { maxAttempts: 2, initialBackoffMs: 15_000, maxBackoffMs: 120_000 },
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL', 'COMMUNICATION'],
    auditLevel: 'STANDARD',
    retentionClass: 'STANDARD',
    dryRunAvailable: true,
    compensationPossible: false,
  }),

  'approval.request': policy({
    actionType: 'approval.request',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_EXECUTE',
    approvalRule: 'GATE_ONLY',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: '*',
    allowedScopes: ['organization', 'vehicle', 'station'],
    timeout: { defaultMs: 30_000, maxMs: 60_000 },
    retry: { maxAttempts: 1, initialBackoffMs: 5_000, maxBackoffMs: 15_000 },
    maxAttempts: 1,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL'],
    auditLevel: 'DETAILED',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
  }),

  'workflow.approval.request': policy({
    actionType: 'workflow.approval.request',
    policyVersion: '2026-07-1',
    capabilityGate: 'DEPRECATED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_EXECUTE',
    approvalRule: 'GATE_ONLY',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: '*',
    allowedScopes: ['organization', 'vehicle', 'station'],
    timeout: { defaultMs: 30_000, maxMs: 60_000 },
    retry: { maxAttempts: 1, initialBackoffMs: 5_000, maxBackoffMs: 15_000 },
    maxAttempts: 1,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL'],
    auditLevel: 'DETAILED',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
  }),

  'booking.flag': policy({
    actionType: 'booking.flag',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_EXECUTE',
    approvalRule: 'NONE',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['booking', '*'],
    allowedScopes: ['organization', 'vehicle', 'station'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 2, initialBackoffMs: 15_000, maxBackoffMs: 60_000 },
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL', 'PII'],
    auditLevel: 'DETAILED',
    retentionClass: 'LONG',
    dryRunAvailable: true,
    compensationPossible: false,
    forbiddenTriggerCombinations: [
      { trigger: 'manual.test', reason: 'booking.flag is not allowed on manual.test trigger' },
    ],
  }),

  'vehicle.status.update': policy({
    actionType: 'vehicle.status.update',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'HIGH',
    requiredPermission: 'WORKFLOW_VEHICLE_WRITE',
    approvalRule: 'OPTIONAL',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['vehicle', 'booking', '*'],
    allowedScopes: ['organization', 'vehicle'],
    timeout: { defaultMs: 90_000, maxMs: 180_000 },
    retry: { maxAttempts: 2, initialBackoffMs: 15_000, maxBackoffMs: 60_000 },
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL', 'VEHICLE_TELEMETRY'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: true,
    highRiskSafeguards: [
      { code: 'TRANSITION_MATRIX', description: 'Only allowed VehicleStatus transitions' },
      { code: 'RENTAL_HEALTH_GATE', description: 'RentalHealthService blocks bypass to AVAILABLE' },
      { code: 'CONDITIONAL_APPROVAL', description: 'Sensitive transitions require explicit approval' },
    ],
  }),

  'alert.create': policy({
    actionType: 'alert.create',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_EXECUTE',
    approvalRule: 'NONE',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: '*',
    allowedScopes: ['organization', 'vehicle', 'station'],
    timeout: BASE_TIMEOUT,
    retry: BASE_RETRY,
    maxAttempts: 3,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL'],
    auditLevel: 'STANDARD',
    retentionClass: 'STANDARD',
    dryRunAvailable: true,
    compensationPossible: false,
  }),

  'notification.prepare': policy({
    actionType: 'notification.prepare',
    policyVersion: '2026-07-1',
    capabilityGate: 'DEPRECATED',
    riskClass: 'LOW',
    requiredPermission: 'WORKFLOW_EXECUTE',
    approvalRule: 'NONE',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: '*',
    allowedScopes: ['organization', 'vehicle', 'station'],
    timeout: BASE_TIMEOUT,
    retry: BASE_RETRY,
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL'],
    auditLevel: 'MINIMAL',
    retentionClass: 'SHORT',
    dryRunAvailable: true,
    compensationPossible: false,
  }),

  'ai.suggest_action': policy({
    actionType: 'ai.suggest_action',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'CRITICAL',
    requiredPermission: 'WORKFLOW_AI_SUGGEST',
    approvalRule: 'REQUIRED',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: '*',
    allowedScopes: ['organization'],
    timeout: { defaultMs: 180_000, maxMs: 300_000 },
    retry: { maxAttempts: 1, initialBackoffMs: 30_000, maxBackoffMs: 60_000 },
    maxAttempts: 1,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
    highRiskSafeguards: [
      { code: 'HUMAN_IN_LOOP', description: 'Never auto-execute AI suggestions' },
      { code: 'SUGGESTION_ONLY', description: 'Materializes review task only' },
    ],
  }),

  // ── Customer email (production adapter) ──

  'email.send': policy({
    actionType: 'email.send',
    policyVersion: '2026-07-2',
    capabilityGate: 'ENABLED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_CUSTOMER_CONTACT',
    approvalRule: 'REQUIRED',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['customer', 'booking'],
    allowedScopes: ['organization'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 2, initialBackoffMs: 30_000, maxBackoffMs: 120_000 },
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['COMMUNICATION', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
    prohibitUnverifiedDiagnosisOnTriggers: VEHICLE_HEALTH_CRITICAL_TRIGGERS,
    highRiskSafeguards: [
      { code: 'OPT_IN_REQUIRED', description: 'Customer communication consent required' },
      { code: 'SEND_WINDOW', description: 'Transactional sends respect org send window unless overridden' },
    ],
  }),

  // ── Customer WhatsApp (production adapters) ──

  'whatsapp.template.send': policy({
    actionType: 'whatsapp.template.send',
    policyVersion: '2026-07-1',
    capabilityGate: 'ENABLED',
    riskClass: 'HIGH',
    requiredPermission: 'WORKFLOW_CUSTOMER_CONTACT',
    approvalRule: 'REQUIRED',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['customer', 'booking'],
    allowedScopes: ['organization'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 2, initialBackoffMs: 30_000, maxBackoffMs: 120_000 },
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['COMMUNICATION', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
    prohibitUnverifiedDiagnosisOnTriggers: VEHICLE_HEALTH_CRITICAL_TRIGGERS,
    highRiskSafeguards: [
      { code: 'OPT_IN_REQUIRED', description: 'WhatsApp opt-in and channel consent required' },
      { code: 'QUIET_HOURS', description: 'Transactional sends respect org quiet hours unless overridden' },
      { code: 'RATE_LIMIT', description: 'Org and per-contact frequency limits enforced' },
      { code: 'TEMPLATE_APPROVED', description: 'Only approved template versions may be sent' },
    ],
  }),

  'whatsapp.ai_message.send': policy({
    actionType: 'whatsapp.ai_message.send',
    policyVersion: '2026-07-1',
    capabilityGate: 'DISABLED',
    riskClass: 'CRITICAL',
    requiredPermission: 'WORKFLOW_CUSTOMER_CONTACT',
    approvalRule: 'REQUIRED',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['customer', 'booking'],
    allowedScopes: ['organization'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 1, initialBackoffMs: 30_000, maxBackoffMs: 120_000 },
    maxAttempts: 1,
    fallbackCapable: false,
    dataCategories: ['COMMUNICATION', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
    prohibitUnverifiedDiagnosisOnTriggers: VEHICLE_HEALTH_CRITICAL_TRIGGERS,
    highRiskSafeguards: [
      { code: 'AI_PIPELINE_REQUIRED', description: 'Disabled until AI pipeline is production-ready' },
      { code: 'HUMAN_IN_LOOP', description: 'Sensitive AI flags require explicit approval' },
      { code: 'AI_TRANSPARENCY', description: 'AI transparency disclaimer appended to messages' },
      { code: 'SERVICE_WINDOW', description: 'Free-text only within 24h customer service window' },
    ],
  }),

  // ── Disabled future / external actions (policy defined, capability DISABLED) ──

  'customer.contact.email': policy({
    actionType: 'customer.contact.email',
    policyVersion: '2026-07-1',
    capabilityGate: 'DISABLED',
    riskClass: 'MEDIUM',
    requiredPermission: 'WORKFLOW_CUSTOMER_CONTACT',
    approvalRule: 'REQUIRED',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['customer', 'booking'],
    allowedScopes: ['organization'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 2, initialBackoffMs: 30_000, maxBackoffMs: 120_000 },
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['COMMUNICATION', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
    prohibitUnverifiedDiagnosisOnTriggers: VEHICLE_HEALTH_CRITICAL_TRIGGERS,
    highRiskSafeguards: [
      { code: 'OPT_IN_REQUIRED', description: 'Customer communication consent required' },
    ],
  }),

  'customer.contact.whatsapp': policy({
    actionType: 'customer.contact.whatsapp',
    policyVersion: '2026-07-1',
    capabilityGate: 'DISABLED',
    riskClass: 'HIGH',
    requiredPermission: 'WORKFLOW_CUSTOMER_CONTACT',
    approvalRule: 'REQUIRED',
    allowedTriggers: ALL_TRIGGERS,
    allowedEntityTypes: ['customer', 'booking'],
    allowedScopes: ['organization'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 2, initialBackoffMs: 30_000, maxBackoffMs: 120_000 },
    maxAttempts: 2,
    fallbackCapable: false,
    dataCategories: ['COMMUNICATION', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: false,
    prohibitUnverifiedDiagnosisOnTriggers: VEHICLE_HEALTH_CRITICAL_TRIGGERS,
    highRiskSafeguards: [
      { code: 'OPT_IN_REQUIRED', description: 'WhatsApp opt-in required' },
      { code: 'RATE_LIMIT', description: 'Outbound rate limits enforced' },
    ],
  }),

  'voice.call': policy({
    actionType: 'voice.call',
    policyVersion: '2026-07-1',
    capabilityGate: 'DISABLED',
    riskClass: 'HIGH',
    requiredPermission: 'WORKFLOW_VOICE_CALL',
    approvalRule: 'REQUIRED',
    allowedTriggers: ['customer.complaint.created', 'invoice.overdue'],
    allowedEntityTypes: ['customer', 'booking'],
    allowedScopes: ['organization'],
    timeout: { defaultMs: 300_000, maxMs: 600_000 },
    retry: { maxAttempts: 1, initialBackoffMs: 60_000, maxBackoffMs: 120_000 },
    maxAttempts: 1,
    fallbackCapable: false,
    dataCategories: ['COMMUNICATION', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: false,
    compensationPossible: false,
    highRiskSafeguards: [
      { code: 'BUDGET_GATE', description: 'Voice budget and protection policies' },
    ],
  }),

  'booking.cancel': policy({
    actionType: 'booking.cancel',
    policyVersion: '2026-07-1',
    capabilityGate: 'DISABLED',
    riskClass: 'CRITICAL',
    requiredPermission: 'WORKFLOW_BOOKING_CANCEL',
    approvalRule: 'REQUIRED',
    allowedTriggers: ['booking.returned', 'customer.complaint.created'],
    allowedEntityTypes: ['booking'],
    allowedScopes: ['organization'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 1, initialBackoffMs: 30_000, maxBackoffMs: 60_000 },
    maxAttempts: 1,
    fallbackCapable: false,
    dataCategories: ['OPERATIONAL', 'FINANCIAL', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: true,
    highRiskSafeguards: [
      { code: 'FINANCIAL_IMPACT', description: 'Cancellation fee and refund rules' },
      { code: 'DUAL_CONTROL', description: 'Requires explicit approval' },
    ],
  }),

  'invoice.charge': policy({
    actionType: 'invoice.charge',
    policyVersion: '2026-07-1',
    capabilityGate: 'DISABLED',
    riskClass: 'CRITICAL',
    requiredPermission: 'WORKFLOW_INVOICE_CHARGE',
    approvalRule: 'REQUIRED',
    allowedTriggers: ['invoice.overdue', 'booking.completed'],
    allowedEntityTypes: ['booking', 'customer'],
    allowedScopes: ['organization'],
    timeout: BASE_TIMEOUT,
    retry: { maxAttempts: 1, initialBackoffMs: 30_000, maxBackoffMs: 60_000 },
    maxAttempts: 1,
    fallbackCapable: false,
    dataCategories: ['FINANCIAL', 'PII'],
    auditLevel: 'FORENSIC',
    retentionClass: 'COMPLIANCE',
    dryRunAvailable: true,
    compensationPossible: true,
    highRiskSafeguards: [
      { code: 'PAYMENT_PROVIDER', description: 'Stripe/payment provider idempotency' },
      { code: 'DUAL_CONTROL', description: 'Requires explicit approval' },
    ],
  }),
};

export function getWorkflowActionPolicy(actionType: string): WorkflowActionTechnicalPolicy | undefined {
  return WORKFLOW_ACTION_POLICY_MATRIX[actionType];
}

export function listWorkflowActionPolicyTypes(): string[] {
  return Object.keys(WORKFLOW_ACTION_POLICY_MATRIX);
}
