export type P25ApdProfileInvalidationReason =
  | 'ACTIVITY'
  | 'TRIP_ACTIVE'
  | 'R9_WAKE'
  | 'DEVICE_RECONNECT'
  | 'PROVIDER_RECONNECT'
  | 'SOURCE_TIMESTAMP_MISSING'
  | 'PROVIDER_OBSERVABILITY_GAP'
  | 'EARLY_SOURCE_ADVANCE'
  | 'LATE_SOURCE_ADVANCE'
  | 'PHASE_DRIFT'
  | 'CAPABILITY_CHANGE'
  | 'INSUFFICIENT_RECENT_EVIDENCE';
