export const ERD_RECHARGE_PRODUCT_READ_DEDUPE_ENV_FLAG =
  'ERD_RECHARGE_PRODUCT_READ_DEDUPE_ENABLED';

export const ERD_RECHARGE_PRODUCT_READ_DEDUPE_EVIDENCE_VERSION =
  'erd_recharge_product_read_identity_v1';
