import {
  BusinessAuditAction,
  BUSINESS_AUDIT_ENTITY_TYPE,
  type BusinessAuditActionCode,
  type BusinessAuditEntityType,
} from '@modules/business-audit/business-audit.constants';

/** Retention recommendation for evaluations audit events (ActivityLog + outbox). */
export const EVALUATIONS_AUDIT_RETENTION_DAYS = 730;

export const EvaluationsAuditAction = {
  SENSITIVE_DETAIL_ACCESSED: BusinessAuditAction.EVALUATIONS_SENSITIVE_DETAIL_ACCESSED,
  FINANCE_EXPORT: BusinessAuditAction.EVALUATIONS_FINANCE_EXPORT,
  PII_DATA_ACCESSED: BusinessAuditAction.EVALUATIONS_PII_DATA_ACCESSED,
  RECOMMENDATION_CHANGED: BusinessAuditAction.EVALUATIONS_RECOMMENDATION_CHANGED,
  ASSIGNEE_CHANGED: BusinessAuditAction.EVALUATIONS_ASSIGNEE_CHANGED,
  STATUS_CHANGED: BusinessAuditAction.EVALUATIONS_STATUS_CHANGED,
  KPI_DEFINITION_CHANGED: BusinessAuditAction.EVALUATIONS_KPI_DEFINITION_CHANGED,
  FORECAST_MODEL_CHANGED: BusinessAuditAction.EVALUATIONS_FORECAST_MODEL_CHANGED,
  THRESHOLD_CHANGED: BusinessAuditAction.EVALUATIONS_THRESHOLD_CHANGED,
  MANUAL_RECALCULATION: BusinessAuditAction.EVALUATIONS_MANUAL_RECALCULATION,
  MODEL_ACTIVATED: BusinessAuditAction.EVALUATIONS_MODEL_ACTIVATED,
  MODEL_DEACTIVATED: BusinessAuditAction.EVALUATIONS_MODEL_DEACTIVATED,
  DATA_QUALITY_ACTION: BusinessAuditAction.EVALUATIONS_DATA_QUALITY_ACTION,
  ACCESS_DENIED: BusinessAuditAction.EVALUATIONS_ACCESS_DENIED,
} as const satisfies Record<string, BusinessAuditActionCode>;

export type EvaluationsAuditActionCode =
  (typeof EvaluationsAuditAction)[keyof typeof EvaluationsAuditAction];

export const EVALUATIONS_AUDIT_ENTITY_TYPE = {
  EXPORT: BUSINESS_AUDIT_ENTITY_TYPE.EVALUATIONS_EXPORT,
  MISUSE_CASE: BUSINESS_AUDIT_ENTITY_TYPE.EVALUATIONS_MISUSE_CASE,
  INSIGHT_POLICY: BUSINESS_AUDIT_ENTITY_TYPE.EVALUATIONS_INSIGHT_POLICY,
  MODEL_REGISTRY: BUSINESS_AUDIT_ENTITY_TYPE.EVALUATIONS_MODEL_REGISTRY,
  FORECAST_RUN: BUSINESS_AUDIT_ENTITY_TYPE.EVALUATIONS_FORECAST_RUN,
  CUSTOMER_LABELS: BUSINESS_AUDIT_ENTITY_TYPE.EVALUATIONS_CUSTOMER_LABELS,
  ADMIN_DIAGNOSTICS: BUSINESS_AUDIT_ENTITY_TYPE.EVALUATIONS_ADMIN_DIAGNOSTICS,
} as const satisfies Record<string, BusinessAuditEntityType>;

export type EvaluationsAuditEntityType =
  (typeof EVALUATIONS_AUDIT_ENTITY_TYPE)[keyof typeof EVALUATIONS_AUDIT_ENTITY_TYPE];

export type EvaluationsAuditOutcome = 'SUCCESS' | 'DENIED' | 'FAILED';
