import {
  OVERDUE_RETURN_EXTENSION_STATUS,
  OVERDUE_RETURN_HANDOVER_STATUS,
  OVERDUE_RETURN_RETURN_STATUS,
} from '@modules/bookings/overdue-return/overdue-return-explanation.constants';

export {
  OVERDUE_RETURN_EXTENSION_STATUS as VEHICLE_BOOKING_EXTENSION_STATUS,
  OVERDUE_RETURN_HANDOVER_STATUS as VEHICLE_BOOKING_HANDOVER_STATUS,
  OVERDUE_RETURN_RETURN_STATUS as VEHICLE_BOOKING_RETURN_STATUS,
};

export const VEHICLE_BOOKING_CONTEXT_KIND = {
  ACTIVE_RENTED: 'ACTIVE_RENTED',
  RESERVED: 'RESERVED',
  UPCOMING: 'UPCOMING',
  NONE: 'NONE',
} as const;

export type VehicleBookingContextKind =
  (typeof VEHICLE_BOOKING_CONTEXT_KIND)[keyof typeof VEHICLE_BOOKING_CONTEXT_KIND];

export const VEHICLE_BOOKING_CONTEXT_BUCKET = {
  CURRENT: 'CURRENT',
  RESERVED: 'RESERVED',
  UPCOMING: 'UPCOMING',
} as const;

export type VehicleBookingContextBucket =
  (typeof VEHICLE_BOOKING_CONTEXT_BUCKET)[keyof typeof VEHICLE_BOOKING_CONTEXT_BUCKET];

export const VEHICLE_BOOKING_PROCESS_STEP = {
  PICKUP_HANDOVER_PENDING: 'PICKUP_HANDOVER_PENDING',
  RETURN_HANDOVER_PENDING: 'RETURN_HANDOVER_PENDING',
  PICKUP_OVERDUE: 'PICKUP_OVERDUE',
  RETURN_OVERDUE: 'RETURN_OVERDUE',
} as const;

export type VehicleBookingProcessStep =
  (typeof VEHICLE_BOOKING_PROCESS_STEP)[keyof typeof VEHICLE_BOOKING_PROCESS_STEP];

export const VEHICLE_BOOKING_CONTEXT_REASON_CODE = {
  ACTIVE_RENTED: 'ACTIVE_RENTED',
  RESERVED_WINDOW: 'RESERVED_WINDOW',
  UPCOMING_BOOKING: 'UPCOMING_BOOKING',
  NO_OPEN_BOOKING: 'NO_OPEN_BOOKING',
  PICKUP_OVERDUE: 'PICKUP_OVERDUE',
  RETURN_OVERDUE: 'RETURN_OVERDUE',
  RETURN_HANDOVER_PENDING: 'RETURN_HANDOVER_PENDING',
  PICKUP_HANDOVER_PENDING: 'PICKUP_HANDOVER_PENDING',
  EXTENSION_APPLIED: 'EXTENSION_APPLIED',
  RETURN_COMPLETED: 'RETURN_COMPLETED',
  MULTIPLE_ACTIVE_BOOKINGS: 'MULTIPLE_ACTIVE_BOOKINGS',
  RETURN_COMPLETED_BOOKING_STILL_ACTIVE: 'RETURN_COMPLETED_BOOKING_STILL_ACTIVE',
  GHOST_OPERATIONAL_STATE: 'GHOST_OPERATIONAL_STATE',
} as const;

export type VehicleBookingContextReasonCode =
  (typeof VEHICLE_BOOKING_CONTEXT_REASON_CODE)[keyof typeof VEHICLE_BOOKING_CONTEXT_REASON_CODE];

export const VEHICLE_BOOKING_INCONSISTENCY_FLAG = {
  MULTIPLE_ACTIVE_BOOKINGS: 'MULTIPLE_ACTIVE_BOOKINGS',
  RETURN_COMPLETED_BOOKING_STILL_ACTIVE: 'RETURN_COMPLETED_BOOKING_STILL_ACTIVE',
  RETURN_PROTOCOL_EXISTS_BUT_MARKED_OVERDUE: 'RETURN_PROTOCOL_EXISTS_BUT_MARKED_OVERDUE',
  FLEET_CONTEXT_LOAD_FAILED: 'FLEET_CONTEXT_LOAD_FAILED',
} as const;

export type VehicleBookingInconsistencyFlag =
  (typeof VEHICLE_BOOKING_INCONSISTENCY_FLAG)[keyof typeof VEHICLE_BOOKING_INCONSISTENCY_FLAG];

export const VEHICLE_BOOKING_DEADLINE_KIND = {
  PICKUP: 'PICKUP',
  RETURN: 'RETURN',
} as const;

export type VehicleBookingDeadlineKind =
  (typeof VEHICLE_BOOKING_DEADLINE_KIND)[keyof typeof VEHICLE_BOOKING_DEADLINE_KIND];
