/** Canonical return-overdue grace for dashboard tiles and fleet booking context — 0 min (immediate at endDate). */
export const BOOKING_RETURN_OVERDUE_GRACE_PERIOD_MINUTES = 0;

export const OVERDUE_RETURN_REASON_CODE = {
  RETURN_DEADLINE_PASSED: 'RETURN_DEADLINE_PASSED',
  GRACE_PERIOD_EXCEEDED: 'GRACE_PERIOD_EXCEEDED',
  RETURN_NOT_COMPLETED: 'RETURN_NOT_COMPLETED',
  NO_APPROVED_EXTENSION: 'NO_APPROVED_EXTENSION',
  HANDOVER_STILL_ACTIVE: 'HANDOVER_STILL_ACTIVE',
  STATUS_WITHOUT_ACTIVE_BOOKING: 'STATUS_WITHOUT_ACTIVE_BOOKING',
  RETURN_COMPLETED_BUT_RUNTIME_STALE: 'RETURN_COMPLETED_BUT_RUNTIME_STALE',
  BOOKING_CANCELLED_BUT_MARKED_OVERDUE: 'BOOKING_CANCELLED_BUT_MARKED_OVERDUE',
  FLEET_CONTEXT_DIVERGENCE: 'FLEET_CONTEXT_DIVERGENCE',
  RETURN_NOT_DUE_YET: 'RETURN_NOT_DUE_YET',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
} as const;

export type OverdueReturnReasonCode =
  (typeof OVERDUE_RETURN_REASON_CODE)[keyof typeof OVERDUE_RETURN_REASON_CODE];

export const OVERDUE_RETURN_INCONSISTENCY_FLAG = {
  RETURN_PROTOCOL_EXISTS_BUT_MARKED_OVERDUE: 'RETURN_PROTOCOL_EXISTS_BUT_MARKED_OVERDUE',
  FLEET_ACTIVE_IS_OVERDUE_DIVERGENCE: 'FLEET_ACTIVE_IS_OVERDUE_DIVERGENCE',
  RETURN_COMPLETED_BOOKING_STILL_ACTIVE: 'RETURN_COMPLETED_BOOKING_STILL_ACTIVE',
  CANCELLED_BOOKING_MARKED_OVERDUE: 'CANCELLED_BOOKING_MARKED_OVERDUE',
  STATUS_WITHOUT_ACTIVE_BOOKING: 'STATUS_WITHOUT_ACTIVE_BOOKING',
  HISTORICAL_BOOKING_NOT_CURRENT: 'HISTORICAL_BOOKING_NOT_CURRENT',
} as const;

export type OverdueReturnInconsistencyFlag =
  (typeof OVERDUE_RETURN_INCONSISTENCY_FLAG)[keyof typeof OVERDUE_RETURN_INCONSISTENCY_FLAG];

export const OVERDUE_RETURN_EXTENSION_STATUS = {
  NONE: 'NONE',
  APPLIED_VIA_END_DATE_PATCH: 'APPLIED_VIA_END_DATE_PATCH',
  UNKNOWN: 'UNKNOWN',
} as const;

export type OverdueReturnExtensionStatus =
  (typeof OVERDUE_RETURN_EXTENSION_STATUS)[keyof typeof OVERDUE_RETURN_EXTENSION_STATUS];

export const OVERDUE_RETURN_HANDOVER_STATUS = {
  NOT_STARTED: 'NOT_STARTED',
  PICKUP_COMPLETED: 'PICKUP_COMPLETED',
  RETURN_COMPLETED: 'RETURN_COMPLETED',
} as const;

export type OverdueReturnHandoverStatus =
  (typeof OVERDUE_RETURN_HANDOVER_STATUS)[keyof typeof OVERDUE_RETURN_HANDOVER_STATUS];

export const OVERDUE_RETURN_RETURN_STATUS = {
  PENDING: 'PENDING',
  COMPLETED: 'COMPLETED',
  NOT_APPLICABLE: 'NOT_APPLICABLE',
} as const;

export type OverdueReturnReturnStatus =
  (typeof OVERDUE_RETURN_RETURN_STATUS)[keyof typeof OVERDUE_RETURN_RETURN_STATUS];
