import {
  DRIVING_BEHAVIOR_DATA_CATEGORY,
  DRIVING_BEHAVIOR_PATH,
  DRIVING_BEHAVIOR_PURPOSE,
  DRIVING_BEHAVIOR_SERVICE_IDENTITY,
} from '../driving-behavior-enforcement/driving-behavior-enforcement.constants';
import {
  VEHICLE_HEALTH_DATA_CATEGORY,
  VEHICLE_HEALTH_PATH,
  VEHICLE_HEALTH_PURPOSE,
  VEHICLE_HEALTH_SERVICE_IDENTITY,
} from '../vehicle-health-enforcement/vehicle-health-enforcement.constants';
import { TELEMETRY_INGEST_DATA_CATEGORY, TELEMETRY_INGEST_PURPOSE } from '../telemetry-ingestion-enforcement/telemetry-ingestion-enforcement.constants';
import {
  NOTIFICATION_ENFORCEMENT_PATH,
  NOTIFICATION_ENFORCEMENT_SERVICE_IDENTITY,
  NOTIFICATION_GATE_KIND,
} from './notification-enforcement.constants';
import type { NotificationAuthGateSpec } from './notification-enforcement.types';

const OPERATIONAL: NotificationAuthGateSpec = {
  gateKind: NOTIFICATION_GATE_KIND.OPERATIONAL,
  processingPath: NOTIFICATION_ENFORCEMENT_PATH.NOTIFICATION_INGEST,
  serviceIdentity: NOTIFICATION_ENFORCEMENT_SERVICE_IDENTITY.NOTIFICATION_CORE,
};

const TECHNICAL_MONITORING: NotificationAuthGateSpec = {
  gateKind: NOTIFICATION_GATE_KIND.TECHNICAL_MONITORING,
  processingPath: NOTIFICATION_ENFORCEMENT_PATH.NOTIFICATION_INGEST,
  serviceIdentity: NOTIFICATION_ENFORCEMENT_SERVICE_IDENTITY.NOTIFICATION_CORE,
};

const HEALTH_DTC: NotificationAuthGateSpec = {
  gateKind: NOTIFICATION_GATE_KIND.HEALTH_ALERT,
  dataCategory: VEHICLE_HEALTH_DATA_CATEGORY.DTC_CODES,
  purpose: VEHICLE_HEALTH_PURPOSE.ALERTS,
  processingPath: VEHICLE_HEALTH_PATH.BRAKE_ALERT,
  serviceIdentity: VEHICLE_HEALTH_SERVICE_IDENTITY.HEALTH_ALERT,
  sensitivePreviewParams: ['dtcCode', 'dtcDescription', 'faultCode'],
};

const HEALTH_SIGNAL: NotificationAuthGateSpec = {
  gateKind: NOTIFICATION_GATE_KIND.HEALTH_ALERT,
  dataCategory: VEHICLE_HEALTH_DATA_CATEGORY.HEALTH_SIGNALS,
  purpose: VEHICLE_HEALTH_PURPOSE.ALERTS,
  processingPath: VEHICLE_HEALTH_PATH.BRAKE_ALERT,
  serviceIdentity: VEHICLE_HEALTH_SERVICE_IDENTITY.HEALTH_ALERT,
  sensitivePreviewParams: ['wearPct', 'voltage', 'treadDepth', 'padThickness'],
};

const DRIVING_TECHNICAL: NotificationAuthGateSpec = {
  gateKind: NOTIFICATION_GATE_KIND.DRIVING_ALERT,
  dataCategory: DRIVING_BEHAVIOR_DATA_CATEGORY.DRIVING_BEHAVIOR,
  purpose: DRIVING_BEHAVIOR_PURPOSE.TECHNICAL_EVENT_DETECTION,
  processingPath: DRIVING_BEHAVIOR_PATH.BEHAVIOR_NOTIFY,
  serviceIdentity: DRIVING_BEHAVIOR_SERVICE_IDENTITY.BEHAVIOR_NOTIFY,
  sensitivePreviewParams: ['eventCount', 'severityScore', 'tripId'],
};

const DRIVING_MISUSE: NotificationAuthGateSpec = {
  gateKind: NOTIFICATION_GATE_KIND.DRIVING_ALERT,
  dataCategory: DRIVING_BEHAVIOR_DATA_CATEGORY.DRIVING_BEHAVIOR,
  purpose: DRIVING_BEHAVIOR_PURPOSE.MISUSE_DETECTION,
  processingPath: DRIVING_BEHAVIOR_PATH.BEHAVIOR_NOTIFY,
  serviceIdentity: DRIVING_BEHAVIOR_SERVICE_IDENTITY.BEHAVIOR_NOTIFY,
  sensitivePreviewParams: ['misuseType', 'evidenceCount', 'tripId', 'driverName'],
};

const CONNECTIVITY: NotificationAuthGateSpec = {
  gateKind: NOTIFICATION_GATE_KIND.CONNECTIVITY_ALERT,
  dataCategory: TELEMETRY_INGEST_DATA_CATEGORY.GPS_LOCATION,
  purpose: TELEMETRY_INGEST_PURPOSE.ALERTS,
  processingPath: NOTIFICATION_ENFORCEMENT_PATH.CONNECTIVITY_NOTIFY,
  serviceIdentity: NOTIFICATION_ENFORCEMENT_SERVICE_IDENTITY.CONNECTIVITY_NOTIFY,
  sensitivePreviewParams: ['lastLat', 'lastLng', 'lastPosition', 'coordinates'],
};

/** Event-type → authorization gate specification. */
export const NOTIFICATION_EVENT_AUTH_REGISTRY: Readonly<Record<string, NotificationAuthGateSpec>> = {
  // Operations / bookings — tenant scope only
  STATION_SHORTAGE: OPERATIONAL,
  PICKUP_OVERDUE: OPERATIONAL,
  RETURN_OVERDUE: OPERATIONAL,
  BLOCKED_VEHICLE: OPERATIONAL,
  VEHICLE_NOT_READY: OPERATIONAL,
  MAINTENANCE_REQUIRED: OPERATIONAL,
  COMPLIANCE_EXPIRED: OPERATIONAL,
  SERVICE_OVERDUE: OPERATIONAL,
  TIGHT_HANDOVER: OPERATIONAL,
  RETURN_NEEDS_INSPECTION: OPERATIONAL,
  LOW_UTILIZATION: OPERATIONAL,
  SERVICE_WINDOW: OPERATIONAL,
  SERVICE_BEFORE_BOOKING: OPERATIONAL,
  TUV_OVERDUE: OPERATIONAL,
  BOKRAFT_OVERDUE: OPERATIONAL,
  HM_SERVICE_NO_TRACKING: OPERATIONAL,
  BOOKING_CREATED: OPERATIONAL,
  BOOKING_UPDATED: OPERATIONAL,
  PICKUP_DUE: OPERATIONAL,
  RETURN_DUE: OPERATIONAL,
  HANDOVER_INCOMPLETE: OPERATIONAL,
  REQUIRED_DOCUMENT_MISSING: OPERATIONAL,
  PAYMENT_FAILED: OPERATIONAL,
  INVOICE_OVERDUE: OPERATIONAL,
  DEPOSIT_PROBLEM: OPERATIONAL,

  // Technical monitoring — separate from user privacy notifications
  INTEGRATION_DISCONNECTED: TECHNICAL_MONITORING,
  WEBHOOK_FAILURE: TECHNICAL_MONITORING,
  CONNECTIVITY_STATE_UNKNOWN: TECHNICAL_MONITORING,

  // Health alerts
  ACTIVE_DTC: HEALTH_DTC,
  BATTERY_CRITICAL: HEALTH_SIGNAL,
  TIRE_CRITICAL: HEALTH_SIGNAL,
  BRAKE_CRITICAL: HEALTH_SIGNAL,
  TECHNICAL_OBSERVATION_ACTIVE: {
    ...HEALTH_SIGNAL,
    processingPath: VEHICLE_HEALTH_PATH.MANUAL_OBSERVATION,
  },

  // Driving behavior
  DRIVING_ASSESSMENT_DEVICE_QUALITY: DRIVING_TECHNICAL,
  TRIP_ANALYSIS_COMPLETED: {
    ...DRIVING_TECHNICAL,
    purpose: DRIVING_BEHAVIOR_PURPOSE.FLEET_OPERATIONS,
  },
  DATA_QUALITY_LIMITED: DRIVING_TECHNICAL,
  MISUSE_DETECTED: DRIVING_MISUSE,
  POSSIBLE_IMPACT: {
    ...DRIVING_MISUSE,
    purpose: DRIVING_BEHAVIOR_PURPOSE.DAMAGE_SUSPECT,
  },

  // Connectivity / GPS / offline
  TELEMETRY_OFFLINE: CONNECTIVITY,
  TELEMETRY_SOFT_OFFLINE: CONNECTIVITY,
  DEVICE_UNPLUGGED: CONNECTIVITY,
  DEVICE_RECONNECTED: CONNECTIVITY,
  AUTHORIZATION_REQUIRED: CONNECTIVITY,
  DATA_SOURCE_DISCONNECTED: CONNECTIVITY,
  DATA_COVERAGE_INSUFFICIENT: CONNECTIVITY,
  DEVICE_BINDING_CHANGED: CONNECTIVITY,
};

export function resolveNotificationAuthGate(eventType: string): NotificationAuthGateSpec {
  return (
    NOTIFICATION_EVENT_AUTH_REGISTRY[eventType] ?? {
      gateKind: NOTIFICATION_GATE_KIND.OPERATIONAL,
      processingPath: NOTIFICATION_ENFORCEMENT_PATH.NOTIFICATION_INGEST,
      serviceIdentity: NOTIFICATION_ENFORCEMENT_SERVICE_IDENTITY.NOTIFICATION_CORE,
    }
  );
}

export function listEventTypesForGateKind(gateKind: string): string[] {
  return Object.entries(NOTIFICATION_EVENT_AUTH_REGISTRY)
    .filter(([, spec]) => spec.gateKind === gateKind)
    .map(([eventType]) => eventType);
}

export function listEventTypesForDataCategory(dataCategory: string): string[] {
  return Object.entries(NOTIFICATION_EVENT_AUTH_REGISTRY)
    .filter(([, spec]) => spec.dataCategory === dataCategory)
    .map(([eventType]) => eventType);
}
