/** Master Admin presentation island (C5B) — not product i18n Integration 2. */
const COPY: Record<string, string> = {
  'master.batteryV2Shadow.pageTitle': 'Battery V2 shadow inspection',
  'master.batteryV2Shadow.pageDescription':
    'Read-only Master Admin view over M3_3C_C5A_V1 — internal engineering inspection, not customer health UI (M3.3H).',
  'master.batteryV2Shadow.refreshAria': 'Refresh inspection',
  'master.batteryV2Shadow.targetSelection': 'Target selection',
  'master.batteryV2Shadow.organization': 'Organization',
  'master.batteryV2Shadow.selectOrganization': 'Select organization…',
  'master.batteryV2Shadow.vehicle': 'Vehicle',
  'master.batteryV2Shadow.filterVehiclePlaceholder': 'Filter plate / VIN / make…',
  'master.batteryV2Shadow.selectVehicle': 'Select vehicle…',
  'master.batteryV2Shadow.restSession': 'Rest session',
  'master.batteryV2Shadow.selectRestSession': 'Select rest session…',
  'master.batteryV2Shadow.emptyNoVehicleTitle': 'No vehicle selected',
  'master.batteryV2Shadow.emptyNoVehicleDescription':
    'Choose an organization and vehicle to load Battery V2 rest-session inspection data.',
  'master.batteryV2Shadow.emptyNoSessionTitle': 'No rest session selected',
  'master.batteryV2Shadow.emptyNoSessionsFound': 'No rest sessions found for this vehicle.',
  'master.batteryV2Shadow.emptySelectSession': 'Select a rest session to inspect.',
  'master.batteryV2Shadow.errorInspectionTitle': 'Inspection failed',
  'master.batteryV2Shadow.errorUnknown': 'Unknown error',
  'master.batteryV2Shadow.errorSessionsLoad': 'Rest sessions could not be loaded.',
  'master.batteryV2Shadow.errorInspectionRequest': 'Inspection request failed.',
  'master.batteryV2Shadow.integrityPrefix': 'Integrity:',
  'master.batteryV2Shadow.sessionIdentity': 'Session identity',
  'master.batteryV2Shadow.canonicalState': 'Canonical state',
  'master.batteryV2Shadow.canonicalFeatureTitle': 'Canonical feature (C5A)',
  'master.batteryV2Shadow.chargeContextTitle': 'Charge context (canonical, C5A raw)',
  'master.batteryV2Shadow.revisionHistoryTitle': 'Revision history (visible window: {{count}})',
  'master.batteryV2Shadow.digestIntegrityTitle': 'Digest / revision integrity',
  'master.batteryV2Shadow.metric.vehicle': 'Vehicle',
  'master.batteryV2Shadow.metric.sessionStatus': 'Session status',
  'master.batteryV2Shadow.metric.anchor': 'Anchor',
  'master.batteryV2Shadow.metric.endReason': 'End reason',
  'master.batteryV2Shadow.metric.restObservations': 'Rest observations',
  'master.batteryV2Shadow.metric.sessionId': 'Session id',
  'master.batteryV2Shadow.metric.canonicalRevision': 'Canonical revision',
  'master.batteryV2Shadow.metric.canonicalRowId': 'Canonical row id',
  'master.batteryV2Shadow.metric.selection': 'Selection',
  'master.batteryV2Shadow.metric.latestSemanticRev': 'Latest semantic rev',
  'master.batteryV2Shadow.metric.totalFeatureRows': 'Total feature rows',
  'master.batteryV2Shadow.metric.windowTruncated': 'Window truncated',
  'master.batteryV2Shadow.metric.countAggregateConsistent': 'Count/aggregate consistent',
  'master.batteryV2Shadow.metric.shutdownRestDelta': 'Shutdown → first rest Δ',
  'master.batteryV2Shadow.metric.theilSenSlope': 'Theil-Sen slope',
  'master.batteryV2Shadow.metric.medianRestV': 'Median rest V',
  'master.batteryV2Shadow.metric.validRestPoints': 'Valid rest points',
  'master.batteryV2Shadow.metric.minRestV': 'Min rest V',
  'master.batteryV2Shadow.metric.maxRestV': 'Max rest V',
  'master.batteryV2Shadow.metric.variance': 'Variance mV²',
  'master.batteryV2Shadow.metric.missingRungs': 'Missing rungs',
  'master.batteryV2Shadow.metric.chargeClass': 'Charge class',
  'master.batteryV2Shadow.metric.observationSpan': 'Observation span',
  'master.batteryV2Shadow.metric.semanticGaps': 'Semantic gaps',
  'master.batteryV2Shadow.metric.duplicateRevisions': 'Duplicate revisions',
  'master.batteryV2Shadow.metric.uncheckedRows': 'Unchecked rows',
  'master.batteryV2Shadow.metric.versionTuple': 'Version tuple',
  'master.batteryV2Shadow.retentionCurveNote':
    'Retention curve points (from C5A inputSummary): {{count}} eligible retention point(s) — values not recomputed in UI.',
  'master.batteryV2Shadow.retentionSectionTitle': 'Retention curve (C5A inputSummary.retentionPoints)',
  'master.batteryV2Shadow.retentionEmpty': 'No retention points in C5A inputSummary for this revision.',
  'master.batteryV2Shadow.retentionCol.index': '#',
  'master.batteryV2Shadow.retentionCol.observation': 'Observation',
  'master.batteryV2Shadow.retentionCol.restAge': 'actualRestAgeMs',
  'master.batteryV2Shadow.retentionCol.voltage': 'voltageMv',
  'master.batteryV2Shadow.retentionCol.rung': 'nominalRung',
  'master.batteryV2Shadow.retentionCol.evidence': 'evidenceClass',
  'master.batteryV2Shadow.table.rev': 'Rev',
  'master.batteryV2Shadow.table.phase': 'Phase',
  'master.batteryV2Shadow.table.trust': 'Trust',
  'master.batteryV2Shadow.table.digest': 'Digest',
  'master.batteryV2Shadow.table.slope': 'Slope',
  'master.batteryV2Shadow.table.canonical': 'Canonical',
  'master.batteryV2Shadow.yesLatest100': 'yes (latest 100)',
  'master.batteryV2Shadow.yes': 'yes',
  'master.batteryV2Shadow.no': 'no',
  'master.batteryV2Shadow.canonicalTag': 'canonical',
  'master.batteryV2Shadow.digestValid': 'valid',
  'master.batteryV2Shadow.digestMismatch': 'MISMATCH',
};

export function resolveBatteryV2ShadowCopy(key: string, params?: Record<string, string | number>): string {
  let text = COPY[key] ?? key;
  if (params) {
    for (const [k, v] of Object.entries(params)) {
      text = text.replace(`{{${k}}}`, String(v));
    }
  }
  return text;
}
