#!/usr/bin/env bash
# Read-only CONFIG-FILE evidence for DIMO_GLOBAL_BUDGET_ENABLED (Tiny Activation).
# Does not inspect PM2 processes, logs, or live runtime env — see EXP021_S4F3 evidence doc.
set -euo pipefail

ENV_PATH="${SYNQDRIVE_BACKEND_ENV:-/opt/synqdrive/shared/backend.env}"

CONFIG_EXPLICITLY_DEFINED=NO
CONFIG_NORMALIZED_VALUE=UNKNOWN
CONFIG_FILE_STATE=MISSING
PROVIDER_EVIDENCE_SOURCE=shared_backend_env_file

echo "EVIDENCE_SCOPE=CONFIG_FILE_ONLY"
echo "ACTIVE_RUNTIME_CONFIRMATION=NOT_PERFORMED"
echo "GLOBAL_BUDGET_ACTIVE_RUNTIME_STATE=UNVERIFIED"
echo "FILE_AUDIT_CAN_ALONE_SATISFY_TINY_GATE=NO"
echo "AUDIT_BACKEND_ENV_PATH=${ENV_PATH}"
echo "DIMO_GLOBAL_BUDGET_CONFIG_SOURCE=shared_backend_env_file"

if [[ ! -r "${ENV_PATH}" ]]; then
  CONFIG_EXPLICITLY_DEFINED=NO
  CONFIG_NORMALIZED_VALUE=UNKNOWN
  CONFIG_FILE_STATE=UNREADABLE
  PROVIDER_EVIDENCE_SOURCE=backend_env_file_missing_or_unreadable
else
  if grep -q '^DIMO_GLOBAL_BUDGET_ENABLED=' "${ENV_PATH}"; then
    CONFIG_EXPLICITLY_DEFINED=YES
    RAW="$(grep '^DIMO_GLOBAL_BUDGET_ENABLED=' "${ENV_PATH}" | tail -1 | cut -d= -f2-)"
    case "$(echo "${RAW}" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')" in
      true | 1 | yes | on)
        CONFIG_NORMALIZED_VALUE=ENABLED
        CONFIG_FILE_STATE=EXPLICIT_ENABLED
        ;;
      false | 0 | no | off)
        CONFIG_NORMALIZED_VALUE=DISABLED
        CONFIG_FILE_STATE=EXPLICIT_DISABLED
        ;;
      *)
        CONFIG_NORMALIZED_VALUE=UNKNOWN
        CONFIG_FILE_STATE=MALFORMED
        ;;
    esac
  else
    CONFIG_EXPLICITLY_DEFINED=NO
    CONFIG_NORMALIZED_VALUE=UNKNOWN
    CONFIG_FILE_STATE=MISSING
  fi
fi

echo "GLOBAL_BUDGET_CONFIG_FILE_STATE=${CONFIG_FILE_STATE}"
echo "DIMO_GLOBAL_BUDGET_CONFIG_EXPLICITLY_DEFINED=${CONFIG_EXPLICITLY_DEFINED}"
echo "DIMO_GLOBAL_BUDGET_CONFIG_NORMALIZED_VALUE=${CONFIG_NORMALIZED_VALUE}"

# Legacy aliases — same shell state as canonical (CONFIG_FILE scope only).
echo "DIMO_GLOBAL_BUDGET_ENV_EXPLICITLY_DEFINED=${CONFIG_EXPLICITLY_DEFINED}"
echo "DIMO_GLOBAL_BUDGET_ENV_NORMALIZED_VALUE=${CONFIG_NORMALIZED_VALUE}"
echo "LEGACY_ALIAS_MATCHES_CANONICAL=YES"

echo "PROVIDER_GLOBAL_BUDGET_EVIDENCE_SOURCE=${PROVIDER_EVIDENCE_SOURCE}"
echo "GENERIC_DIMO_CONFIG_DEFAULT_TRUE_IS_NOT_TINY_ACTIVATION_EVIDENCE=YES"
echo "EFFECTIVE_RUNTIME_DEFAULT_BEHAVIOR=ENABLED_BY_DEFAULT_IF_UNSET_IN_NEST_CONFIG"
echo "TINY_ACTIVATION_EXPLICIT_CONFIG_EVIDENCE=REQUIRES_EXPLICIT_CONFIG_AND_POST_MUTATION_RUNTIME_PROOF"
