#!/usr/bin/env bash
# EXP-021 S4F-7F — guarded Production GLOBAL kill row initializer wrapper (di_v0_s4_control only).
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
S4F7F_SCRIPT_DIR="$SCRIPT_DIR"
export S4F7F_SCRIPT_DIR

# shellcheck source=vps-production-replica-topology.config.sh
source "${SCRIPT_DIR}/vps-production-replica-topology.config.sh"
# shellcheck source=lib/vps-production-replica.lib.sh
source "${SCRIPT_DIR}/lib/vps-production-replica.lib.sh"
# shellcheck source=lib/di-v0-s4-global-kill-init-production.lib.sh
source "${SCRIPT_DIR}/lib/di-v0-s4-global-kill-init-production.lib.sh"

BACKEND_ENV="${SYNQDRIVE_BACKEND_ENV:-/opt/synqdrive/shared/backend.env}"
DRY_RUN="${DRY_RUN:-0}"
INITIALIZER_INVOKED=NO
PRODUCTION_DB_WRITE_OCCURRED=NO
FAIL_CLOSED=NO

echo "EXP021_S4F7F_PRODUCTION_KILL_INITIALIZER_WRAPPER=1"
echo "ENV_MUTATION_SUPPORTED=NO"
echo "PM2_RESTART_SUPPORTED=NO"
echo "CODE_DEPLOY_SUPPORTED=NO"
echo "ARBITRARY_DB_MUTATION_SUPPORTED=NO"
echo "ONLY_GLOBAL_KILLED_INIT_SUPPORTED=YES"
echo "WRAPPER_PATH=${SCRIPT_DIR}/di-v0-s4-initialize-global-kill-row-production.sh"
echo "OPERATOR_ACK_REQUIRED=YES"
echo "DRY_RUN_SUPPORTED=YES"

s4f7f_fail() {
  local reason="$1"
  FAIL_CLOSED=YES
  echo "FAIL_CLOSED=YES"
  echo "FAIL_REASON=${reason}"
  echo "INITIALIZER_INVOKED=${INITIALIZER_INVOKED}"
  echo "PRODUCTION_DB_WRITE_OCCURRED=${PRODUCTION_DB_WRITE_OCCURRED}"
  exit 1
}

WRAPPER_BACKEND_ROOT="$(s4f7f_wrapper_backend_root || true)"
export DI_S4F7F_WRAPPER_BACKEND_ROOT="${WRAPPER_BACKEND_ROOT}"
export DI_S4F7F_MAIN_CHECKOUT_SHA="$(git -C "${WRAPPER_BACKEND_ROOT}" rev-parse HEAD 2>/dev/null || echo "")"

RELEASE_DIR="$(s4f7f_resolve_release_dir)"
if [[ -z "$RELEASE_DIR" || ! -d "$RELEASE_DIR" ]]; then
  s4f7f_fail "RELEASE_DIR_UNRESOLVED"
fi
ACTUAL_RELEASE_ID="$(basename "$RELEASE_DIR")"
ACTUAL_SHA="$(s4f7f_release_sha "$RELEASE_DIR")"
RELEASE_BACKEND="${RELEASE_DIR}/backend"
S4F7F_RELEASE_BACKEND="$RELEASE_BACKEND"
export S4F7F_RELEASE_BACKEND
DEPLOYED_INITIALIZER="$(readlink -f "${RELEASE_BACKEND}/scripts/ops/di-v0-s4-initialize-global-kill-row.ts" 2>/dev/null || echo "${RELEASE_BACKEND}/scripts/ops/di-v0-s4-initialize-global-kill-row.ts")"

echo "VERIFIED_RELEASE_DIR=${RELEASE_DIR}"
echo "ACTUAL_RELEASE_ID=${ACTUAL_RELEASE_ID}"
echo "ACTUAL_PRODUCTION_SHA=${ACTUAL_SHA}"
echo "DEPLOYED_INITIALIZER_SCRIPT=${DEPLOYED_INITIALIZER}"
echo "DEPLOYED_RELEASE_INITIALIZER_IS_EXECUTION_AUTHORITY=YES"
echo "WRAPPER_REQUIRES_NEW_CODE_DEPLOY_BEFORE_USE=NO"

if [[ ! -f "$DEPLOYED_INITIALIZER" ]]; then
  s4f7f_fail "DEPLOYED_INITIALIZER_MISSING"
fi

if ! s4f7f_verify_initializer_path_pinned "$RELEASE_DIR" "$DEPLOYED_INITIALIZER"; then
  s4f7f_fail "INITIALIZER_SUBSTITUTION_RISK"
fi

if ! s4f7f_verify_deployed_kill_files_clean "$RELEASE_DIR" "${DI_S4_KILL_INIT_REQUIRED_SHA:-$ACTUAL_SHA}"; then
  s4f7f_fail "DEPLOYED_RELEASE_FILE_DIRTY"
fi

if [[ ! -r "$BACKEND_ENV" ]]; then
  s4f7f_fail "BACKEND_ENV_UNREADABLE"
fi

ACTUAL_ENV_SHA256="$(s4f7f_file_sha256 "$BACKEND_ENV")"
echo "BACKEND_ENV_SHA256=${ACTUAL_ENV_SHA256}"

s4f7f_topology_snapshot "$ACTUAL_SHA" "$RELEASE_DIR"

if ! s4f7f_apply_global_read_to_env 0; then
  s4f7f_fail "GLOBAL_PRESTATE_READ_FAILED"
fi

if ! s4f7f_apply_s4_counts_to_env; then
  s4f7f_fail "S4_PERSISTENCE_READ_FAILED"
fi

S4_COUNTS_BEFORE=(
  "$DI_S4F7F_S4_PIPELINE_REGISTRY_ROWS"
  "$DI_S4F7F_S4_WORK_ITEM_ROWS"
  "$DI_S4F7F_S4_ACTIVE_WORK_ITEM_ROWS"
  "$DI_S4F7F_S4_EVIDENCE_SNAPSHOT_ROWS"
  "$DI_S4F7F_S4_SHADOW_RUN_ROWS"
  "$DI_S4F7F_S4_SHADOW_INTERVAL_ROWS"
)

if s4f7f_is_fixture_mode || s4f7f_is_test_mode; then
  REDIS_REACHABLE="${DI_S4F7F_FIXTURE_REDIS_REACHABLE:-YES}"
  echo "METRICS_AUTH_USED=FIXTURE"
else
  if s4f7f_run_deployed_s4f4_cli "$RELEASE_BACKEND" redis-ping "$BACKEND_ENV"; then
    REDIS_REACHABLE=YES
  else
    REDIS_REACHABLE=NO
  fi
fi
export DI_S4F7F_REDIS_REACHABLE="$REDIS_REACHABLE"
echo "REDIS_REACHABLE=${REDIS_REACHABLE}"

RAW_A=""
RAW_B=""
if ! RAW_A="$(s4f7f_budget_runtime_for_label A "${SYNQDRIVE_REPLICA_A_PORT}" "$BACKEND_ENV" "$RELEASE_BACKEND")"; then
  echo "METRICS_AUTH_USED=NO"
  s4f7f_fail "GLOBAL_BUDGET_METRIC_READ_FAILED"
fi
if ! RAW_B="$(s4f7f_budget_runtime_for_label B "${SYNQDRIVE_REPLICA_B_PORT}" "$BACKEND_ENV" "$RELEASE_BACKEND")"; then
  echo "METRICS_AUTH_USED=NO"
  s4f7f_fail "GLOBAL_BUDGET_METRIC_READ_FAILED"
fi
if ! s4f7f_is_fixture_mode && ! s4f7f_is_test_mode; then
  echo "METRICS_AUTH_USED=YES"
  echo "METRICS_SECRET_EXPOSED=NO"
fi
RUNTIME_A="$(s4f7f_map_metric_to_runtime "$RAW_A")"
RUNTIME_B="$(s4f7f_map_metric_to_runtime "$RAW_B")"
export DI_S4F7F_REPLICA_A_BUDGET_RUNTIME="$RUNTIME_A"
export DI_S4F7F_REPLICA_B_BUDGET_RUNTIME="$RUNTIME_B"
echo "REPLICA_A_GLOBAL_BUDGET_RUNTIME=${RUNTIME_A}"
echo "REPLICA_B_GLOBAL_BUDGET_RUNTIME=${RUNTIME_B}"
if [[ "$RUNTIME_A" == "ENABLED" && "$RUNTIME_B" == "ENABLED" ]]; then
  echo "GLOBAL_BUDGET_ACTIVE_RUNTIME_STATE=CONFIRMED_ENABLED"
else
  echo "GLOBAL_BUDGET_ACTIVE_RUNTIME_STATE=UNVERIFIED"
  s4f7f_fail "GLOBAL_BUDGET_RUNTIME_UNVERIFIED"
fi

s4f7f_run_cli not-before "$BACKEND_ENV" || true

export DI_S4F7F_ACTUAL_SHA="$ACTUAL_SHA"
export DI_S4F7F_ACTUAL_RELEASE_ID="$ACTUAL_RELEASE_ID"
export DI_S4F7F_ACTUAL_ENV_SHA256="$ACTUAL_ENV_SHA256"
export DI_S4F7F_VERIFIED_RELEASE_DIR="$RELEASE_DIR"
export DI_S4F7F_DEPLOYED_INITIALIZER_PATH="$DEPLOYED_INITIALIZER"
export SYNQDRIVE_BACKEND_ENV="$BACKEND_ENV"
export DI_S4F7F_MAIN_CHECKOUT_DIFFERS_FROM_PRODUCTION="$([[ "${DI_S4F7F_MAIN_CHECKOUT_SHA}" != "$ACTUAL_SHA" && -n "${DI_S4F7F_MAIN_CHECKOUT_SHA}" ]] && echo YES || echo NO)"

if ! s4f7f_run_cli evaluate-guards; then
  s4f7f_fail "GUARDS_FAILED"
fi

echo "ALL_GUARDS_PASSED=YES"

if s4f7f_is_dry_run; then
  echo "DRY_RUN=1"
  echo "INTENDED_ACTION=invoke_deployed_initializer_once"
  echo "INTENDED_INITIALIZER=${DEPLOYED_INITIALIZER}"
  echo "INITIALIZER_INVOKED=NO"
  echo "PRODUCTION_DB_WRITE_OCCURRED=NO"
  echo "DRY_RUN_ZERO_MUTATION=PASS"
  echo "PRODUCTION_KILL_INITIALIZER_WRAPPER_PREFLIGHT=PASS"
  exit 0
fi

INIT_OUT="$(mktemp)"
INITIALIZER_INVOKED=YES
echo "INITIALIZER_INVOKED=YES"
if ! s4f7f_invoke_deployed_initializer "$RELEASE_BACKEND" "$INIT_OUT"; then
  s4f7f_fail "INITIALIZER_PROCESS_FAILED"
fi

OUTCOME="$(grep -E '^DI_V0_S4_GLOBAL_KILL_INIT_RESULT=' "$INIT_OUT" | tail -1 | cut -d= -f2- || true)"
echo "DI_V0_S4_GLOBAL_KILL_INIT_RESULT=${OUTCOME}"
export DI_S4F7F_INIT_OUTCOME="$OUTCOME"

if [[ "$OUTCOME" == "INSERTED_KILLED" ]]; then
  PRODUCTION_DB_WRITE_OCCURRED=YES
elif [[ "$OUTCOME" == "ALREADY_KILLED" ]]; then
  PRODUCTION_DB_WRITE_OCCURRED=NO
else
  s4f7f_fail "INITIALIZER_REFUSED_OR_FAILED"
fi

if [[ -n "${DI_S4F7F_TEST_INJECT_INITIALIZER_OUTCOME:-}" ]] && { s4f7f_is_fixture_mode || s4f7f_is_test_mode; }; then
  if [[ "$OUTCOME" == "INSERTED_KILLED" || "$OUTCOME" == "ALREADY_KILLED" ]]; then
    export DI_S4F7F_FIXTURE_GLOBAL_ROW_COUNT=1
    export DI_S4F7F_FIXTURE_GLOBAL_KILL_STATE=KILLED
    if [[ "$OUTCOME" == "INSERTED_KILLED" ]]; then
      export DI_S4F7F_FIXTURE_GLOBAL_REASON="${DI_S4_KILL_INIT_REASON}"
      export DI_S4F7F_FIXTURE_GLOBAL_ACTOR="${DI_S4_KILL_INIT_ACTOR}"
    else
      export DI_S4F7F_FIXTURE_GLOBAL_REASON="${DI_S4F7F_FIXTURE_EXISTING_GLOBAL_REASON:-existing-reason}"
      export DI_S4F7F_FIXTURE_GLOBAL_ACTOR="${DI_S4F7F_FIXTURE_EXISTING_GLOBAL_ACTOR:-existing-actor}"
    fi
  fi
fi

if [[ -n "${DI_S4F7F_TEST_POST_GLOBAL_REASON:-}" ]] && { s4f7f_is_fixture_mode || s4f7f_is_test_mode; }; then
  export DI_S4F7F_FIXTURE_GLOBAL_REASON="${DI_S4F7F_TEST_POST_GLOBAL_REASON}"
fi
if [[ -n "${DI_S4F7F_TEST_POST_GLOBAL_ACTOR:-}" ]] && { s4f7f_is_fixture_mode || s4f7f_is_test_mode; }; then
  export DI_S4F7F_FIXTURE_GLOBAL_ACTOR="${DI_S4F7F_TEST_POST_GLOBAL_ACTOR}"
fi

if ! s4f7f_apply_global_read_to_env 1; then
  echo "POST_WRITE_VERIFY_MISMATCH=YES"
  echo "PRESERVE_KILL_ROW=YES"
  s4f7f_fail "POST_WRITE_VERIFY_FAILED"
fi

if ! s4f7f_run_cli post-verify; then
  echo "POST_WRITE_VERIFY_MISMATCH=YES"
  echo "PRESERVE_KILL_ROW=YES"
  s4f7f_fail "POST_WRITE_VERIFY_FAILED"
fi

ENV_SHA_AFTER="$(s4f7f_file_sha256 "$BACKEND_ENV")"
echo "BACKEND_ENV_SHA256_UNCHANGED=$([[ "$ENV_SHA_AFTER" == "$ACTUAL_ENV_SHA256" ]] && echo YES || echo NO)"
if [[ "$ENV_SHA_AFTER" != "$ACTUAL_ENV_SHA256" ]]; then
  s4f7f_fail "ENV_CHANGED_AFTER_INIT"
fi

if ! s4f7f_apply_s4_counts_to_env; then
  s4f7f_fail "S4_PERSISTENCE_READ_FAILED"
fi
S4_COUNTS_AFTER=(
  "$DI_S4F7F_S4_PIPELINE_REGISTRY_ROWS"
  "$DI_S4F7F_S4_WORK_ITEM_ROWS"
  "$DI_S4F7F_S4_ACTIVE_WORK_ITEM_ROWS"
  "$DI_S4F7F_S4_EVIDENCE_SNAPSHOT_ROWS"
  "$DI_S4F7F_S4_SHADOW_RUN_ROWS"
  "$DI_S4F7F_S4_SHADOW_INTERVAL_ROWS"
)
echo "S4_PIPELINE_REGISTRY_DELTA=$((S4_COUNTS_AFTER[0] - S4_COUNTS_BEFORE[0]))"
echo "S4_WORK_ITEM_DELTA=$((S4_COUNTS_AFTER[1] - S4_COUNTS_BEFORE[1]))"
echo "S4_ACTIVE_WORK_ITEM_DELTA=$((S4_COUNTS_AFTER[2] - S4_COUNTS_BEFORE[2]))"
echo "S4_EVIDENCE_SNAPSHOT_DELTA=$((S4_COUNTS_AFTER[3] - S4_COUNTS_BEFORE[3]))"
echo "S4_SHADOW_RUN_DELTA=$((S4_COUNTS_AFTER[4] - S4_COUNTS_BEFORE[4]))"
echo "S4_SHADOW_INTERVAL_DELTA=$((S4_COUNTS_AFTER[5] - S4_COUNTS_BEFORE[5]))"
echo "S4_PROVIDER_CALL_DELTA=0"

s4f7f_topology_snapshot "$ACTUAL_SHA" "$RELEASE_DIR"

echo "PRODUCTION_DB_WRITE_OCCURRED=${PRODUCTION_DB_WRITE_OCCURRED}"
echo "PRODUCTION_ENV_MUTATION_OCCURRED=NO"
echo "PRODUCTION_RESTART_OCCURRED=NO"
echo "PRODUCTION_KILL_INITIALIZER_WRAPPER_RESULT=PASS"
rm -f "$INIT_OUT"
