#!/usr/bin/env bash
# Read-only CONFIG-FILE evidence for DIMO_GLOBAL_BUDGET_ENABLED (Tiny Activation).
# Does not inspect PM2 processes, logs, or live runtime env — see EXP021_S4F3 evidence doc.
set -euo pipefail

ENV_PATH="${SYNQDRIVE_BACKEND_ENV:-/opt/synqdrive/shared/backend.env}"

echo "EVIDENCE_SCOPE=CONFIG_FILE_ONLY"
echo "ACTIVE_RUNTIME_CONFIRMATION=NOT_PERFORMED"
echo "GLOBAL_BUDGET_ACTIVE_RUNTIME_STATE=UNVERIFIED"
echo "FILE_AUDIT_CAN_ALONE_SATISFY_TINY_GATE=NO"
echo "AUDIT_BACKEND_ENV_PATH=${ENV_PATH}"
echo "DIMO_GLOBAL_BUDGET_CONFIG_SOURCE=shared_backend_env_file"

if [[ ! -r "${ENV_PATH}" ]]; then
  echo "GLOBAL_BUDGET_CONFIG_FILE_STATE=UNREADABLE"
  echo "DIMO_GLOBAL_BUDGET_CONFIG_EXPLICITLY_DEFINED=NO"
  echo "DIMO_GLOBAL_BUDGET_CONFIG_NORMALIZED_VALUE=UNKNOWN"
  echo "DIMO_GLOBAL_BUDGET_ENV_EXPLICITLY_DEFINED=NO"
  echo "DIMO_GLOBAL_BUDGET_ENV_NORMALIZED_VALUE=UNKNOWN"
  echo "PROVIDER_GLOBAL_BUDGET_EVIDENCE_SOURCE=backend_env_file_missing_or_unreadable"
  echo "GENERIC_DIMO_CONFIG_DEFAULT_TRUE_IS_NOT_TINY_ACTIVATION_EVIDENCE=YES"
  exit 0
fi

if grep -q '^DIMO_GLOBAL_BUDGET_ENABLED=' "${ENV_PATH}"; then
  echo "DIMO_GLOBAL_BUDGET_CONFIG_EXPLICITLY_DEFINED=YES"
  RAW="$(grep '^DIMO_GLOBAL_BUDGET_ENABLED=' "${ENV_PATH}" | tail -1 | cut -d= -f2-)"
  case "$(echo "${RAW}" | tr '[:upper:]' '[:lower:]' | tr -d '[:space:]')" in
    true | 1 | yes | on)
      echo "GLOBAL_BUDGET_CONFIG_FILE_STATE=EXPLICIT_ENABLED"
      echo "DIMO_GLOBAL_BUDGET_CONFIG_NORMALIZED_VALUE=ENABLED"
      ;;
    false | 0 | no | off)
      echo "GLOBAL_BUDGET_CONFIG_FILE_STATE=EXPLICIT_DISABLED"
      echo "DIMO_GLOBAL_BUDGET_CONFIG_NORMALIZED_VALUE=DISABLED"
      ;;
    *)
      echo "GLOBAL_BUDGET_CONFIG_FILE_STATE=MALFORMED"
      echo "DIMO_GLOBAL_BUDGET_CONFIG_NORMALIZED_VALUE=UNKNOWN"
      ;;
  esac
else
  echo "DIMO_GLOBAL_BUDGET_CONFIG_EXPLICITLY_DEFINED=NO"
  echo "GLOBAL_BUDGET_CONFIG_FILE_STATE=MISSING"
  echo "DIMO_GLOBAL_BUDGET_CONFIG_NORMALIZED_VALUE=UNKNOWN"
fi

# Legacy aliases — CONFIG_FILE scope only (do not treat as runtime proof).
echo "DIMO_GLOBAL_BUDGET_ENV_EXPLICITLY_DEFINED=${DIMO_GLOBAL_BUDGET_CONFIG_EXPLICITLY_DEFINED:-NO}"
echo "DIMO_GLOBAL_BUDGET_ENV_NORMALIZED_VALUE=${DIMO_GLOBAL_BUDGET_CONFIG_NORMALIZED_VALUE:-UNKNOWN}"
echo "PROVIDER_GLOBAL_BUDGET_EVIDENCE_SOURCE=shared_backend_env_file"
echo "GENERIC_DIMO_CONFIG_DEFAULT_TRUE_IS_NOT_TINY_ACTIVATION_EVIDENCE=YES"
echo "EFFECTIVE_RUNTIME_DEFAULT_BEHAVIOR=ENABLED_BY_DEFAULT_IF_UNSET_IN_NEST_CONFIG"
echo "TINY_ACTIVATION_EXPLICIT_CONFIG_EVIDENCE=REQUIRES_EXPLICIT_CONFIG_AND_POST_MUTATION_RUNTIME_PROOF"
