#!/usr/bin/env bash
# Canonical production two-replica topology (P1.8.2 / P1.8.2.1).
# Sourced by vps-deploy-release.sh and rollback tooling.

if [[ "${BASH_SOURCE[0]}" == "${0}" ]]; then
  echo "This file must be sourced, not executed." >&2
  exit 1
fi

# Override to 1 only on intentional single-replica hosts (e.g. staging).
SYNQDRIVE_PRODUCTION_REPLICA_COUNT="${SYNQDRIVE_PRODUCTION_REPLICA_COUNT:-2}"

SYNQDRIVE_REPLICA_A_PM2_NAME="${SYNQDRIVE_REPLICA_A_PM2_NAME:-synqdrive}"
SYNQDRIVE_REPLICA_A_PORT="${SYNQDRIVE_REPLICA_A_PORT:-3001}"

SYNQDRIVE_REPLICA_B_PM2_NAME="${SYNQDRIVE_REPLICA_B_PM2_NAME:-synqdrive-b}"
SYNQDRIVE_REPLICA_B_PORT="${SYNQDRIVE_REPLICA_B_PORT:-3002}"
SYNQDRIVE_REPLICA_B_INSTANCE_ID="${SYNQDRIVE_REPLICA_B_INSTANCE_ID:-replica-b}"

SYNQDRIVE_CURRENT_LINK="${SYNQDRIVE_CURRENT_LINK:-/opt/synqdrive/current}"
SYNQDRIVE_RELEASES_ROOT="${SYNQDRIVE_RELEASES_ROOT:-/opt/synqdrive/releases}"
SYNQDRIVE_SHARED_ROOT="${SYNQDRIVE_SHARED_ROOT:-/opt/synqdrive/shared}"
SYNQDRIVE_DEPLOY_STATE_DIR="${SYNQDRIVE_DEPLOY_STATE_DIR:-${SYNQDRIVE_SHARED_ROOT}/deploy-state}"
SYNQDRIVE_NGINX_SITE="${SYNQDRIVE_NGINX_SITE:-/etc/nginx/sites-enabled/synqdrive}"

SYNQDRIVE_EXTERNAL_HEALTH_URL="${SYNQDRIVE_EXTERNAL_HEALTH_URL:-https://app.synqdrive.eu/api/v1/health}"
SYNQDRIVE_MAX_UPTIME_AFTER_DEPLOY_SEC="${SYNQDRIVE_MAX_UPTIME_AFTER_DEPLOY_SEC:-300}"
SYNQDRIVE_REPLICA_HEALTH_RETRIES="${SYNQDRIVE_REPLICA_HEALTH_RETRIES:-45}"
SYNQDRIVE_REPLICA_HEALTH_DELAY_SEC="${SYNQDRIVE_REPLICA_HEALTH_DELAY_SEC:-2}"

# P1.8.3.1 scheduler leader convergence gate (bounded poll, not blind sleep)
# Derived from P1.7 acquireIntervalMs=5000: (2*replicas+2)*acquire + 2*poll + margin ≈ 44s
SYNQDRIVE_SCHEDULER_LEADER_POLL_INTERVAL_MS="${SYNQDRIVE_SCHEDULER_LEADER_POLL_INTERVAL_MS:-2000}"
SYNQDRIVE_SCHEDULER_LEADER_CONVERGENCE_TIMEOUT_MS="${SYNQDRIVE_SCHEDULER_LEADER_CONVERGENCE_TIMEOUT_MS:-44000}"
SYNQDRIVE_SCHEDULER_LEADER_STABLE_OBSERVATIONS="${SYNQDRIVE_SCHEDULER_LEADER_STABLE_OBSERVATIONS:-2}"
