export const STATION_SET_VEHICLES_DEPRECATED_CODE = 'STATION_SET_VEHICLES_DEPRECATED';

export const STATION_SET_VEHICLES_DISABLED_CODE = 'STATION_SET_VEHICLES_DISABLED';

export const STATION_SET_VEHICLES_INCOMPLETE_LIST_CODE = 'STATION_SET_VEHICLES_INCOMPLETE_LIST';

export const STATION_SET_VEHICLES_PARTIAL_LIST_CODE = 'STATION_SET_VEHICLES_PARTIAL_LIST';

export const STATION_SET_VEHICLES_DISABLE_FLAG = 'STATIONS_V2_SET_VEHICLES_DISABLED';

export const STATION_SET_VEHICLES_REPLACEMENT_METHOD = 'POST';

export const STATION_SET_VEHICLES_REPLACEMENT_PATH =
  '/organizations/:orgId/stations/vehicles/change-home-station';
