import { MembershipRole, NotificationCategory } from '@prisma/client';
import {
  NotificationActionType,
  NotificationDomain,
  NotificationEntityType,
  NotificationEventKind,
  NotificationSeverity,
  NotificationSourceType,
} from '../notification.enums';
import type { NotificationEventTypeDefinition } from './notification-event-registry.types';
import {
  billingTarget,
  bookingTarget,
  fleetConnectivityTarget,
  handoverPickupTarget,
  handoverReturnTarget,
  legalDocumentsSettingsTarget,
  stationTarget,
  tripTarget,
  vehicleModuleTarget,
  vehicleTarget,
} from './notification-event-target.builders';
import { LEGAL_DOCUMENT_NOTIFICATION_EVENT_DEFINITIONS } from './legal-document-notification-event.definitions';
import {
  DEFAULT_CRITICAL_DELIVERY,
  DEFAULT_IN_APP_DELIVERY,
  EVENT_RESOLUTION,
  OPERATIONS_REOPEN,
  SHORT_EVENT_EXPIRY,
  STATE_RESOLUTION,
} from './notification-event-registry.policies';

const OPS_ROLES = [
  MembershipRole.ORG_ADMIN,
  MembershipRole.SUB_ADMIN,
  MembershipRole.WORKER,
] as const;

const ALL_STAFF_ROLES = [
  MembershipRole.ORG_ADMIN,
  MembershipRole.SUB_ADMIN,
  MembershipRole.WORKER,
  MembershipRole.DRIVER,
] as const;

export const NOTIFICATION_EVENT_TYPE_DEFINITIONS = [
  {
    slug: 'station-shortage',
    eventType: 'STATION_SHORTAGE',
    domain: NotificationDomain.OPERATIONS,
    defaultEntityType: NotificationEntityType.STATION,
    conditionCode: 'shortage',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.stationShortage',
    bodyKey: 'notification.body.stationShortage',
    requiredTemplateParams: ['stationName', 'available', 'totalVehicles'],
    actionType: NotificationActionType.OPEN_STATION,
    actionTargetBuilder: stationTarget,
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: { ...STATE_RESOLUTION, reopenPolicy: OPERATIONS_REOPEN },
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.BOOKINGS,
    supportedRoles: OPS_ROLES,
    groupingRule: { groupKeyParam: 'stationId' },
    requiresNavigation: true,
    shadowModeEnabled: true,
    producerModule: 'business-insights',
  },
  {
    slug: 'overdue-pickup',
    eventType: 'PICKUP_OVERDUE',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'pickup_overdue',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.pickupOverdue',
    bodyKey: 'notification.body.pickupOverdue',
    requiredTemplateParams: ['bookingRef', 'label'],
    actionType: NotificationActionType.OPEN_HANDOVER_PICKUP,
    actionTargetBuilder: handoverPickupTarget,
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'overdue-return',
    eventType: 'RETURN_OVERDUE',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'return_overdue',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.returnOverdue',
    bodyKey: 'notification.body.returnOverdue',
    requiredTemplateParams: ['bookingRef', 'label'],
    actionType: NotificationActionType.OPEN_HANDOVER_RETURN,
    actionTargetBuilder: handoverReturnTarget,
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'blocked-vehicle',
    eventType: 'BLOCKED_VEHICLE',
    domain: NotificationDomain.OPERATIONS,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'blocked_vehicle',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.blockedVehicle',
    bodyKey: 'notification.body.blockedVehicle',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE,
    actionTargetBuilder: vehicleTarget,
    sourceType: NotificationSourceType.OPERATIONAL_ISSUE,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.TASKS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'operations',
  },
  {
    slug: 'vehicle-not-ready',
    eventType: 'VEHICLE_NOT_READY',
    domain: NotificationDomain.OPERATIONS,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'vehicle_not_ready',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.vehicleNotReady',
    bodyKey: 'notification.body.vehicleNotReady',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE,
    actionTargetBuilder: vehicleTarget,
    sourceType: NotificationSourceType.OPERATIONAL_ISSUE,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.TASKS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'operations',
  },
  {
    slug: 'maintenance-required',
    eventType: 'MAINTENANCE_REQUIRED',
    domain: NotificationDomain.OPERATIONS,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'maintenance_required',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.maintenanceRequired',
    bodyKey: 'notification.body.maintenanceRequired',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('maintenance'),
    sourceType: NotificationSourceType.OPERATIONAL_ISSUE,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.TASKS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'operations',
  },
  {
    slug: 'active-dtc',
    eventType: 'ACTIVE_DTC',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'active_dtc',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.activeDtc',
    bodyKey: 'notification.body.activeDtc',
    requiredTemplateParams: ['label', 'code'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('health'),
    sourceType: NotificationSourceType.HEALTH_ALERT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_CRITICAL_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'vehicle-intelligence',
  },
  {
    slug: 'battery-health-warning',
    eventType: 'BATTERY_CRITICAL',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'battery_critical',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.CRITICAL,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.batteryCritical',
    bodyKey: 'notification.body.batteryCritical',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('battery'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_CRITICAL_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'tire-health-warning',
    eventType: 'TIRE_CRITICAL',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'tires_critical',
    fingerprintVersion: 2,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.CRITICAL,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.tireCritical',
    bodyKey: 'notification.body.tireCritical',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('tires'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_CRITICAL_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'brake-health-warning',
    eventType: 'BRAKE_CRITICAL',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'brakes_critical',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.CRITICAL,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.brakeCritical',
    bodyKey: 'notification.body.brakeCritical',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('brakes'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_CRITICAL_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'compliance-expired',
    eventType: 'COMPLIANCE_EXPIRED',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'compliance_expired',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.complianceExpired',
    bodyKey: 'notification.body.complianceExpired',
    requiredTemplateParams: ['label', 'complianceType'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('service'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'service-overdue',
    eventType: 'SERVICE_OVERDUE',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'service_overdue',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.serviceOverdue',
    bodyKey: 'notification.body.serviceOverdue',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('service'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'tight-handover',
    eventType: 'TIGHT_HANDOVER',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'tight_handover',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.fallback',
    bodyKey: 'notification.body.insightDefault',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_BOOKING,
    actionTargetBuilder: bookingTarget,
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'return-needs-inspection',
    eventType: 'RETURN_NEEDS_INSPECTION',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'return_inspection',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.returnInspection',
    bodyKey: 'notification.body.insightDefault',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_HANDOVER_RETURN,
    actionTargetBuilder: handoverReturnTarget,
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'low-utilization',
    eventType: 'LOW_UTILIZATION',
    domain: NotificationDomain.OPERATIONS,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'low_utilization',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING],
    titleKey: 'notification.title.lowUtilization',
    bodyKey: 'notification.body.lowUtilization',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE,
    actionTargetBuilder: vehicleTarget,
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.BOOKINGS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'service-window',
    eventType: 'SERVICE_WINDOW',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'service_window',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING],
    titleKey: 'notification.fallback',
    bodyKey: 'notification.body.insightDefault',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('service'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.TASKS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'service-before-booking',
    eventType: 'SERVICE_BEFORE_BOOKING',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'service_before_booking',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.fallback',
    bodyKey: 'notification.body.insightDefault',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE,
    actionTargetBuilder: vehicleTarget,
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'tuv-overdue',
    eventType: 'TUV_OVERDUE',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'tuv_overdue',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.complianceExpired',
    bodyKey: 'notification.body.complianceExpired',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('service'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'bokraft-overdue',
    eventType: 'BOKRAFT_OVERDUE',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'bokraft_overdue',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.complianceExpired',
    bodyKey: 'notification.body.complianceExpired',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('service'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'hm-service-no-tracking',
    eventType: 'HM_SERVICE_NO_TRACKING',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'hm_no_tracking',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING],
    titleKey: 'notification.title.hmServiceNoTracking',
    bodyKey: 'notification.body.hmServiceNoTracking',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('service'),
    sourceType: NotificationSourceType.DASHBOARD_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'business-insights',
  },
  {
    slug: 'technical-observation-open',
    eventType: 'TECHNICAL_OBSERVATION_ACTIVE',
    domain: NotificationDomain.VEHICLE_HEALTH,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'technical_observation_active',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.technicalObservation',
    bodyKey: 'notification.body.technicalObservation',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('complaints'),
    sourceType: NotificationSourceType.OPERATIONAL_ISSUE,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.DAMAGE_MISUSE,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: true,
    producerModule: 'vehicle-complaints',
  },
  {
    slug: 'driving-assessment-limited',
    eventType: 'DRIVING_ASSESSMENT_DEVICE_QUALITY',
    domain: NotificationDomain.DRIVING_ANALYSIS,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'driving_assessment_device_quality',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.drivingAssessmentDegraded',
    bodyKey: 'notification.body.drivingAssessmentDegraded',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('health'),
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: true,
    producerModule: 'vehicle-intelligence',
  },
  {
    slug: 'trip-analysis-completed',
    eventType: 'TRIP_ANALYSIS_COMPLETED',
    domain: NotificationDomain.DRIVING_ANALYSIS,
    defaultEntityType: NotificationEntityType.TRIP,
    conditionCode: 'trip_analysis_completed',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO],
    titleKey: 'notification.title.tripAnalysisCompleted',
    bodyKey: 'notification.body.tripAnalysisCompleted',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: tripTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.TASKS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'vehicle-intelligence',
  },
  {
    slug: 'misuse-detected',
    eventType: 'MISUSE_DETECTED',
    domain: NotificationDomain.DRIVING_ANALYSIS,
    defaultEntityType: NotificationEntityType.TRIP,
    conditionCode: 'misuse_detected',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.misuseDetected',
    bodyKey: 'notification.body.misuseDetected',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: tripTarget,
    sourceType: NotificationSourceType.DERIVED_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.DAMAGE_MISUSE,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'vehicle-intelligence',
  },
  {
    slug: 'possible-impact',
    eventType: 'POSSIBLE_IMPACT',
    domain: NotificationDomain.DRIVING_ANALYSIS,
    defaultEntityType: NotificationEntityType.TRIP,
    conditionCode: 'possible_impact',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.possibleImpact',
    bodyKey: 'notification.body.possibleImpact',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: tripTarget,
    sourceType: NotificationSourceType.DERIVED_INSIGHT,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.DAMAGE_MISUSE,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'vehicle-intelligence',
  },
  {
    slug: 'data-quality-limited',
    eventType: 'DATA_QUALITY_LIMITED',
    domain: NotificationDomain.DRIVING_ANALYSIS,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'data_quality_limited',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING],
    titleKey: 'notification.title.dataQualityLimited',
    bodyKey: 'notification.body.dataQualityLimited',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: vehicleModuleTarget('data-analyse'),
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'vehicle-intelligence',
  },
  {
    slug: 'booking-created',
    eventType: 'BOOKING_CREATED',
    domain: NotificationDomain.BOOKINGS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'booking_created',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO],
    titleKey: 'notification.title.bookingCreated',
    bodyKey: 'notification.body.bookingCreated',
    requiredTemplateParams: ['bookingRef', 'label'],
    actionType: NotificationActionType.OPEN_BOOKING,
    actionTargetBuilder: bookingTarget,
    sourceType: NotificationSourceType.BOOKING_TILE,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.BOOKINGS,
    supportedRoles: ALL_STAFF_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'bookings',
  },
  {
    slug: 'booking-updated',
    eventType: 'BOOKING_UPDATED',
    domain: NotificationDomain.BOOKINGS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'booking_updated',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO],
    titleKey: 'notification.title.bookingUpdated',
    bodyKey: 'notification.body.bookingUpdated',
    requiredTemplateParams: ['bookingRef', 'label'],
    actionType: NotificationActionType.OPEN_BOOKING,
    actionTargetBuilder: bookingTarget,
    sourceType: NotificationSourceType.BOOKING_TILE,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.BOOKINGS,
    supportedRoles: ALL_STAFF_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'bookings',
  },
  {
    slug: 'pickup-due',
    eventType: 'PICKUP_DUE',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'pickup_due',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING],
    titleKey: 'notification.title.pickupDue',
    bodyKey: 'notification.body.pickupDue',
    requiredTemplateParams: ['bookingRef', 'label'],
    actionType: NotificationActionType.OPEN_HANDOVER_PICKUP,
    actionTargetBuilder: handoverPickupTarget,
    sourceType: NotificationSourceType.BOOKING_TILE,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'bookings',
  },
  {
    slug: 'return-due',
    eventType: 'RETURN_DUE',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'return_due',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING],
    titleKey: 'notification.title.returnDue',
    bodyKey: 'notification.body.returnDue',
    requiredTemplateParams: ['bookingRef', 'label'],
    actionType: NotificationActionType.OPEN_HANDOVER_RETURN,
    actionTargetBuilder: handoverReturnTarget,
    sourceType: NotificationSourceType.BOOKING_TILE,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'bookings',
  },
  {
    slug: 'handover-incomplete',
    eventType: 'HANDOVER_INCOMPLETE',
    domain: NotificationDomain.HANDOVERS,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'handover_incomplete',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.handoverIncomplete',
    bodyKey: 'notification.body.handoverIncomplete',
    requiredTemplateParams: ['bookingRef', 'label'],
    actionType: NotificationActionType.OPEN_HANDOVER_PICKUP,
    actionTargetBuilder: handoverPickupTarget,
    sourceType: NotificationSourceType.WORKFLOW,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.PICKUPS_RETURNS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'bookings',
  },
  {
    slug: 'required-document-missing',
    eventType: 'REQUIRED_DOCUMENT_MISSING',
    domain: NotificationDomain.DOCUMENTS,
    defaultEntityType: NotificationEntityType.ORGANIZATION,
    conditionCode: 'required_document_missing',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.CRITICAL,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.requiredDocumentMissing',
    bodyKey: 'notification.body.requiredDocumentMissing',
    requiredTemplateParams: ['documentType', 'categoryTitle'],
    actionType: NotificationActionType.OPEN_RENTAL,
    actionTargetBuilder: legalDocumentsSettingsTarget,
    sourceType: NotificationSourceType.WORKFLOW,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.DOCUMENTS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'documents',
  },
  ...LEGAL_DOCUMENT_NOTIFICATION_EVENT_DEFINITIONS,
  {
    slug: 'payment-failed',
    eventType: 'PAYMENT_FAILED',
    domain: NotificationDomain.BILLING,
    defaultEntityType: NotificationEntityType.INVOICE,
    conditionCode: 'payment_failed',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.CRITICAL,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.paymentFailed',
    bodyKey: 'notification.body.paymentFailed',
    requiredTemplateParams: ['invoiceRef'],
    actionType: NotificationActionType.OPEN_BILLING,
    actionTargetBuilder: billingTarget,
    sourceType: NotificationSourceType.SYSTEM,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_CRITICAL_DELIVERY,
    preferenceCategory: NotificationCategory.INVOICES_PAYMENTS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'billing',
  },
  {
    slug: 'invoice-overdue',
    eventType: 'INVOICE_OVERDUE',
    domain: NotificationDomain.BILLING,
    defaultEntityType: NotificationEntityType.INVOICE,
    conditionCode: 'invoice_overdue',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.invoiceOverdue',
    bodyKey: 'notification.body.invoiceOverdue',
    requiredTemplateParams: ['invoiceRef'],
    actionType: NotificationActionType.OPEN_BILLING,
    actionTargetBuilder: billingTarget,
    sourceType: NotificationSourceType.SYSTEM,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.INVOICES_PAYMENTS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'billing',
  },
  {
    slug: 'deposit-problem',
    eventType: 'DEPOSIT_PROBLEM',
    domain: NotificationDomain.BILLING,
    defaultEntityType: NotificationEntityType.BOOKING,
    conditionCode: 'deposit_problem',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.depositProblem',
    bodyKey: 'notification.body.depositProblem',
    requiredTemplateParams: ['bookingRef'],
    actionType: NotificationActionType.OPEN_BOOKING,
    actionTargetBuilder: bookingTarget,
    sourceType: NotificationSourceType.SYSTEM,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.INVOICES_PAYMENTS,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'billing',
  },
  {
    slug: 'integration-disconnected',
    eventType: 'INTEGRATION_DISCONNECTED',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.ORGANIZATION,
    conditionCode: 'integration_disconnected',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.CRITICAL,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.integrationDisconnected',
    bodyKey: 'notification.body.integrationDisconnected',
    requiredTemplateParams: ['integrationName'],
    actionType: NotificationActionType.OPEN_RENTAL,
    actionTargetBuilder: () => ({ type: NotificationActionType.OPEN_RENTAL }),
    sourceType: NotificationSourceType.SYSTEM,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_CRITICAL_DELIVERY,
    preferenceCategory: NotificationCategory.SECURITY,
    supportedRoles: [MembershipRole.ORG_ADMIN, MembershipRole.SUB_ADMIN],
    requiresNavigation: false,
    shadowModeEnabled: false,
    producerModule: 'integrations',
  },
  {
    slug: 'telemetry-offline',
    eventType: 'TELEMETRY_OFFLINE',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'telemetry_offline',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.telemetryOffline',
    bodyKey: 'notification.body.telemetryOffline',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'device-unplugged',
    eventType: 'DEVICE_UNPLUGGED',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'device_unplugged',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.deviceUnplugged',
    bodyKey: 'notification.body.deviceUnplugged',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'device-reconnected',
    eventType: 'DEVICE_RECONNECTED',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'device_reconnected',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO],
    titleKey: 'notification.title.deviceReconnected',
    bodyKey: 'notification.body.deviceReconnected',
    requiredTemplateParams: ['label', 'recoveryMethod'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'telemetry-soft-offline',
    eventType: 'TELEMETRY_SOFT_OFFLINE',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'telemetry_soft_offline',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING],
    titleKey: 'notification.title.telemetrySoftOffline',
    bodyKey: 'notification.body.telemetrySoftOffline',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'authorization-required',
    eventType: 'AUTHORIZATION_REQUIRED',
    domain: NotificationDomain.SECURITY,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'authorization_required',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.authorizationRequired',
    bodyKey: 'notification.body.authorizationRequired',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.SECURITY,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'data-source-disconnected',
    eventType: 'DATA_SOURCE_DISCONNECTED',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'data_source_disconnected',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING],
    titleKey: 'notification.title.dataSourceDisconnected',
    bodyKey: 'notification.body.dataSourceDisconnected',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'data-coverage-insufficient',
    eventType: 'DATA_COVERAGE_INSUFFICIENT',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'data_coverage_insufficient',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO, NotificationSeverity.WARNING],
    titleKey: 'notification.title.dataCoverageInsufficient',
    bodyKey: 'notification.body.dataCoverageInsufficient',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'device-binding-changed',
    eventType: 'DEVICE_BINDING_CHANGED',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'device_binding_changed',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO],
    titleKey: 'notification.title.deviceBindingChanged',
    bodyKey: 'notification.body.deviceBindingChanged',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'connectivity-state-unknown',
    eventType: 'CONNECTIVITY_STATE_UNKNOWN',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.VEHICLE,
    conditionCode: 'connectivity_state_unknown',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.STATE,
    defaultSeverity: NotificationSeverity.INFO,
    allowedSeverityEscalations: [NotificationSeverity.INFO],
    titleKey: 'notification.title.connectivityStateUnknown',
    bodyKey: 'notification.body.connectivityStateUnknown',
    requiredTemplateParams: ['label'],
    actionType: NotificationActionType.OPEN_VEHICLE_MODULE,
    actionTargetBuilder: fleetConnectivityTarget,
    sourceType: NotificationSourceType.RUNTIME,
    resolutionPolicy: STATE_RESOLUTION,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.VEHICLE_HEALTH,
    supportedRoles: OPS_ROLES,
    requiresNavigation: true,
    shadowModeEnabled: false,
    producerModule: 'dimo',
  },
  {
    slug: 'webhook-failure',
    eventType: 'WEBHOOK_FAILURE',
    domain: NotificationDomain.SYSTEM,
    defaultEntityType: NotificationEntityType.ORGANIZATION,
    conditionCode: 'webhook_failure',
    fingerprintVersion: 1,
    eventKind: NotificationEventKind.EVENT,
    defaultSeverity: NotificationSeverity.WARNING,
    allowedSeverityEscalations: [NotificationSeverity.WARNING, NotificationSeverity.CRITICAL],
    titleKey: 'notification.title.webhookFailure',
    bodyKey: 'notification.body.webhookFailure',
    requiredTemplateParams: ['webhookName'],
    actionType: NotificationActionType.OPEN_RENTAL,
    actionTargetBuilder: () => ({ type: NotificationActionType.OPEN_RENTAL }),
    sourceType: NotificationSourceType.SYSTEM,
    resolutionPolicy: EVENT_RESOLUTION,
    expiryPolicy: SHORT_EVENT_EXPIRY,
    deliveryPolicy: DEFAULT_IN_APP_DELIVERY,
    preferenceCategory: NotificationCategory.SECURITY,
    supportedRoles: [MembershipRole.ORG_ADMIN, MembershipRole.SUB_ADMIN],
    requiresNavigation: false,
    shadowModeEnabled: false,
    producerModule: 'webhooks',
  },
] as const satisfies readonly NotificationEventTypeDefinition[];

export const NOTIFICATION_EVENT_SLUG_ALIASES: Record<string, string> = {
  'pickup-overdue': 'overdue-pickup',
  'return-overdue': 'overdue-return',
  'driving-assessment-recovered': 'driving-assessment-limited',
};
