export const HANDOVER_SIGNATURE_DOCUMENT_TYPE = 'HANDOVER_SIGNATURE' as const;

export const HANDOVER_SIGNATURE_RETENTION_CLASS = 'HANDOVER_SIGNATURE' as const;

export const HANDOVER_SIGNATURE_ALLOWED_MIME_TYPES = new Set([
  'image/png',
  'image/jpeg',
  'image/jpg',
]);

/** Max decoded signature image size (512 KiB). */
export const HANDOVER_SIGNATURE_MAX_BYTES = 512 * 1024;

/** Default short-lived view/download URL TTL. */
export const HANDOVER_SIGNATURE_VIEW_URL_TTL_SECONDS = 300;

export const HANDOVER_SIGNATURE_MIGRATION_EVENT = {
  STARTED: 'MIGRATION_STARTED',
  STORAGE_WRITTEN: 'STORAGE_WRITTEN',
  VERIFIED: 'VERIFIED',
  LEGACY_CLEARED: 'LEGACY_CLEARED',
  SKIPPED: 'SKIPPED',
  FAILED: 'FAILED',
} as const;

export const HANDOVER_SIGNATURE_ERROR_CODE = {
  NOT_FOUND: 'BOOKING_HANDOVER_SIGNATURE_NOT_FOUND',
  INVALID_PAYLOAD: 'BOOKING_HANDOVER_SIGNATURE_INVALID_PAYLOAD',
  ACCESS_DENIED: 'BOOKING_HANDOVER_SIGNATURE_ACCESS_DENIED',
  TOKEN_EXPIRED: 'BOOKING_HANDOVER_SIGNATURE_TOKEN_EXPIRED',
  TOKEN_INVALID: 'BOOKING_HANDOVER_SIGNATURE_TOKEN_INVALID',
  STORAGE_VERIFICATION_FAILED: 'BOOKING_HANDOVER_SIGNATURE_STORAGE_VERIFICATION_FAILED',
} as const;
