export const PICKUP_GATE_EVENT_TYPE = {
  BLOCKED: 'GATE_BLOCKED',
  OVERRIDE: 'GATE_OVERRIDE',
  PASSED: 'GATE_PASSED',
} as const;

export type PickupGateEventType =
  (typeof PICKUP_GATE_EVENT_TYPE)[keyof typeof PICKUP_GATE_EVENT_TYPE];

export const PICKUP_GATE_OUTCOME = {
  ALLOWED: 'ALLOWED',
  BLOCKED: 'BLOCKED',
} as const;

export type PickupGateOutcome =
  (typeof PICKUP_GATE_OUTCOME)[keyof typeof PICKUP_GATE_OUTCOME];

/** Structured gate failure / requirement codes returned to clients. */
export const PICKUP_GATE_CODE = {
  WRONG_BOOKING_STATUS: 'PICKUP_GATE_WRONG_BOOKING_STATUS',
  TENANT_MISMATCH: 'PICKUP_GATE_TENANT_MISMATCH',
  CUSTOMER_TENANT_MISMATCH: 'PICKUP_GATE_CUSTOMER_TENANT_MISMATCH',
  CROSS_TENANT_DOCUMENT: 'PICKUP_GATE_CROSS_TENANT_DOCUMENT',
  ACTOR_MANIPULATION: 'PICKUP_GATE_ACTOR_MANIPULATION',
  INTEGRITY_FAILED: 'PICKUP_GATE_INTEGRITY_FAILED',
  MALWARE_BLOCKED: 'PICKUP_GATE_MALWARE_BLOCKED',
  GENERATION_IN_PROGRESS: 'PICKUP_GATE_GENERATION_IN_PROGRESS',
  RESOLVER_CONFLICT: 'PICKUP_GATE_RESOLVER_CONFLICT',
  PRIVACY_POLICY_MISSING: 'PICKUP_GATE_PRIVACY_POLICY_MISSING',
  CONSUMER_INFO_MISSING: 'PICKUP_GATE_CONSUMER_INFO_MISSING',
  TERMS_MISSING: 'PICKUP_GATE_TERMS_MISSING',
  LEGAL_PRESENTATION_MISSING: 'PICKUP_GATE_LEGAL_PRESENTATION_MISSING',
  LEGAL_ACKNOWLEDGMENT_MISSING: 'PICKUP_GATE_LEGAL_ACKNOWLEDGMENT_MISSING',
  DOCUMENTS_NOT_ACKNOWLEDGED: 'PICKUP_GATE_DOCUMENTS_NOT_ACKNOWLEDGED',
  SIGNATURE_MISSING: 'PICKUP_GATE_SIGNATURE_MISSING',
  BUNDLE_INCOMPLETE: 'PICKUP_GATE_BUNDLE_INCOMPLETE',
  PREPARATION_INCOMPLETE: 'PICKUP_GATE_PREPARATION_INCOMPLETE',
  DELIVERY_PENDING: 'PICKUP_GATE_DELIVERY_PENDING',
  CUSTOMER_INELIGIBLE: 'PICKUP_GATE_CUSTOMER_INELIGIBLE',
  OVERRIDE_DENIED: 'PICKUP_GATE_OVERRIDE_DENIED',
  OVERRIDE_REASON_REQUIRED: 'PICKUP_GATE_OVERRIDE_REASON_REQUIRED',
} as const;

export type PickupGateCode = (typeof PICKUP_GATE_CODE)[keyof typeof PICKUP_GATE_CODE];

/** Hard blocks — no authorized override permitted. */
export const PICKUP_GATE_NON_OVERRIDABLE_CODES = new Set<PickupGateCode>([
  PICKUP_GATE_CODE.WRONG_BOOKING_STATUS,
  PICKUP_GATE_CODE.TENANT_MISMATCH,
  PICKUP_GATE_CODE.CUSTOMER_TENANT_MISMATCH,
  PICKUP_GATE_CODE.CROSS_TENANT_DOCUMENT,
  PICKUP_GATE_CODE.ACTOR_MANIPULATION,
  PICKUP_GATE_CODE.INTEGRITY_FAILED,
  PICKUP_GATE_CODE.MALWARE_BLOCKED,
  PICKUP_GATE_CODE.GENERATION_IN_PROGRESS,
  PICKUP_GATE_CODE.PREPARATION_INCOMPLETE,
  PICKUP_GATE_CODE.RESOLVER_CONFLICT,
  PICKUP_GATE_CODE.OVERRIDE_DENIED,
  PICKUP_GATE_CODE.OVERRIDE_REASON_REQUIRED,
]);

export const PICKUP_GATE_ALLOWED_SOURCE_STATUSES = ['CONFIRMED'] as const;
