/** Stable error codes for booking status transition failures. */
export const BOOKING_STATE_MACHINE_ERROR_CODES = {
  TRANSITION_NOT_ALLOWED: 'BOOKING_STATUS_TRANSITION_NOT_ALLOWED',
  TERMINAL_REACTIVATION_FORBIDDEN: 'BOOKING_TERMINAL_REACTIVATION_FORBIDDEN',
  OVERRIDE_REASON_REQUIRED: 'BOOKING_STATUS_OVERRIDE_REASON_REQUIRED',
  OVERRIDE_DENIED: 'BOOKING_STATUS_OVERRIDE_DENIED',
  PRECONDITION_FAILED: 'BOOKING_STATUS_PRECONDITION_FAILED',
  NO_SHOW_TOO_EARLY: 'BOOKING_NO_SHOW_TOO_EARLY',
  STATUS_CHANGE_VIA_GENERIC_UPDATE_FORBIDDEN:
    'BOOKING_STATUS_CHANGE_VIA_GENERIC_UPDATE_FORBIDDEN',
} as const;

export type BookingStateMachineErrorCode =
  (typeof BOOKING_STATE_MACHINE_ERROR_CODES)[keyof typeof BOOKING_STATE_MACHINE_ERROR_CODES];
