/** Semantic version of the gatekeeper evaluation contract — bump on breaking output changes. */
export const BOOKING_ELIGIBILITY_GATE_ENGINE_VERSION = '1.0.0';

export const BOOKING_ELIGIBILITY_GATE_DOMAIN = {
  CUSTOMER: 'customer',
  VERIFICATION: 'verification',
  RENTAL_RULES: 'rental_rules',
  VEHICLE: 'vehicle',
  VEHICLE_READINESS: 'vehicle_readiness',
  PRICING_DEPOSIT: 'pricing_deposit',
  SYSTEM: 'system',
} as const;

export type BookingEligibilityGateDomain =
  (typeof BOOKING_ELIGIBILITY_GATE_DOMAIN)[keyof typeof BOOKING_ELIGIBILITY_GATE_DOMAIN];

/** Machine-readable reason codes — stable across API versions. */
export const BOOKING_ELIGIBILITY_REASON_CODE = {
  // Customer lifecycle
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  CUSTOMER_ARCHIVED: 'CUSTOMER_ARCHIVED',
  CUSTOMER_BLOCKED: 'CUSTOMER_BLOCKED',
  CUSTOMER_SUSPENDED: 'CUSTOMER_SUSPENDED',
  CUSTOMER_INACTIVE: 'CUSTOMER_INACTIVE',
  CUSTOMER_UNDER_REVIEW: 'CUSTOMER_UNDER_REVIEW',
  CUSTOMER_HIGH_RISK: 'CUSTOMER_HIGH_RISK',
  CUSTOMER_LICENSE_EXPIRED: 'CUSTOMER_LICENSE_EXPIRED',
  CUSTOMER_ID_EXPIRED: 'CUSTOMER_ID_EXPIRED',
  CUSTOMER_OVERDUE_INVOICES: 'CUSTOMER_OVERDUE_INVOICES',
  CUSTOMER_OPEN_FINES: 'CUSTOMER_OPEN_FINES',
  CUSTOMER_STAGE_BLOCKED: 'CUSTOMER_STAGE_BLOCKED',

  // Document / verification
  ID_DOCUMENT_MISSING: 'ID_DOCUMENT_MISSING',
  ID_DOCUMENT_PENDING: 'ID_DOCUMENT_PENDING',
  ID_DOCUMENT_REJECTED: 'ID_DOCUMENT_REJECTED',
  ID_DOCUMENT_EXPIRED: 'ID_DOCUMENT_EXPIRED',
  ID_DOCUMENT_REQUIRES_REVIEW: 'ID_DOCUMENT_REQUIRES_REVIEW',
  ID_DOCUMENT_PICKUP_REQUIRED: 'ID_DOCUMENT_PICKUP_REQUIRED',
  LICENSE_MISSING: 'LICENSE_MISSING',
  LICENSE_PENDING: 'LICENSE_PENDING',
  LICENSE_REJECTED: 'LICENSE_REJECTED',
  LICENSE_EXPIRED: 'LICENSE_EXPIRED',
  LICENSE_REQUIRES_REVIEW: 'LICENSE_REQUIRES_REVIEW',
  LICENSE_PICKUP_REQUIRED: 'LICENSE_PICKUP_REQUIRED',
  PROOF_OF_ADDRESS_REQUIRED: 'PROOF_OF_ADDRESS_REQUIRED',
  PROOF_OF_ADDRESS_PENDING: 'PROOF_OF_ADDRESS_PENDING',
  PROOF_OF_ADDRESS_REJECTED: 'PROOF_OF_ADDRESS_REJECTED',
  PROOF_OF_ADDRESS_REQUIRES_REVIEW: 'PROOF_OF_ADDRESS_REQUIRES_REVIEW',

  // Effective rental rules
  RENTAL_RULES_INACTIVE: 'RENTAL_RULES_INACTIVE',
  MINIMUM_AGE_NOT_MET: 'MINIMUM_AGE_NOT_MET',
  LICENSE_HOLDING_TOO_SHORT: 'LICENSE_HOLDING_TOO_SHORT',
  CREDIT_CARD_REQUIRED: 'CREDIT_CARD_REQUIRED',
  DEPOSIT_REQUIRED: 'DEPOSIT_REQUIRED',
  FOREIGN_TRAVEL_NOT_ALLOWED: 'FOREIGN_TRAVEL_NOT_ALLOWED',
  FOREIGN_TRAVEL_APPROVAL_REQUIRED: 'FOREIGN_TRAVEL_APPROVAL_REQUIRED',
  ADDITIONAL_DRIVER_NOT_ALLOWED: 'ADDITIONAL_DRIVER_NOT_ALLOWED',
  ADDITIONAL_DRIVER_APPROVAL_REQUIRED: 'ADDITIONAL_DRIVER_APPROVAL_REQUIRED',
  YOUNG_DRIVER_NOT_ALLOWED: 'YOUNG_DRIVER_NOT_ALLOWED',
  YOUNG_DRIVER_FEE_REQUIRED: 'YOUNG_DRIVER_FEE_REQUIRED',
  RENTAL_MANUAL_APPROVAL_REQUIRED: 'RENTAL_MANUAL_APPROVAL_REQUIRED',
  MISSING_CUSTOMER_DATE_OF_BIRTH: 'MISSING_CUSTOMER_DATE_OF_BIRTH',
  MISSING_CUSTOMER_LICENSE_ISSUED_AT: 'MISSING_CUSTOMER_LICENSE_ISSUED_AT',

  // Vehicle reference
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',

  // Vehicle readiness (Rental Health — optional evaluator)
  VEHICLE_RENTAL_BLOCKED: 'VEHICLE_RENTAL_BLOCKED',
  VEHICLE_READINESS_UNAVAILABLE: 'VEHICLE_READINESS_UNAVAILABLE',

  // Pricing / deposit conflict (optional evaluator — future)
  PRICING_DEPOSIT_NOT_EVALUATED: 'PRICING_DEPOSIT_NOT_EVALUATED',
  PRICING_DEPOSIT_CONFLICT: 'PRICING_DEPOSIT_CONFLICT',

  // System
  EVALUATOR_SKIPPED: 'EVALUATOR_SKIPPED',
  TECHNICAL_ERROR: 'TECHNICAL_ERROR',
} as const;

export type BookingEligibilityReasonCode =
  (typeof BOOKING_ELIGIBILITY_REASON_CODE)[keyof typeof BOOKING_ELIGIBILITY_REASON_CODE];
