export type ReadinessInputClass =
  | 'MANDATORY_FOR_IDENTITY'
  | 'MANDATORY_FOR_TENANT_ASSIGNMENT'
  | 'MANDATORY_FOR_SELECTED_PRODUCT'
  | 'MANDATORY_FOR_SAFETY_REGULATION'
  | 'OPTIONAL_ENRICHMENT'
  | 'CAPABILITY_UNKNOWN_ALLOWED';
