/** Customer/driver rental pattern summary policy (P64). */
export const RENTAL_PATTERN_SUMMARY_VERSION = 'rental-pattern-summary-v1';

export const RENTAL_PATTERN_SUMMARY_CONFIG = {
  MIN_ASSESSED_RENTALS: 2,
  MIN_ATTRIBUTED_RENTALS_FOR_PATTERN: 2,
  MIN_ATTRIBUTION_COVERAGE_PCT: 70,
  MIN_DATA_COVERAGE_PCT: 60,
  MIN_NATIVE_EVIDENCE_SHARE_PCT: 30,
  MAX_PROXY_ONLY_SHARE_PCT: 70,
  REPEATED_PATTERN_MIN_CONCERNING_RENTALS: 2,
  STRONG_SINGLE_HARSH_PER_100KM: 15,
  LOOKBACK_RENTALS: 24,
  COMPATIBLE_CALCULATION_VERSIONS: ['rental-driving-analysis-v2', 'rental-driving-analysis-v1'],
} as const;
