/** Shared UI tokens + copy for Vehicle Detail → Trips tab. */
export const tv = {
  page: 'max-w-[1600px] mx-auto px-0.5 sm:px-0',
  grid: 'grid grid-cols-1 xl:grid-cols-[minmax(0,1.12fr)_minmax(0,1fr)] gap-3 sm:gap-4 xl:gap-5 items-start',
  panel: 'surface-premium rounded-2xl p-3.5 sm:p-4 min-w-0',
  mapPanel:
    'surface-premium rounded-2xl p-3.5 sm:p-4 flex flex-col min-w-0 xl:sticky xl:top-2 xl:self-start xl:h-[calc(100vh-128px)] xl:min-h-[520px]',
  mapFrame:
    'relative w-full h-[min(42vh,360px)] sm:h-[min(44vh,400px)] xl:h-auto xl:flex-1 xl:min-h-[340px] rounded-xl overflow-hidden border border-border/50',
  overlay:
    'sq-map-liquid-overlay flex items-center justify-center z-10 motion-reduce:backdrop-blur-none',
  sectionTitle: 'text-[13px] font-semibold tracking-[-0.02em] text-foreground font-display',
  sectionEyebrow: 'text-[10px] font-semibold uppercase tracking-[0.07em] text-muted-foreground',
  meta: 'text-[11px] text-muted-foreground leading-relaxed',
  toggleBtn:
    'flex items-center gap-1 px-2 py-1 rounded-md text-[10px] font-semibold transition-all border',
  actionBtn:
    'inline-flex items-center gap-1.5 px-2.5 sm:px-3 py-2 rounded-xl text-[11px] font-semibold border border-border/60 surface-premium hover:bg-muted/50 active:scale-[0.98] transition-all disabled:opacity-50',
  actionBtnPrimary:
    'inline-flex items-center gap-1.5 px-2.5 sm:px-3 py-2 rounded-xl text-[11px] font-semibold border border-[color:var(--brand)]/25 bg-[color:var(--brand-soft)] text-[color:var(--brand-ink)] hover:bg-[color:color-mix(in_srgb,var(--brand)_12%,transparent)] active:scale-[0.98] transition-all disabled:opacity-50',
  focusRing:
    'focus-visible:outline-none focus-visible:ring-2 focus-visible:ring-[color:var(--brand)] focus-visible:ring-offset-2 focus-visible:ring-offset-background',
} as const;

export const SUMMARY_COPY = {
  ariaLabel: 'Zeitraum-Zusammenfassung',
  title: 'Fahrverlauf',
  trips: 'Fahrten',
  distance: 'Kilometer',
  duration: 'Fahrzeit',
  notable: 'Ereignisse',
  private: 'Privat',
  unlinked: 'Ohne Buchung',
  dataQuality: 'Datenqualität',
  notableHint: (n: number) =>
    n === 1
      ? '1 auffälliges Ereignis im gewählten Zeitraum — Details in der Liste prüfen.'
      : `${n} auffällige Ereignisse im gewählten Zeitraum — Details in der Liste prüfen.`,
} as const;

export const TRIPS_COPY = {
  mapTitle: 'Routenkarte',
  mapTitleTrip: (date: string) => `Route · ${date}`,
  tripHistory: 'Fahrtenliste',
  checkMissingTrips: 'Fehlende Fahrten prüfen',
  checkMissingShort: 'Prüfen',
  centerRoute: 'Route zentrieren',
  loadingMap: 'Karte wird geladen…',
  loadingRoute: 'Route wird geladen…',
  enrichingTrip: 'Fahrt wird angereichert…',
  mapUnavailable: 'Karte aktuell nicht verfügbar',
  mapUnavailableTitle: 'Karte nicht verfügbar',
  mapUnavailableHint: 'Die Fahrtenliste bleibt vollständig nutzbar.',
  mapLoadFailed: 'Karte konnte nicht geladen werden.',
  routeUnavailable: 'Route für diese Fahrt nicht verfügbar.',
  loadTripsFailed: 'Fahrten konnten nicht geladen werden.',
  syncFailed: 'Prüfung fehlgeschlagen',
  syncNoMissing: 'Keine fehlenden Fahrten gefunden',
  syncRepaired: (n: number) => `${n} Fahrt(en) ergänzt`,
  emptyNoTrips: 'Keine Fahrten im gewählten Zeitraum',
  emptyNoTripsHint:
    'Fahrten werden aus DIMO-Segmenten geladen. Fahrzeug verbinden oder Zeitraum anpassen.',
  emptyNoVehicle: 'Bitte zuerst ein Fahrzeug auswählen.',
  speed: 'Tempo',
  events: 'Ereignisse',
  abuse: 'Missbrauch',
  stops: 'Stopps',
  slow: 'Langsam',
  normal: 'Normal',
  fast: 'Schnell',
  stop: 'Stopp',
  mapMatched: 'Route abgeglichen',
  statusOngoing: 'Aktiv',
  statusCompleted: 'Abgeschlossen',
  statusLimited: 'Eingeschränkt',
  statusAnalyzing: 'Analyse läuft',
  statusGap: 'Lücke',
  statusPrivate: 'Privat',
  metricDistance: 'Strecke',
  metricDuration: 'Dauer',
  metricEvents: 'Ereignisse',
  enrichingInline: 'Fahrt wird angereichert…',
  engine: 'Motor',
  noEngineTelemetry: 'Keine Motordaten für diese Fahrt verfügbar.',
  mapMatchConfidence: 'Routen-Match-Konfidenz',
  energyWarning: 'Energieereignisse konnten nicht geladen werden.',
  retry: 'Erneut versuchen',
} as const;

export const TIMELINE_COPY = {
  tripHistory: 'Fahrtenliste',
  checkMissingTrips: 'Fehlende Fahrten prüfen',
  checkMissingShort: 'Prüfen',
  refreshTimeline: 'Aktualisieren',
  retryLoad: 'Erneut versuchen',
  analyzeBehavior: 'Fahrverhalten analysieren',
  reloadRoute: 'Route neu laden',
  showDetails: 'Details anzeigen',
  centerRoute: 'Route zentrieren',
  emptyNoVehicle: 'Bitte zuerst ein Fahrzeug auswählen.',
  emptyNoTripsRange: 'Keine Fahrten im gewählten Zeitraum',
  emptyNoTripsYet: 'Noch keine Fahrten für dieses Fahrzeug',
  emptyRangeHint: 'Zeitraum anpassen oder fehlende Fahrten prüfen.',
  emptyYetHint: 'Fahrten werden aus DIMO-Segmenten geladen. Fahrzeug verbinden oder fehlende Fahrten prüfen.',
  errorLoad: 'Fahrten konnten nicht geladen werden',
  errorLoadHint: 'Bitte erneut versuchen oder später laden.',
  daySummary: (n: number, km: string, dur: string) => `${n} Fahrten · ${km} · ${dur}`,
  dayNotable: (n: number) => `${n} auffällige Ereignisse`,
  dayPrivate: (n: number) => `${n} privat / nicht zugewiesen`,
  energyEvents: (n: number) => `${n} Energieereignisse`,
  sectionBehavior: 'Fahrverhalten',
  sectionEvents: 'Ereignisse',
  sectionAssignment: 'Zuordnung & Kontext',
  sectionEvidence: 'Beweisübersicht',
} as const;

export const RENTAL_COPY = {
  bookingContext: 'Buchungsbezug',
  noBookingLinked: 'Keine Buchung verknüpft',
  reviewAction: 'Prüfen',
  openBooking: 'Buchung öffnen',
  rentalPeriod: 'Mietzeitraum',
  pickupHandover: 'Übergabe',
  vehicleStatusAtTrip: 'Fahrzeugstatus',
  driverContext: 'Fahrer',
  customerContext: 'Kunde',
  rentalAlignment: 'Mietzeit-Abgleich',
  kmContext: 'Kilometer',
  tripKm: 'Fahrt',
  dayKm: 'Tagessumme',
  bookingKm: 'Buchung gefahren',
  kmIncluded: 'Inklusiv',
  potentialExcessKm: 'Potenzielle Mehrkilometer',
  kmDeviation: 'Abweichung Inklusiv',
  loadingBookings: 'Buchungen werden geladen…',
  loadingBookingDetail: 'Buchungsdetails werden geladen…',
  evidenceTitle: 'Beweisübersicht',
  evidenceNotableHint: 'Auffällige Fahrt — Belastungsereignisse vorhanden.',
  evidenceReviewHint: 'Zur Prüfung markiert — Kontext für operative Bewertung.',
  evidenceTime: 'Zeit',
  evidenceDistance: 'Strecke',
  evidenceStart: 'Start',
  evidenceDestination: 'Ziel',
  evidenceStress: 'Belastung',
  evidenceEvents: 'Ereignisse',
  evidenceAssignment: 'Zuordnung',
  evidenceBooking: 'Buchung',
  evidenceRoute: 'Route',
  evidenceDataQuality: 'Datenqualität',
  evidenceUnavailable: 'Nicht verfügbar',
  evidenceSummaryTitle: 'Trip Analyse',
  tripAnalysisTitle: 'Trip Analyse',
  evidenceOverallRating: 'Gesamtbewertung',
  evidenceVehicleStress: 'Fahrbelastung',
  evidenceDrivingStyle: 'Fahrverhalten',
  evidenceReviewHints: 'Prüfhinweise',
  evidenceMisuseHint: 'Prüfhinweise',
  hfLimited: 'Daten eingeschränkt',
  hfAvailable: 'Telemetrie verfügbar',
  hfPending: 'Datenbasis fehlt',
  routeMatch: 'Routen-Match',
  damageNeutralHint:
    'Kann für Schaden- oder Beschwerdefall relevant sein — keine automatische Schadenszuordnung.',
  misuseSectionTitle: 'Prüfhinweise',
  misuseEmptyTitle: 'Keine Prüfhinweise',
  misuseEmptySubline: 'Für diese Fahrt liegen keine Prüfhinweise vor.',
  misuseReviewDisclaimer: 'Hinweis zur Prüfung — kein automatisierter Vorwurf.',
} as const;

export const BEHAVIOR_COPY = {
  pending: 'Analyse ausstehend',
  running: 'Analyse läuft',
  skippedTitle: 'Nicht analysierbar',
  skippedHint:
    'Keine ausreichenden Hochfrequenz-Telemetriedaten für diese Fahrt. Kurze Fahrten oder Sensorlücken sind möglich.',
  failedTitle: 'Analyse fehlgeschlagen',
  failedRetryHint: 'Die Analyse konnte vorübergehend nicht abgeschlossen werden. Erneut versuchen ist möglich.',
  failedPermanentTitle: 'Analyse nicht möglich',
  failedPermanentHint:
    'Für diese Fahrt liegen dauerhaft unzureichende Daten vor. Eine Belastungsauswertung ist nicht möglich.',
  notStartedTitle: 'Belastungsanalyse noch nicht durchgeführt',
  notStartedHint:
    'Hochfrequenzanalyse starten, um Brems-, Beschleunigungs- und Missbrauchsereignisse zu erkennen.',
  noEventsTitle: 'Unauffällige Fahrt',
  noEventsHint: 'Keine auffälligen Belastungs- oder Missbrauchsereignisse in der Auswertung gefunden.',
  limitedTitle: 'Eingeschränkte Datenqualität',
  limitedHint: 'Die Auswertung basiert auf unvollständigen Telemetriedaten. Ergebnisse können unvollständig sein.',
  retry: 'Erneut versuchen',
  analyze: 'Belastung analysieren',
  showOnMap: 'Auf Karte zeigen',
  noEventsInFilter: 'Keine Ereignisse in dieser Kategorie.',
  technicalDetails: 'Technische Details',
  hfDataPoints: 'HF-Datenpunkte (Summe)',
  gpsEventPositions: 'Ereignisse mit GPS',
  analysisWindow: 'Analysezeitpunkt',
  routeMatchStatus: 'Routen-Match',
  enrichmentAttempts: 'Analyseversuche',
  failureReason: 'Fehlergrund',
} as const;
