export const DI_V0_S4E_CONTROL_PLANE_CONFIG = Symbol('DI_V0_S4E_CONTROL_PLANE_CONFIG');
export const DI_V0_S4E_WORK_ITEM_REPOSITORY = Symbol('DI_V0_S4E_WORK_ITEM_REPOSITORY');
export const DI_V0_S4E_DRIFT_WATCHER_SERVICE = Symbol('DI_V0_S4E_DRIFT_WATCHER_SERVICE');
