export const M3_3_HV_H2_LONGITUDINAL_INPUT_CANDIDATE_V1 = 'M3.3-HV-H2-LONGITUDINAL-INPUT-CANDIDATE-V1' as const;
export const M3_3_HV_H2_LONGITUDINAL_INPUT_REPORT_V1 = 'M3.3-HV-H2-LONGITUDINAL-INPUT-REPORT-V1' as const;

export const M3_3_HV_H2_REPORT_TIMEOUT_MS = 90_000;

export const M3_3_HV_H2_MAX_CAPACITY_OBSERVATIONS_DEFAULT = 500;
export const M3_3_HV_H2_MAX_CAPACITY_OBSERVATIONS_HARD = 2_000;

export const M3_3_HV_H2_MAX_PROVIDER_SOH_ROWS_DEFAULT = 500;
export const M3_3_HV_H2_MAX_PROVIDER_SOH_ROWS_HARD = 2_000;

export const M3_3_HV_H2_MAX_GT_ROWS_DEFAULT = 100;
export const M3_3_HV_H2_MAX_GT_ROWS_HARD = 500;

export const M3_3_HV_H2_MAX_SESSIONS_DEFAULT = 500;
export const M3_3_HV_H2_MAX_SESSIONS_HARD = 2_000;

export const M3_3_HV_H2_REPORT_TEMPORAL_SEMANTICS =
  'OBSERVATION_EVENT_TIME_FILTERED|GT_KNOWLEDGE_AS_OF|SESSION_CONTEXT_CURRENT_OR_FAIL_CLOSED' as const;

export const BATTERY_HV_H2_ALLOW_PRODUCTION_READONLY_ENV_KEY =
  'BATTERY_HV_H2_ALLOW_PRODUCTION_READONLY';

export const METHOD_IDENTITY_REQUIRED = true as const;
export const CROSS_METHOD_POOLING_DEFAULT = false as const;

export const HV_H2_BATTERY_SCOPE = 'HV' as const;

/** Operator CLI only — no Nest controller, scheduler, or worker. */
export const H2_AUTOMATIC_RUNTIME_REACHABLE = false as const;
export const H2_OPERATOR_CLI_REACHABLE = true as const;
export const H2_CUSTOMER_RUNTIME_REACHABLE = false as const;
