export const COMPLETE_PICKUP_HANDOVER_ERROR = {
  IDEMPOTENCY_KEY_REQUIRED: 'COMPLETE_PICKUP_HANDOVER_IDEMPOTENCY_KEY_REQUIRED',
  PERMISSION_DENIED: 'COMPLETE_PICKUP_HANDOVER_PERMISSION_DENIED',
  BOOKING_NOT_FOUND: 'COMPLETE_PICKUP_HANDOVER_BOOKING_NOT_FOUND',
  BOOKING_WRONG_STATUS: 'COMPLETE_PICKUP_HANDOVER_BOOKING_WRONG_STATUS',
  BOOKING_WRONG_ORG: 'COMPLETE_PICKUP_HANDOVER_BOOKING_WRONG_ORG',
  SESSION_NOT_FOUND: 'COMPLETE_PICKUP_HANDOVER_SESSION_NOT_FOUND',
  SESSION_WRONG_STATUS: 'COMPLETE_PICKUP_HANDOVER_SESSION_WRONG_STATUS',
  VERSION_CONFLICT: 'COMPLETE_PICKUP_HANDOVER_VERSION_CONFLICT',
  VEHICLE_MISMATCH: 'COMPLETE_PICKUP_HANDOVER_VEHICLE_MISMATCH',
  VEHICLE_BLOCKED: 'COMPLETE_PICKUP_HANDOVER_VEHICLE_BLOCKED',
  VEHICLE_RENTAL_BLOCKED: 'COMPLETE_PICKUP_HANDOVER_VEHICLE_RENTAL_BLOCKED',
  SCOPE_DENIED: 'COMPLETE_PICKUP_HANDOVER_SCOPE_DENIED',
  SIGNATURE_REQUIRED: 'COMPLETE_PICKUP_HANDOVER_SIGNATURE_REQUIRED',
  DOCUMENTS_NOT_ACKNOWLEDGED: 'COMPLETE_PICKUP_HANDOVER_DOCUMENTS_NOT_ACKNOWLEDGED',
  ELIGIBILITY_BLOCKED: 'COMPLETE_PICKUP_HANDOVER_ELIGIBILITY_BLOCKED',
  GATE_BLOCKED: 'COMPLETE_PICKUP_HANDOVER_GATE_BLOCKED',
  PROTOCOL_ALREADY_EXISTS: 'COMPLETE_PICKUP_HANDOVER_PROTOCOL_ALREADY_EXISTS',
  ALREADY_COMPLETED: 'COMPLETE_PICKUP_HANDOVER_ALREADY_COMPLETED',
} as const;

export type CompletePickupHandoverErrorCode =
  (typeof COMPLETE_PICKUP_HANDOVER_ERROR)[keyof typeof COMPLETE_PICKUP_HANDOVER_ERROR];
