export const COMPLETE_RETURN_HANDOVER_ERROR = {
  IDEMPOTENCY_KEY_REQUIRED: 'COMPLETE_RETURN_HANDOVER_IDEMPOTENCY_KEY_REQUIRED',
  PERMISSION_DENIED: 'COMPLETE_RETURN_HANDOVER_PERMISSION_DENIED',
  BOOKING_NOT_FOUND: 'COMPLETE_RETURN_HANDOVER_BOOKING_NOT_FOUND',
  BOOKING_WRONG_STATUS: 'COMPLETE_RETURN_HANDOVER_BOOKING_WRONG_STATUS',
  PICKUP_PROTOCOL_REQUIRED: 'COMPLETE_RETURN_HANDOVER_PICKUP_PROTOCOL_REQUIRED',
  SESSION_NOT_FOUND: 'COMPLETE_RETURN_HANDOVER_SESSION_NOT_FOUND',
  SESSION_WRONG_STATUS: 'COMPLETE_RETURN_HANDOVER_SESSION_WRONG_STATUS',
  VERSION_CONFLICT: 'COMPLETE_RETURN_HANDOVER_VERSION_CONFLICT',
  VEHICLE_MISMATCH: 'COMPLETE_RETURN_HANDOVER_VEHICLE_MISMATCH',
  SCOPE_DENIED: 'COMPLETE_RETURN_HANDOVER_SCOPE_DENIED',
  SIGNATURE_REQUIRED: 'COMPLETE_RETURN_HANDOVER_SIGNATURE_REQUIRED',
  DOCUMENTS_NOT_ACKNOWLEDGED: 'COMPLETE_RETURN_HANDOVER_DOCUMENTS_NOT_ACKNOWLEDGED',
  ODOMETER_IMPLAUSIBLE: 'COMPLETE_RETURN_HANDOVER_ODOMETER_IMPLAUSIBLE',
  PROTOCOL_ALREADY_EXISTS: 'COMPLETE_RETURN_HANDOVER_PROTOCOL_ALREADY_EXISTS',
  CONCURRENT_COMPLETION: 'COMPLETE_RETURN_HANDOVER_CONCURRENT_COMPLETION',
  DOCUMENT_ENQUEUE_FAILED: 'COMPLETE_RETURN_HANDOVER_DOCUMENT_ENQUEUE_FAILED',
} as const;

export type CompleteReturnHandoverErrorCode =
  (typeof COMPLETE_RETURN_HANDOVER_ERROR)[keyof typeof COMPLETE_RETURN_HANDOVER_ERROR];
