/** Stable domain error codes for handover session transitions — not free-form strings. */
export const HANDOVER_SESSION_ERROR = {
  INVALID_STATUS: 'HANDOVER_SESSION_INVALID_STATUS',
  TRANSITION_FORBIDDEN: 'HANDOVER_SESSION_TRANSITION_FORBIDDEN',
  TERMINAL_IMMUTABLE: 'HANDOVER_SESSION_TERMINAL_IMMUTABLE',
  VERSION_CONFLICT: 'HANDOVER_SESSION_VERSION_CONFLICT',
  LOCK_CONFLICT: 'HANDOVER_SESSION_LOCK_CONFLICT',
  BOOKING_NOT_FOUND: 'HANDOVER_SESSION_BOOKING_NOT_FOUND',
  BOOKING_WRONG_STATUS: 'HANDOVER_SESSION_BOOKING_WRONG_STATUS',
  BOOKING_TERMINAL: 'HANDOVER_SESSION_BOOKING_TERMINAL',
  PROTOCOL_ALREADY_EXISTS: 'HANDOVER_SESSION_PROTOCOL_ALREADY_EXISTS',
  VEHICLE_BLOCKED: 'HANDOVER_SESSION_VEHICLE_BLOCKED',
  VEHICLE_RENTAL_BLOCKED: 'HANDOVER_SESSION_VEHICLE_RENTAL_BLOCKED',
  SCOPE_DENIED: 'HANDOVER_SESSION_SCOPE_DENIED',
  SCOPE_OVERRIDE_REQUIRED: 'HANDOVER_SESSION_SCOPE_OVERRIDE_REQUIRED',
  PERMISSION_DENIED: 'HANDOVER_SESSION_PERMISSION_DENIED',
  GATE_BLOCKED: 'HANDOVER_SESSION_GATE_BLOCKED',
  GATE_OVERRIDE_REQUIRED: 'HANDOVER_SESSION_GATE_OVERRIDE_REQUIRED',
  GATE_OVERRIDE_DENIED: 'HANDOVER_SESSION_GATE_OVERRIDE_DENIED',
  ELIGIBILITY_BLOCKED: 'HANDOVER_SESSION_ELIGIBILITY_BLOCKED',
  SIGNATURE_REQUIRED: 'HANDOVER_SESSION_SIGNATURE_REQUIRED',
  DOCUMENTS_NOT_ACKNOWLEDGED: 'HANDOVER_SESSION_DOCUMENTS_NOT_ACKNOWLEDGED',
  PICKUP_PROTOCOL_REQUIRED: 'HANDOVER_SESSION_PICKUP_PROTOCOL_REQUIRED',
  ACTIVE_SESSION_EXISTS: 'HANDOVER_SESSION_ACTIVE_EXISTS',
  COMPLETE_NOT_IMPLEMENTED: 'HANDOVER_SESSION_COMPLETE_NOT_IMPLEMENTED',
  SUPERSEDE_REASON_REQUIRED: 'HANDOVER_SESSION_SUPERSEDE_REASON_REQUIRED',
  CANCEL_REASON_REQUIRED: 'HANDOVER_SESSION_CANCEL_REASON_REQUIRED',
} as const;

export type HandoverSessionErrorCode =
  (typeof HANDOVER_SESSION_ERROR)[keyof typeof HANDOVER_SESSION_ERROR];
