export const HANDOVER_DRAFT_ERROR = {
  NOT_FOUND: 'HANDOVER_DRAFT_NOT_FOUND',
  EXPIRED: 'HANDOVER_DRAFT_EXPIRED',
  NOT_EDITABLE: 'HANDOVER_DRAFT_NOT_EDITABLE',
  VERSION_CONFLICT: 'HANDOVER_DRAFT_VERSION_CONFLICT',
  LOCK_CONFLICT: 'HANDOVER_DRAFT_LOCK_CONFLICT',
  SCOPE_DENIED: 'HANDOVER_DRAFT_SCOPE_DENIED',
  PERMISSION_DENIED: 'HANDOVER_DRAFT_PERMISSION_DENIED',
  ACTIVE_EXISTS: 'HANDOVER_DRAFT_ACTIVE_EXISTS',
  NOT_READY_FOR_COMPLETE: 'HANDOVER_DRAFT_NOT_READY_FOR_COMPLETE',
} as const;
