export const HANDOVER_COMPLETION_RECORD_ERROR = {
  NOT_FOUND: 'HANDOVER_COMPLETION_RECORD_NOT_FOUND',
  IMMUTABLE: 'HANDOVER_COMPLETION_RECORD_IMMUTABLE',
  OVERRIDE_PERMISSION_DENIED: 'HANDOVER_COMPLETION_OVERRIDE_PERMISSION_DENIED',
  CORRECTION_REASON_REQUIRED: 'HANDOVER_COMPLETION_CORRECTION_REASON_REQUIRED',
  SIGNATURE_REQUIRED: 'HANDOVER_COMPLETION_SIGNATURE_REQUIRED',
  PROTOCOL_NOT_FOUND: 'HANDOVER_COMPLETION_PROTOCOL_NOT_FOUND',
  ALREADY_SUPERSEDED: 'HANDOVER_COMPLETION_ALREADY_SUPERSEDED',
} as const;
