export const DI_V0_NATIVE_EVENT_EVIDENCE_ADAPTER_V0_2 = 'DI_V0_NATIVE_EVENT_EVIDENCE_ADAPTER_V0_2';
export const DI_V0_NATIVE_EVENT_EVIDENCE_SNAPSHOT_V0_2 = 'DI_V0_NATIVE_EVENT_EVIDENCE_SNAPSHOT_V0_2';

export const DI_V0_NATIVE_EVENT_EVIDENCE_KIND = 'NATIVE_EVENT_OBSERVATION' as const;
