import { Injectable, Logger, BadRequestException } from '@nestjs/common';
import { ConfigService } from '@nestjs/config';
import { createReadStream } from 'fs';
import { mkdir, readFile, unlink, writeFile } from 'fs/promises';
import { resolve, sep, dirname, extname, basename } from 'path';
import { randomUUID } from 'crypto';
import { Readable } from 'stream';
import {
  DocumentStoragePort,
  PutObjectInput,
  PutObjectResult,
} from './document-storage.interface';
import {
  DOCUMENT_STORAGE_ZONES,
  type DocumentStorageCapabilities,
  type DocumentStorageZone,
} from '../document-storage-lifecycle.types';
import documentRetentionConfig from '@config/document-retention.config';

const STORAGE_PROVIDER = 'local';

/**
 * Local-disk implementation of {@link DocumentStoragePort}.
 *
 * Files are written under `documentExtraction.localStorageDir` (default
 * `./storage/documents`), which is NOT registered as a static asset directory —
 * documents are never publicly reachable.
 *
 * Quarantined uploads are written to `documentExtraction.localQuarantineStorageDir`
 * (default `./storage/documents-quarantine`) until malware scanning promotes them.
 *
 * Object keys are fully generated by this service:
 *   organizations/{orgId}/vehicles/{vehicleId}/documents/{yyyy}/{mm}/{uuid}-{safeName}
 * The untrusted original filename is sanitised and only contributes a suffix; it
 * is never used for directory construction. Every key passed back in for read /
 * delete is validated to stay inside the base directory (path-traversal guard).
 *
 * --- Future S3-compatible provider (TODO) ---
 * Implement a sibling `S3DocumentStorageService implements DocumentStoragePort`
 * that PUTs/GETs by the same object key (it maps cleanly to an S3 key), returns
 * `storageProvider: 's3'`, and returns `null` from getInternalPath. Then bind
 * the DOCUMENT_STORAGE token by `documentExtraction.storageProvider`.
 */
@Injectable()
export class LocalDocumentStorageService implements DocumentStoragePort {
  private readonly logger = new Logger(LocalDocumentStorageService.name);
  private readonly baseDir: string;
  private readonly quarantineBaseDir: string;

  constructor(private readonly config: ConfigService) {
    const configured = this.config.get<string>(
      'documentExtraction.localStorageDir',
      './storage/documents',
    );
    this.baseDir = resolve(process.cwd(), configured);
    const quarantineConfigured = this.config.get<string>(
      'documentExtraction.localQuarantineStorageDir',
      './storage/documents-quarantine',
    );
    this.quarantineBaseDir = resolve(process.cwd(), quarantineConfigured);
  }

  getCapabilities(): DocumentStorageCapabilities {
    const retention = this.config.get<ReturnType<typeof documentRetentionConfig>>('documentRetention');
    const encryption = retention?.encryptionAtRest ?? {
      declared: false,
      provider: 'none' as const,
      kmsKeyId: null,
    };
    const backup = retention?.backup ?? {
      strategy: 'vps-pre-deploy-db' as const,
      documentObjectsIncluded: false,
      lastVerifiedAt: null,
      note: null,
    };
    return {
      provider: STORAGE_PROVIDER,
      zones: [DOCUMENT_STORAGE_ZONES.QUARANTINE, DOCUMENT_STORAGE_ZONES.CLEAN],
      transport: {
        apiTransport: 'https',
        providerTransport: 'local-filesystem',
      },
      encryptionAtRest: encryption,
      backup,
    };
  }

  resolveStorageZone(objectKey: string): DocumentStorageZone {
    return objectKey.startsWith('quarantine/') ? DOCUMENT_STORAGE_ZONES.QUARANTINE : DOCUMENT_STORAGE_ZONES.CLEAN;
  }

  async putObject(input: PutObjectInput): Promise<PutObjectResult> {
    return this.writeObject(input, this.baseDir, 'organizations');
  }

  async putQuarantineObject(input: PutObjectInput): Promise<PutObjectResult> {
    return this.writeObject(input, this.quarantineBaseDir, 'quarantine/organizations');
  }

  async promoteQuarantineToClean(input: {
    quarantineObjectKey: string;
    organizationId: string;
    vehicleId: string;
    originalName: string;
    mimeType: string;
  }): Promise<PutObjectResult> {
    const quarantinePath = this.resolveKeyInBase(this.quarantineBaseDir, input.quarantineObjectKey);
    const buffer = await readFile(quarantinePath);
    const stored = await this.putObject({
      organizationId: input.organizationId,
      vehicleId: input.vehicleId,
      originalName: input.originalName,
      buffer,
      mimeType: input.mimeType,
    });
    await unlink(quarantinePath).catch(() => undefined);
    return stored;
  }

  async getObject(objectKey: string): Promise<Buffer> {
    const absPath = this.resolveKey(objectKey);
    return readFile(absPath);
  }

  async getObjectStream(objectKey: string): Promise<Readable> {
    const absPath = this.resolveKey(objectKey);
    return createReadStream(absPath);
  }

  async deleteObject(objectKey: string): Promise<void> {
    try {
      const absPath = this.resolveKey(objectKey);
      await unlink(absPath).catch(() => undefined);
    } catch (err) {
      this.logger.debug(`deleteObject(${objectKey}) skipped: ${(err as Error).message}`);
    }
  }

  getInternalPath(objectKey: string): string | null {
    if (objectKey.startsWith('quarantine/')) {
      return this.resolveKeyInBase(this.quarantineBaseDir, objectKey);
    }
    return this.resolveKey(objectKey);
  }

  // ── internals ──────────────────────────────────────────────────────────

  private async writeObject(
    input: PutObjectInput,
    baseDir: string,
    keyPrefix: string,
  ): Promise<PutObjectResult> {
    const orgSeg = this.safeSegment(input.organizationId);
    if (!orgSeg) {
      throw new BadRequestException('organizationId is required for storage');
    }

    const now = new Date();
    const yyyy = String(now.getUTCFullYear());
    const mm = String(now.getUTCMonth() + 1).padStart(2, '0');
    const safeName = this.sanitizeFileName(input.originalName);

    const vehSeg = input.vehicleId ? this.safeSegment(input.vehicleId) : null;
    const objectKey = vehSeg
      ? [keyPrefix, orgSeg, 'vehicles', vehSeg, 'documents', yyyy, mm, `${randomUUID()}-${safeName}`].join(
          '/',
        )
      : [
          keyPrefix,
          orgSeg,
          'inbox',
          'documents',
          yyyy,
          mm,
          `${randomUUID()}-${safeName}`,
        ].join('/');

    const absPath = this.resolveKeyInBase(baseDir, objectKey);
    await mkdir(dirname(absPath), { recursive: true });
    await writeFile(absPath, input.buffer);

    return {
      objectKey,
      storageProvider: STORAGE_PROVIDER,
      sizeBytes: input.buffer.length,
      mimeType: input.mimeType,
    };
  }

  private resolveKey(objectKey: string): string {
    if (objectKey.startsWith('quarantine/')) {
      return this.resolveKeyInBase(this.quarantineBaseDir, objectKey);
    }
    return this.resolveKeyInBase(this.baseDir, objectKey);
  }

  /**
   * Resolves an object key to an absolute path and asserts it stays inside the
   * base directory. Rejects absolute keys, `..` traversal, and NUL bytes.
   */
  private resolveKeyInBase(baseDir: string, objectKey: string): string {
    if (typeof objectKey !== 'string' || objectKey.length === 0) {
      throw new BadRequestException('Invalid object key');
    }
    if (objectKey.includes('\0') || objectKey.includes('..')) {
      throw new BadRequestException('Invalid object key');
    }
    const normalized = objectKey.replace(/\\/g, '/').replace(/^\/+/, '');
    if (/^[a-zA-Z]:/.test(normalized)) {
      throw new BadRequestException('Invalid object key');
    }
    const abs = resolve(baseDir, normalized);
    const baseWithSep = baseDir.endsWith(sep) ? baseDir : baseDir + sep;
    if (abs !== baseDir && !abs.startsWith(baseWithSep)) {
      throw new BadRequestException('Invalid object key (path traversal)');
    }
    return abs;
  }

  /** A single path segment derived from a trusted id (uuid). Defensive only. */
  private safeSegment(value: string): string {
    if (!value) return '';
    return basename(String(value)).replace(/[^a-zA-Z0-9_-]/g, '');
  }

  /**
   * Sanitises an untrusted original filename into a safe suffix. Keeps a known
   * extension, strips directories, and collapses unsafe characters.
   */
  private sanitizeFileName(originalName: string): string {
    const base = basename(String(originalName || 'document'));
    const ext = extname(base).toLowerCase().replace(/[^a-z0-9.]/g, '');
    const stem = base
      .slice(0, base.length - extname(base).length)
      .replace(/[^a-zA-Z0-9_-]/g, '_')
      .replace(/_+/g, '_')
      .slice(0, 60) || 'document';
    const safeExt = ext && ext.length <= 6 ? ext : '';
    return `${stem}${safeExt}`;
  }
}
