export const VEHICLE_REGISTRY_LIFECYCLE_OUTBOX_WORKER_INTERVAL_MS = 30_000;
export const VEHICLE_REGISTRY_LIFECYCLE_OUTBOX_BATCH_SIZE = 25;
export const VEHICLE_REGISTRY_LIFECYCLE_OUTBOX_MAX_RETRIES = 12;
