export const BOOKING_IDEMPOTENCY_ERROR_CODES = {
  IDEMPOTENCY_KEY_REQUIRED: 'IDEMPOTENCY_KEY_REQUIRED',
  IDEMPOTENCY_KEY_REUSED: 'IDEMPOTENCY_KEY_REUSED',
  IDEMPOTENCY_IN_PROGRESS: 'IDEMPOTENCY_IN_PROGRESS',
} as const;

export const BOOKING_IDEMPOTENCY_OPERATIONS = {
  BOOKING_CREATE: 'BOOKING_CREATE',
  BOOKING_UPDATE_SCHEDULE: 'BOOKING_UPDATE_SCHEDULE',
  BOOKING_UPDATE_VEHICLE: 'BOOKING_UPDATE_VEHICLE',
  BOOKING_DOCUMENT_GENERATE: 'BOOKING_DOCUMENT_GENERATE',
  BOOKING_DOCUMENT_EMAIL: 'BOOKING_DOCUMENT_EMAIL',
  BOOKING_INVOICE_BOOTSTRAP: 'BOOKING_INVOICE_BOOTSTRAP',
} as const;

export type BookingIdempotencyOperation =
  (typeof BOOKING_IDEMPOTENCY_OPERATIONS)[keyof typeof BOOKING_IDEMPOTENCY_OPERATIONS];

/** Default retention: 72 hours. Override via BOOKING_IDEMPOTENCY_RETENTION_HOURS. */
export const DEFAULT_BOOKING_IDEMPOTENCY_RETENTION_HOURS = 72;

export const BOOKING_IDEMPOTENCY_SENSITIVE_KEYS = new Set([
  'customerSignatureDataUrl',
  'customerSignatureName',
  'signatureDataUrl',
  'paymentMethodDetails',
  'cardNumber',
  'cvv',
  'iban',
  'password',
  'token',
  'secret',
]);
