import type {
  E7RecommendationCategory,
  E7RecommendationFamily,
} from './evaluations-recommendations.contract';

/** Server-internal deterministic sort buckets (not exposed as category enum). */
export const E7_RECOMMENDATION_SORT_BUCKET_ORDER: Readonly<
  Record<E7RecommendationFamily, number>
> = {
  RECEIVABLES_ATTENTION: 10,
  OPEN_RECEIVABLES_REVIEW: 20,
  WEAKNESS_ATTENTION: 30,
  UTILIZATION_ATTENTION: 40,
  COST_EVIDENCE_INCOMPLETE: 50,
  DATA_QUALITY_LIMITED: 60,
  DETECTION_INPUT_SKIPPED: 70,
  DRIVER_INFLUENCE_REVIEW: 80,
  STRENGTH_REINFORCE: 90,
};

export const E7_FAMILY_CATEGORY: Readonly<Record<E7RecommendationFamily, E7RecommendationCategory>> = {
  RECEIVABLES_ATTENTION: 'FINANCE',
  OPEN_RECEIVABLES_REVIEW: 'FINANCE',
  WEAKNESS_ATTENTION: 'FLEET',
  UTILIZATION_ATTENTION: 'FLEET',
  COST_EVIDENCE_INCOMPLETE: 'OPERATIONS',
  DATA_QUALITY_LIMITED: 'QUALITY',
  DETECTION_INPUT_SKIPPED: 'INSIGHT',
  DRIVER_INFLUENCE_REVIEW: 'DRIVER',
  STRENGTH_REINFORCE: 'INSIGHT',
};

export const E7_FAMILY_IMPLEMENTATION_STATUS: Readonly<
  Record<E7RecommendationFamily, 'IMPLEMENTED' | 'DEFERRED_WITH_AUTHORITY_REASON'>
> = {
  WEAKNESS_ATTENTION: 'IMPLEMENTED',
  STRENGTH_REINFORCE: 'IMPLEMENTED',
  UTILIZATION_ATTENTION: 'IMPLEMENTED',
  RECEIVABLES_ATTENTION: 'IMPLEMENTED',
  OPEN_RECEIVABLES_REVIEW: 'IMPLEMENTED',
  COST_EVIDENCE_INCOMPLETE: 'IMPLEMENTED',
  DATA_QUALITY_LIMITED: 'IMPLEMENTED',
  DRIVER_INFLUENCE_REVIEW: 'IMPLEMENTED',
  DETECTION_INPUT_SKIPPED: 'IMPLEMENTED',
};

export const E7_SEVERITY_RANK: Readonly<Record<'CRITICAL' | 'WARNING' | 'INFO', number>> = {
  CRITICAL: 0,
  WARNING: 1,
  INFO: 2,
};

export const E7_WEAKNESS_RULE_UNDERUTILIZATION = 'UNDERUTILIZATION' as const;
