import { DOCUMENT_TYPE, type DocumentType } from '../documents.constants';

/** Persistent workflow states for booking document generation jobs (Prompt 19). */
export const BOOKING_DOCUMENT_GENERATION_STATUS = {
  PENDING: 'PENDING',
  PROCESSING: 'PROCESSING',
  SUCCEEDED: 'SUCCEEDED',
  FAILED_RETRYABLE: 'FAILED_RETRYABLE',
  FAILED_FINAL: 'FAILED_FINAL',
} as const;

export type BookingDocumentGenerationStatus =
  (typeof BOOKING_DOCUMENT_GENERATION_STATUS)[keyof typeof BOOKING_DOCUMENT_GENERATION_STATUS];

export const BOOKING_DOCUMENT_GENERATION_JOB_TYPE = {
  INITIAL_BUNDLE: 'INITIAL_BUNDLE',
  REGENERATE: 'REGENERATE',
  PICKUP_PROTOCOL: 'PICKUP_PROTOCOL',
  RETURN_PROTOCOL: 'RETURN_PROTOCOL',
  FINAL_INVOICE: 'FINAL_INVOICE',
} as const;

export type BookingDocumentGenerationJobType =
  (typeof BOOKING_DOCUMENT_GENERATION_JOB_TYPE)[keyof typeof BOOKING_DOCUMENT_GENERATION_JOB_TYPE];

export const BOOKING_DOCUMENT_GENERATION_ERROR_CODE = {
  NOT_FOUND: 'BOOKING_DOC_GEN_NOT_FOUND',
  TENANT_MISMATCH: 'BOOKING_DOC_GEN_TENANT_MISMATCH',
  INVALID_PAYLOAD: 'BOOKING_DOC_GEN_INVALID_PAYLOAD',
  IMMUTABLE: 'BOOKING_DOC_GEN_IMMUTABLE',
  MAX_ATTEMPTS_EXCEEDED: 'BOOKING_DOC_GEN_MAX_ATTEMPTS_EXCEEDED',
  GENERATION_DISABLED: 'BOOKING_DOC_GEN_GENERATION_DISABLED',
  EXECUTION_FAILED: 'BOOKING_DOC_GEN_EXECUTION_FAILED',
} as const;

export const BOOKING_DOCUMENT_GENERATION_DEFAULT_MAX_ATTEMPTS = 5;
export const BOOKING_DOCUMENT_GENERATION_BASE_BACKOFF_MS = 5_000;

export const BOOKING_DOCUMENT_GENERATION_TERMINAL_STATUSES = new Set<BookingDocumentGenerationStatus>([
  BOOKING_DOCUMENT_GENERATION_STATUS.SUCCEEDED,
  BOOKING_DOCUMENT_GENERATION_STATUS.FAILED_FINAL,
]);

/**
 * Booking logic must distinguish sync guarantees vs async generation.
 * Wizard/admin sync paths may still call bundle service directly.
 */
export const BOOKING_DOCUMENT_GENERATION_POLICY = {
  /** Document types that wizard checkout awaits synchronously (unchanged UX). */
  SYNCHRONOUS_ON_CHECKOUT: [
    DOCUMENT_TYPE.BOOKING_INVOICE,
    DOCUMENT_TYPE.DEPOSIT_RECEIPT,
    DOCUMENT_TYPE.RENTAL_CONTRACT,
    DOCUMENT_TYPE.TERMS_AND_CONDITIONS,
    DOCUMENT_TYPE.CONSUMER_INFORMATION,
    DOCUMENT_TYPE.PRIVACY_POLICY,
  ] as DocumentType[],

  /** Enqueued after booking create/confirm — non-blocking for HTTP. */
  ASYNC_ON_BOOKING_CONFIRM: [
    DOCUMENT_TYPE.BOOKING_INVOICE,
    DOCUMENT_TYPE.DEPOSIT_RECEIPT,
    DOCUMENT_TYPE.RENTAL_CONTRACT,
    DOCUMENT_TYPE.TERMS_AND_CONDITIONS,
    DOCUMENT_TYPE.CONSUMER_INFORMATION,
    DOCUMENT_TYPE.PRIVACY_POLICY,
  ] as DocumentType[],

  /** Enqueued after pickup handover. */
  ASYNC_ON_PICKUP: [DOCUMENT_TYPE.HANDOVER_PICKUP] as DocumentType[],

  /** Enqueued after return handover. */
  ASYNC_ON_RETURN: [DOCUMENT_TYPE.HANDOVER_RETURN, DOCUMENT_TYPE.FINAL_INVOICE] as DocumentType[],

  /** Errors that should mark job FAILED_FINAL (no retry). */
  BLOCKING_ERROR_PATTERNS: [
    'TENANT_MISMATCH',
    'NOT_FOUND',
    'MISSING_MANDATORY',
    'RESOLVER_CONFLICT',
  ] as const,
} as const;

export const BOOKING_DOCUMENT_GENERATION_BULL_JOB_NAME = 'generate';
