import type { CommunicationConversationListResponse } from './types';

/** Canonical C7 list response fixture for contract tests. */
export const COMMUNICATION_LIST_CONTRACT_FIXTURE: CommunicationConversationListResponse = {
  items: [
    {
      id: '00000000-0000-4000-8000-000000000101',
      channel: 'WHATSAPP',
      status: 'AI_ACTIVE',
      unreadCount: 2,
      lastActivityAt: '2026-08-22T10:30:00.000Z',
      displayLabel: 'Max Mustermann',
      lastMessagePreview: 'Pickup reminder sent',
      customer: { id: 'cust-1', displayName: 'Max Mustermann' },
      booking: { id: 'book-1', reference: 'BK-ABC123' },
      vehicle: { id: 'veh-1', displayLabel: 'KS-AB 123' },
      station: null,
      assignedUser: null,
      assignedAgent: null,
    },
    {
      id: '00000000-0000-4000-8000-000000000102',
      channel: 'VOICE',
      status: 'HUMAN_REQUIRED',
      unreadCount: 0,
      lastActivityAt: '2026-08-22T09:15:00.000Z',
      displayLabel: 'Unknown contact',
      lastMessagePreview: null,
      customer: null,
      booking: null,
      vehicle: null,
      station: null,
      assignedUser: { id: 'user-1', displayName: 'Ops User' },
      assignedAgent: null,
    },
    {
      id: '00000000-0000-4000-8000-000000000103',
      channel: 'SMS',
      status: 'WAITING_CUSTOMER',
      unreadCount: 1,
      lastActivityAt: '2026-08-22T08:00:00.000Z',
      displayLabel: 'Anna Schmidt',
      lastMessagePreview: 'cc:IMAGE',
      customer: { id: 'cust-2', displayName: 'Anna Schmidt' },
      booking: null,
      vehicle: null,
      station: { id: 'station-1', name: 'Berlin Mitte' },
      assignedUser: null,
      assignedAgent: null,
    },
  ],
  nextCursor: 'cursor-page-2',
  hasMore: true,
};

export const COMMUNICATION_LIST_PAGE_2_FIXTURE: CommunicationConversationListResponse = {
  items: [
    {
      id: '00000000-0000-4000-8000-000000000103',
      channel: 'SMS',
      status: 'WAITING_CUSTOMER',
      unreadCount: 1,
      lastActivityAt: '2026-08-22T08:00:00.000Z',
      displayLabel: 'Anna Schmidt',
      lastMessagePreview: 'cc:IMAGE',
      customer: { id: 'cust-2', displayName: 'Anna Schmidt' },
      booking: null,
      vehicle: null,
      station: { id: 'station-1', name: 'Berlin Mitte' },
      assignedUser: null,
      assignedAgent: null,
    },
    {
      id: '00000000-0000-4000-8000-000000000104',
      channel: 'WHATSAPP',
      status: 'RESOLVED',
      unreadCount: 0,
      lastActivityAt: '2026-08-21T18:00:00.000Z',
      displayLabel: 'Fleet Support',
      lastMessagePreview: 'Thanks!',
      customer: { id: 'cust-3', displayName: 'Fleet Support' },
      booking: null,
      vehicle: null,
      station: null,
      assignedUser: null,
      assignedAgent: null,
    },
  ],
  nextCursor: null,
  hasMore: false,
};
