export const WORKFLOW_EXECUTION_SNAPSHOT_ERROR_CODES = {
  NOT_FOUND: 'WORKFLOW_EXECUTION_SNAPSHOT_NOT_FOUND',
  RUN_NOT_FOUND: 'WORKFLOW_RUN_NOT_FOUND',
  VERSION_NOT_FOUND: 'WORKFLOW_VERSION_NOT_FOUND',
  DEFINITION_NOT_FOUND: 'WORKFLOW_DEFINITION_NOT_FOUND',
  FOREIGN_TENANT: 'WORKFLOW_EXECUTION_SNAPSHOT_FOREIGN_TENANT',
  ALREADY_EXISTS: 'WORKFLOW_EXECUTION_SNAPSHOT_ALREADY_EXISTS',
  IMMUTABLE: 'WORKFLOW_EXECUTION_SNAPSHOT_IMMUTABLE',
  AUDIT_READ_FORBIDDEN: 'WORKFLOW_EXECUTION_SNAPSHOT_AUDIT_READ_FORBIDDEN',
  INVALID_VERSION_STATE: 'WORKFLOW_EXECUTION_SNAPSHOT_INVALID_VERSION_STATE',
  SECRET_DETECTED: 'WORKFLOW_EXECUTION_SNAPSHOT_SECRET_DETECTED',
} as const;
