/** Stable, machine-readable codes for booking create validation failures. */
export const BOOKING_CREATE_ERROR_CODES = {
  INVALID_BOOKING_INSTANT: 'INVALID_BOOKING_INSTANT',
  BOOKING_END_BEFORE_START: 'BOOKING_END_BEFORE_START',
  BOOKING_INVALID_DATES: 'BOOKING_INVALID_DATES',
  BOOKING_CONFLICTING_DATE_ALIASES: 'BOOKING_CONFLICTING_DATE_ALIASES',
  BOOKING_CONFLICTING_QUOTE_ALIASES: 'BOOKING_CONFLICTING_QUOTE_ALIASES',
  PRICING_QUOTE_REQUIRED: 'PRICING_QUOTE_REQUIRED',
  BOOKING_CURRENCY_MISMATCH: 'BOOKING_CURRENCY_MISMATCH',
  BOOKING_MINIMUM_RENTAL_DAYS: 'BOOKING_MINIMUM_RENTAL_DAYS',
  BOOKING_MAXIMUM_RENTAL_DAYS: 'BOOKING_MAXIMUM_RENTAL_DAYS',
  CUSTOMER_NOT_FOUND: 'CUSTOMER_NOT_FOUND',
  VEHICLE_NOT_FOUND: 'VEHICLE_NOT_FOUND',
  STATION_NOT_FOUND: 'STATION_NOT_FOUND',
  ALLOWED_DRIVER_NOT_FOUND: 'ALLOWED_DRIVER_NOT_FOUND',
  ALLOWED_DRIVER_IS_CONTRACT_HOLDER: 'ALLOWED_DRIVER_IS_CONTRACT_HOLDER',
  ALLOWED_DRIVER_DUPLICATE: 'ALLOWED_DRIVER_DUPLICATE',
  ONE_WAY_RENTAL_MISMATCH: 'ONE_WAY_RENTAL_MISMATCH',
  CLIENT_PRICE_NOT_ALLOWED: 'CLIENT_PRICE_NOT_ALLOWED',
  VEHICLE_RENTAL_BLOCKED: 'VEHICLE_RENTAL_BLOCKED',
  VEHICLE_HEALTH_GATE_UNAVAILABLE: 'VEHICLE_HEALTH_GATE_UNAVAILABLE',
  CUSTOMER_BOOKING_BLOCKED: 'CUSTOMER_BOOKING_BLOCKED',
  CUSTOMER_CONFIRMATION_BLOCKED: 'CUSTOMER_CONFIRMATION_BLOCKED',
  BOOKING_CONFLICT: 'BOOKING_CONFLICT',
} as const;

export type BookingCreateErrorCode =
  (typeof BOOKING_CREATE_ERROR_CODES)[keyof typeof BOOKING_CREATE_ERROR_CODES];

/** Default maximum rental duration when no tariff/org rule defines one (days). */
export const DEFAULT_MAXIMUM_RENTAL_DAYS = 365;
