/** Stable, machine-readable codes for handover validation failures. */
export const HANDOVER_ERROR_CODES = {
  INVALID_PAYLOAD: 'HANDOVER_INVALID_PAYLOAD',
  ODOMETER_NEGATIVE: 'HANDOVER_ODOMETER_NEGATIVE',
  ODOMETER_BELOW_PICKUP: 'HANDOVER_ODOMETER_BELOW_PICKUP',
  ODOMETER_OVERRIDE_REASON_REQUIRED: 'HANDOVER_ODOMETER_OVERRIDE_REASON_REQUIRED',
  ODOMETER_OVERRIDE_DENIED: 'HANDOVER_ODOMETER_OVERRIDE_DENIED',
  FUEL_PERCENT_OUT_OF_RANGE: 'HANDOVER_FUEL_PERCENT_OUT_OF_RANGE',
  CHARGE_PERCENT_OUT_OF_RANGE: 'HANDOVER_CHARGE_PERCENT_OUT_OF_RANGE',
  WARNING_LIGHTS_NOTES_REQUIRED: 'HANDOVER_WARNING_LIGHTS_NOTES_REQUIRED',
  SIGNATURE_DATA_URL_INVALID: 'HANDOVER_SIGNATURE_DATA_URL_INVALID',
  SIGNATURE_DATA_URL_TOO_LARGE: 'HANDOVER_SIGNATURE_DATA_URL_TOO_LARGE',
  SIGNATURE_MIME_NOT_ALLOWED: 'HANDOVER_SIGNATURE_MIME_NOT_ALLOWED',
  DAMAGE_ID_NOT_FOUND: 'HANDOVER_DAMAGE_ID_NOT_FOUND',
  DAMAGE_VEHICLE_MISMATCH: 'HANDOVER_DAMAGE_VEHICLE_MISMATCH',
  STATION_NOT_FOUND: 'HANDOVER_STATION_NOT_FOUND',
  STATION_NOT_ENABLED: 'HANDOVER_STATION_NOT_ENABLED',
  ACTOR_MANIPULATION: 'HANDOVER_ACTOR_MANIPULATION',
  PERFORMED_AT_INVALID: 'HANDOVER_PERFORMED_AT_INVALID',
  PERFORMED_AT_FUTURE: 'HANDOVER_PERFORMED_AT_FUTURE',
  PERFORMED_AT_TOO_EARLY: 'HANDOVER_PERFORMED_AT_TOO_EARLY',
  PICKUP_WRONG_STATUS: 'HANDOVER_PICKUP_WRONG_STATUS',
  RETURN_WRONG_STATUS: 'HANDOVER_RETURN_WRONG_STATUS',
  ALREADY_EXISTS: 'HANDOVER_ALREADY_EXISTS',
  PICKUP_VEHICLE_BLOCKED: 'HANDOVER_PICKUP_VEHICLE_BLOCKED',
  OVERRIDE_REASON_REQUIRED: 'HANDOVER_OVERRIDE_REASON_REQUIRED',
  OVERRIDE_DENIED: 'HANDOVER_OVERRIDE_DENIED',
  TECHNICAL_OBSERVATION_INVALID: 'HANDOVER_TECHNICAL_OBSERVATION_INVALID',
} as const;

export type HandoverErrorCode =
  (typeof HANDOVER_ERROR_CODES)[keyof typeof HANDOVER_ERROR_CODES];

/** Maximum decoded signature image size (bytes). */
export const HANDOVER_SIGNATURE_MAX_BYTES = 512 * 1024;

/** Allowed signature MIME types (data URL prefix). */
export const HANDOVER_SIGNATURE_ALLOWED_MIMES = new Set([
  'image/png',
  'image/jpeg',
  'image/jpg',
  'image/webp',
]);

export const HANDOVER_ODOMETER_MAX_KM = 9_999_999;
export const HANDOVER_OVERRIDE_REASON_MIN_LENGTH = 10;
export const HANDOVER_OVERRIDE_REASON_MAX_LENGTH = 2000;
export const HANDOVER_NOTES_MAX_LENGTH = 5000;
export const HANDOVER_WARNING_LIGHTS_NOTES_MAX_LENGTH = 2000;
export const HANDOVER_SIGNATURE_NAME_MAX_LENGTH = 200;
export const HANDOVER_DAMAGE_IDS_MAX = 50;
export const HANDOVER_TECHNICAL_OBSERVATIONS_MAX = 20;
export const HANDOVER_TECHNICAL_OBSERVATION_DESCRIPTION_MAX = 2000;
